- README.md
- README.rst
This is necessary for pypi and readthedocs
> Change README format to rst

- circle.yml
- fmriprep/run_workflow.py
- fmriprep/utils/misc.py
- fmriprep/workflows/__init__.py
- fmriprep/workflows/base.py
- setup.py
Expanded on gather bids data to allow for workflows to be executed per subject session. Still some issues with executing EPI Unwrap Workflow.
> Updates to how dataset is read and workflows executed on it.

- fmriprep/utils/misc.py
- fmriprep/utils/misc_test.py
- fmriprep/utils/test.py
Theres some unit tests to boot, but these still need to be integrated into circle ci.
> Updates to collect bids to match original workflows gathered files

- build/circle_setup.sh
- fmriprep/__init__.py
- fmriprep/run_workflow.py
- fmriprep/viz/__init__.py
> [FIX] relative imports

- fmriprep/workflows/anatomical.py
- fmriprep/workflows/epi.py
- fmriprep/workflows/fieldmap.py
Moved skull stripping image creation into their respective workflows and have them output to the same directory based on the work_dir setting.
> Skull Stripping Image Overlays

- fmriprep/run_workflow.py
- fmriprep/workflows/anatomical.py
Now, the use of brain extraction from ANTs is optional. It is enabled with the flag ```--skull-strip-ants```
> [ENH] Add AFNI skull strip

- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/bids.py
- fmriprep/workflows/base.py
- fmriprep/workflows/epi.py
- fmriprep/workflows/fieldmap.py
> [ENH] Use ApplyTOPUP to correct the SE images

- fmriprep/run_workflow.py
- requirements.txt
> [ENH] Improvements in output directories

- fmriprep/run_workflow.py
- fmriprep/utils/test_misc.py
- fmriprep/viz/pipeline_reports.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/epi.py
- fmriprep/workflows/fieldmap.py
- fmriprep/workflows/sbref.py
@oesteban @rwblair I would like confirmation that this is ok from one of you before I merge
> make settings['workdir'] always accessible; absolute imports

- fmriprep/run_workflow.py
- fmriprep/utils/misc.py
> More work on multiple runs in epi data.

- CHANGES.rst
- fmriprep/__init__.py
- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/bids.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/epi.py
Implementing #44 partially and starting with #68.
> [ENH] Output data sinks

- Dockerfile
- build/files/run_fmriprep
- build/files/run_unittests
... so that @shoshber can continue with #107
> [FIX] Generated new Dockerfile with new containers

- fmriprep/workflows/base.py
- fmriprep/workflows/fieldmap/base.py
- fmriprep/workflows/fieldmap/se_fmap_workflow.py
- test/workflows/fieldmap/test_fieldmap.py
A cosmetic change that closes #62
> [FIX] Replace se_pair by se_fmap

- circle.yml
- fmriprep/run_workflow.py
> make cli BIDS-Apps compliant 2.0

- fmriprep/run_workflow.py
- fmriprep/workflows/fieldmap/base.py
- requirements.txt
> depend on latest nipype master 2.0

- README.rst
- docs/about.rst
- docs/authors.rst
- docs/index.rst
> [ENH] Write documentation for beter RTD render

- CHANGES.rst
- circle.yml
- fmriprep/run_workflow.py
- fmriprep/workflows/anatomical.py
> [ENH] Added merger node to accept list of T1s

- fmriprep/workflows/epi.py
I'm still working on testing this. Opening PR in case @oesteban has any comments while its being tested.
> [WIP] Issue44

- build/files/run_fmriprep
- circle.yml
- fmriprep/interfaces/bids.py
- fmriprep/run_workflow.py
- fmriprep/utils/__init__.py
- fmriprep/utils/misc.py
> [ENH] Miscelaneous improvements

- fmriprep/workflows/anatomical.py
so far: update template being used by robust normilization in anatomical workflow
> [RTM] Minor changes to correct anatomical workflow.

- fmriprep/workflows/epi.py
> [RTM] we don't need to call fslroi to get the image affine

- fmriprep/workflows/base.py
- fmriprep/workflows/epi.py
Reuse epi_mean instead of recalculating it
> [RTM] reuse existing mean

- fmriprep/workflows/epi.py
> [RTM] use mean epi for bet

- Dockerfile
- fmriprep/interfaces/bids.py
- fmriprep/interfaces/utils.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/confounds.py
- fmriprep/workflows/epi.py
- test/workflows/test_confounds.py
Rename and reformat outputs to conform with BIDS Derivatives.
Closes #68.
> [RTM] Enh/derivatives

- Dockerfile
- fmriprep/interfaces/bids.py
- fmriprep/interfaces/utils.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/confounds.py
- fmriprep/workflows/epi.py
- test/workflows/test_confounds.py
Reverts poldracklab/fmriprep#208
> Revert "[RTM] Enh/derivatives"

- fmriprep/workflows/anatomical.py
> [RTM] Fixes #207

- Dockerfile
- fmriprep/interfaces/bids.py
- fmriprep/interfaces/utils.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/confounds.py
- fmriprep/workflows/epi.py
- test/workflows/test_confounds.py
Reverts poldracklab/fmriprep#211
> Revert "Revert "[RTM] Enh/derivatives""

- Dockerfile
This will hopefully mitigate the multiproc deadlocks. See https://github.com/nipy/nipype/issues/1692
> [RTM] switching to python3

- circle.yml
- fmriprep/interfaces/bids.py
- fmriprep/workflows/fieldmap/__init__.py
- fmriprep/workflows/fieldmap/base.py
- fmriprep/workflows/fieldmap/phase_diff_and_magnitudes.py
- fmriprep/workflows/fieldmap/se_fmap_workflow.py
- fmriprep/workflows/fieldmap/unwarp.py
- fmriprep/workflows/fieldmap/utils.py
- test/workflows/fieldmap/test_fieldmap.py
Several improvements to make this workflow a bit more reliable:
- Updated the ReadSidecarJSON interface with the latest version from mriqc (fixes several problems of the former version).
- To consider: moving in niworkflows.
- Updated the function to create Topup encoding files
- To consider: submit a complete interface to nipype, since that'd is extremely useful for people if we do it correctly).
- NOTE: I haven't implemented the "EchoTime" case yet, since we are aiming at Dec 15. In a future, that should be also implemented, along with a better logic (i.e. what to do if a file has all sorts of ways to calculate the echo time).
- Remove the old JSONFileGrabber to get the settings for ants, using the ```from_file``` new feature of nipype.
- By the title of the PR I wouldn't expect less …
> [RTM] Some love to sdc_unwarp

- fmriprep/interfaces/utils.py
- fmriprep/workflows/epi.py
> [RTM] use nibabel to merge nifti files

- fmriprep/run_workflow.py
- fmriprep/workflows/base.py
- Allow user to force a specific workflow. Closes #188 
- Raise an exception if T1w images are missing. Closes #217
> [RTM] manual workflow type and missing T1ws error

- fmriprep/interfaces/bids.py
- fmriprep/run_workflow.py
- fmriprep/viz/config.json
- fmriprep/viz/report.tpl
- fmriprep/viz/reports.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/epi.py
- fmriprep/workflows/sbref.py
Updates to the report datasinks and report aggregator configuration.
> [WIP]Report datasinks

- fmriprep/run_workflow.py
- fmriprep/utils/misc.py
- fmriprep/workflows/base.py
This will be useful for datasets with multiple tasks (like Reward/Beast).
> [RTM] add an option to limit the analysis just to one task

- fmriprep/viz/config.json
- fmriprep/viz/report.tpl
- fmriprep/viz/reports.py
There were two images with different titles but the same image in reports for ds054.
Need to confirm these changes don't mess with ds005 in any way.
> [RTM]Fix sbref dupe

- fmriprep/workflows/sbref.py
> [RTM] move reorient to beginning of sbref processing

- requirements.txt
Bleeding edge requirements are installed in the Dockerfile.
> [RTM] Deleting unused file

- fmriprep/viz/report.tpl
> [RTM]add padding so that navbar doesn't clobber content

- Dockerfile
- requirements.txt
As per https://github.com/poldracklab/fmriprep/issues/273#issuecomment-266902355. Fixes #278
> bringing back requirements.txt

- requirements.txt
Updates niworkflows and closes #277
> [RTM] niworkflows version bump

- requirements.txt
> [RTM] niworkflows update

- fmriprep/run_workflow.py
- fmriprep/viz/report.tpl
- fmriprep/viz/reports.py
- fmriprep/workflows/base.py
addresses some concerns in #66 Present commits pull in all present crashfiles. May limit this to all crash files generated in the last 24hours. Or we may consider cleaning up crash files on each new run.
> [RTM]Fix for Issue #66

- setup.py
> Add viz/*.json to package_data

- Dockerfile
- build/files/run_fmriprep
- build/files/run_unittests
- circle.yml
- clean up and slim down the dockerfile
- add metadata
- make CircleCI push versioned images upon release
- latest docker hub tag will point to the latest release
Closes #273
> [RTM] dockerfile refactor

- circle.yml
- docs/ds005.rst
- docs/installation.rst
- fmriprep/run_workflow.py
- fmriprep/workflows/base.py
Closes #311.
This PR does not touch internal function names (I did not want to change too much just before the release). This will be dealt with in #322
> [RTM] replace -t with --ignore

- docs/conf.py
See: http://fmriprep.readthedocs.io/en/fix-print_args/usage.html
Closes #327
> [RTM] include cmd args in documentation

- fmriprep/interfaces/bids.py
- fmriprep/workflows/base.py
Right now, the DictStrAny does not take in unicode strings.
This PR patches that.
> Make BIDSDataGrabber great (python<3) again

- fmriprep/run_workflow.py
- fmriprep/viz/report.tpl
- fmriprep/viz/reports.py
- fmriprep/workflows/base.py
- Fixes #354 
- Fixes a bug with error toggle link in the report sending users to the top of the report
- Improves rendering of tracebacks
- Improves precision of ignored exceptions
- Adds an assertion
> [RTM] Improvements to error reporting

- docs/workflows.rst
- fmriprep/interfaces/bids.py
- fmriprep/run_workflow.py
- fmriprep/viz/reports.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/confounds.py
- fmriprep/workflows/epi.py
- fmriprep/workflows/sbref.py
- test/interfaces/test_bids.py
- test/workflows/test_base.py
- test/workflows/test_confounds.py
> derivatives restructuring

- fmriprep/run_workflow.py
- fmriprep/viz/reports.py
- fmriprep/workflows/base.py
Simplifies the code and makes debugging less confusing.
> [RTM] limit report generation only to the subjects that were analyzed

- fmriprep/workflows/anatomical.py
Detected when attempting to run on `uh2/sub-s483`.
> [RTM] Handle multiple T1s gracefully in FS workflow

- fmriprep/run_workflow.py
> [RTM] Disable logging

- fmriprep/interfaces/utils.py
- fmriprep/workflows/epi.py
> [RTM] Write the correct tr in output _preproc files.

- docs/changes.rst
- docs/index.rst
> [RTM] added changelog

- docs/contributors.rst
- docs/installation.rst
- Fixed paths
- Removed egg creation part (not necessary anymore)
- added paragraph on Singularity
> [RTM] update docs on patching containers

- fmriprep/workflows/base.py
> [RTM, ENH] Raise exception if no BOLD scans are found

- docs/environment.yml
> Documentation (fix RTD)

- CHANGES.rst
- fmriprep/cli/run.py
- fmriprep/workflows/anatomical.py
> ENH: Permit disabling sub-mm FS reconstruction

- CHANGES.rst
- docs/conf.py
Let me know if you'd rather have a contributors file, and if you think we should credit specific PRs to listed contributors.
Also update the copyright to 2017 and to include me.
> DOC: Add contribution thanks in changelog

- fmriprep/workflows/base.py
Introduced in #448. Probably got lost in a merge conflict.
> BF: Reconnect subjects_dir to anatomical workflow

- docs/environment.yml
- requirements.txt
Incorporates poldracklab/niworkflows#150.
Docs fixed here: https://fmriprep.readthedocs.io/en/fix_docs/workflows.html
The following figures would be nice to reduce to orig/simple, but that's going to take updating the Sphinx extension:
- https://fmriprep.readthedocs.io/en/fix_docs/_images/workflows-1.png
- https://fmriprep.readthedocs.io/en/fix_docs/_images/workflows-2.png
- https://fmriprep.readthedocs.io/en/fix_docs/_images/workflows-4.png
Fixes #441.
> DOC: Update niworkflows pin

- circle.yml
This will check installation dependencies before getting to the release stage.
> TEST: Install setup deps and test run

- requirements.txt
> Update nipype and niworkflows versions

- docs/workflows.rst
- requirements.txt
Tracks nipy/nipype#1964.
Fixes #463.
> [DOC] Use updated Sphinx extension

- docs/environment.yml
This was the important bit. Sorry about the double PR.
> DOC: Update RTD nipype/niworkflows pins

- docs/workflows.rst
- fmriprep/cli/run.py
- fmriprep/utils/misc.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/confounds.py
- fmriprep/workflows/epi.py
- fmriprep/workflows/fieldmap/base.py
- fmriprep/workflows/fieldmap/fmap.py
- fmriprep/workflows/fieldmap/phdiff.py
- fmriprep/workflows/fieldmap/unwarp.py
- test/workflows/stub.py
- test/workflows/test_base.py
- test/workflows/test_confounds.py
- Removes settings dictionary in favour of explicit function arguments. Closes #418
- All defaults are set in one place - run.py. Closes #442
- Memory restrictions are now set per each run independently.
- Minor workflow name tweaking.
> [RTM] Refactor settings

- circle.yml
> [RTM] CI: Test FreeSurfer workflows with pre-reconstructed subject

- docs/environment.yml
- fmriprep/interfaces/bids.py
- fmriprep/interfaces/fmap.py
- fmriprep/interfaces/images.py
- fmriprep/interfaces/itk.py
- fmriprep/interfaces/nilearn.py
- fmriprep/interfaces/utils.py
- requirements.txt
Depends: poldracklab/niworkflows#153
> [RTM] Use niworkflows.interfaces.base.SimpleInterface

- CHANGES.rst
- docs/workflows.rst
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
> [RTM] RF: Make anatomical MNI outputs optional

- docs/environment.yml
- requirements.txt
Incorporates nipy/nipype#1966, which should resolve our self-created problems with expert options files.
@ianEisenberg If you have any datasets that are throwing the expert options error, could you try running this branch?
Closes #429 
Closes #425
> [RTM] FIX: Check for expert options file

- fmriprep/workflows/fieldmap/unwarp.py
For some reason this was missing from merging master last night.
> [RTM] fixing master merge

- fmriprep/workflows/fieldmap/fmap.py
- fmriprep/workflows/fieldmap/phdiff.py
Minor change suggested by a look at the [ds054 graph](https://384-78558509-gh.circle-artifacts.com/0/home/ubuntu/ds054/scratch/fmriprep_wf/graph.dot.svg).
> [RTM] RF: Conform cleanup wf to naming conventions

- fmriprep/workflows/fieldmap/fmap.py
- fmriprep/workflows/fieldmap/phdiff.py
- fmriprep/workflows/fieldmap/unwarp.py
As discussed in #505.
If #509 gets merged first: DOCSONLY
> [RTM] DOC: Use orig/simple graphs for fieldmaps

- fmriprep/info.py
This would allow us to evaluate other PRs until #522 will be finalized.
> [RTM] fix the version of sphinx (for now)

- fmriprep/__init__.py
- fmriprep/info.py
- fmriprep/workflows/epi.py
> [RTM] Accommodate Sphinx >=1.6 warning behavior

- requirements.txt
> [RTM] validate normalization 

- CHANGES.rst
- fmriprep/cli/run.py
- fmriprep/workflows/base.py
- fmriprep/workflows/epi.py
- wrapper/fmriprep_docker.py
An attempt to solve the issue:
https://github.com/poldracklab/fmriprep/issues/337
> [WIP?] Add mni_ref parameter that allows external reference image for resampling

- CHANGES.rst
- requirements.txt
Closes #527. See https://github.com/poldracklab/niworkflows/pull/169 for details.
> [WIP] Robuster normalization

- circle.yml
See https://github.com/singularityware/singularity/issues/679#issuecomment-302844605
> [RTM] updating docker

- .circle/tests.sh
- wrapper/fmriprep_docker.py
> FIX: Update overlapping options in wrapper

- docs/environment.yml
- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/images.py
- fmriprep/workflows/fieldmap/unwarp.py
- fmriprep/workflows/util.py
- requirements.txt
Switches to using the niworkflows `CopyHeader`. Also did some PEP8 cleanup in the files I touched. 9ba3a03 is the meat of this PR.
> [RTM] Update to niworkflows 0.0.7

- fmriprep/workflows/epi.py
This fixes compatibility with Python 2.7.
> Fix for inability of P2.7 to deal with unicode formatting

- CHANGES.rst
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/epi.py
- fmriprep/workflows/fieldmap/phdiff.py
- fmriprep/workflows/util.py
Closes #553 (via a workaround). Real issue is in Nipype (see https://github.com/nipy/nipype/issues/2072).
> [RTM] Exit code workaround

- CHANGES.rst
- fmriprep/workflows/anatomical.py
> [RTM] ENH: Output T1-space tissue probability maps, MNI-space segmentations

- CHANGES.rst
- Dockerfile
- docs/installation.rst
Uses the Neurodebian build.
Will test on a couple subjects to see if any additional changes need to be made.
Closes #516.
> [RTM] Upgrade to ANTs 2.2.0

- CHANGES.rst
- fmriprep/workflows/util.py
Reported [here](https://neurostars.org/t/fmriprep-crashed-in-epi-reg-wf-bbreg-wf-get-cost/545).
> FIX: Invalid parameter in bbreg_wf

- Dockerfile
See https://github.com/singularityware/singularity/issues/795#issuecomment-314235821
> [RTM] run ldconfig

- docs/environment.yml
- docs/workflows.rst
- fmriprep/workflows/confounds.py
- fmriprep/workflows/epi.py
- requirements.txt
- test/workflows/test_confounds.py
> ENH: Add cosine-based high-pass filter interface

- fmriprep/workflows/epi.py
This might be causing some of our problems when PE direction is unknown.
> FIX: Bad arg in pe_chooser Function interface

- circle.yml
- fmriprep/info.py
> [FIX] Download version in PyPI

- .readthedocs.yml
- fmriprep/info.py
Seems to be [working](https://readthedocs.org/projects/fmriprep/builds/5701606/).
I'm +1 to merge.
> DOC: Fix ReadTheDocs builds

- docs/installation.rst
- fmriprep/cli/run.py
> ENH: Add argument aliases with hyphens instead of underscores

- fmriprep/interfaces/reports.py
- fmriprep/viz/config.json
- fmriprep/viz/report.tpl
- fmriprep/viz/reports.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/confounds.py
- fmriprep/workflows/epi.py
First pass at adding summary reports to the anatomical and functional workflows.
Todo:
Should we be adding the version information at the top, or bottom (just before exceptions)? And anything besides the version string? (Our version string should be fairly informative, since we pin niworkflows/nipype.)
Closes #574
Closes #594
> [RTM] Add summary reports

- fmriprep/workflows/epi.py
since you are all lints free ;)
> ENH: passify flake8 and pycharm lintian checks

- fmriprep/cli/run.py
- fmriprep/interfaces/bids.py
- fmriprep/utils/__init__.py
- fmriprep/utils/misc.py
> RF: Replace make_folder with os.makedirs(exist_ok=True)

- fmriprep/workflows/anatomical.py
- fmriprep/workflows/confounds.py
- requirements.txt
... and keep up with the changes in niworkflows
> [ENH] Use float=True in ANTs registration

- .zenodo.json
- CONTRIBUTING.md
@jdkent, @craigmoodie, @feilong, @erramuzpe, @zenkavi, @ilkayisik, @yarikoptic please post your pen names, affiliations and ORCID if you would like to be included as coauthors in the Zenodo entry for FMRIPREP.
> added zenodo entry

- .zenodo.json
Hey @effigies @chrisfilo 
thanks for the detail :+1: 
I was on vacation, but I'm actively using fmriprep, great job! I hope to contribute more in the future.
> modified zenodo file

- .circle/data/ds005_outputs.txt
- docs/workflows.rst
- fmriprep/workflows/bold.py
- fmriprep/workflows/confounds.py
The assumption is that most people that turn on the AROMA flag will want to do non-aggressive denoising - this PR makes it easier for them.
> [RTM] Save non-aggressively denoised outputs for convenience.

- Dockerfile
Closes #651. Reference https://github.com/singularityware/singularity/issues/571
> [FIX] Docker&conda interaction breaks singularity

- fmriprep/info.py
There was a metadata retrieval bug in previous release
> [RTM] pybids version bump

- fmriprep/interfaces/bids.py
Addresses a [comment](https://github.com/poldracklab/fmriprep/pull/663#discussion_r133554832) in #663.
> STY: Avoid reusing variable name for separate purpose

- fmriprep/cli/run.py
AFNI skull stripping does not play nicely with eroding the brainmask in T1 space.
This may be reverted after poldracklab/niworkflows#194 is resolved.
Follow-up to #659.
> ENH: Disable AFNI skullstrip flag

- docs/api/index.rst
- docs/api/interfaces.rst
- docs/index.rst
- docs/workflows.rst
- fmriprep/interfaces/bids.py
- fmriprep/interfaces/confounds.py
- fmriprep/interfaces/freesurfer.py
- fmriprep/interfaces/images.py
- fmriprep/interfaces/surf.py
- fmriprep/interfaces/utils.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold.py
- fmriprep/workflows/confounds.py
- fmriprep/workflows/util.py
- tox.ini
> [RTM] DOC: Document workflows

- CHANGES.rst
- docs/workflows.rst
- fmriprep/cli/run.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold.py
- fmriprep/workflows/tests/test_base.py
> enh: replace medial wall values with nans

- .circle/tests.sh
- fmriprep/cli/run.py
- fmriprep/data/tests/crash_files/crash-20170905-182839-root-dvars-b78e9ea8-e295-48a1-af71-2d36afd9cebf.txt
- fmriprep/viz/report.tpl
- fmriprep/viz/reports.py
Fixes #686.
Assuming this doesn't break things, it'll be RTM when I figure out a good way to compare.
> [RTM] ENH: Parse text crash files

- docs/workflows.rst
- fmriprep/info.py
- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/itk.py
- fmriprep/workflows/bold.py
> [FIX] Collapse ITK transforms in only one file

- fmriprep/viz/config.json
> [RTM] REPORT: Fix BOLD mask inclusion

- docs/environment.yml
- docs/requirements.txt
- fmriprep/info.py
- requirements.txt
Making sure we're fixing things instead of breaking them. Tracks nipy/nipype#2196.
Closes #724.
> [RTM] PIN: Upgrade niworkflows.nipype to include networkx fix

- docs/workflows.rst
Just the note from #726. I'll leave that (and the contributing issue) open for future discussion/work.
> [RTM] DOC: Add note about T1w space [docs only]

- docs/environment.yml
- requirements.txt
Includes: nipy/nipype#2198, nipy/nipype#2200
Depends: poldracklab/niworkflows#197
> [WIP] PIN: Update niworkflows

- fmriprep/workflows/bold.py
Follow-up to poldracklab/niworkflows#198.
> [RTM] RF: Reuse volume skipping calculation from niworkflows

- .circle/data/ds005_outputs.txt
- .circle/data/ds054_outputs.txt
- fmriprep/workflows/anatomical.py
> ENH: Add inverse MNI transform to derivatives

- docs/environment.yml
- fmriprep/info.py
- requirements.txt
Now includes poldracklab/niworkflows#204.
Closes #758.
This is just verifying that poldracklab/niworkflows#203 didn't break fmriprep. I wouldn't bother actually updating the pin until poldracklab/niworkflows#204 goes in.
> [RTM] PIN: poldracklab/niworkflows master branch

- fmriprep/interfaces/freesurfer.py
- fmriprep/workflows/bold.py
- fmriprep/workflows/util.py
> [FIX] Patch to remove long filenames after mri_concatenate_lta

- fmriprep/interfaces/images.py
> [FIX] Be robust to 4D T1w images

- fmriprep/info.py
- fmriprep/workflows/bold.py
- fmriprep/workflows/fieldmap/base.py
- fmriprep/workflows/fieldmap/phdiff.py
- requirements.txt
Depends on INCF/pybids#81. Fixes #709.
> [FIX] Allow missing magnitude2 phasediff-type

- fmriprep/interfaces/images.py
Lowers the tolerance to 0.01mm. Fixes #777
> [FIX] Lower tolerance deciding t1_merge shapes

- fmriprep/interfaces/images.py
> [FIX] Copy sform over qform when qform is invalid

- fmriprep/interfaces/utils.py
Additionally, make sure that the output image is float. This PR addresses the following error:
```
Node: fmriprep_wf.single_subject_13_wf.func_preproc_task_fb_run_04_wf.bold_confounds_wf.acc_roi
Working directory: /scratch/users/oesteban/fmriprep-phase2/work/ds000212/fmriprep_wf/single_subject_13_wf/func_preproc_task_fb_run_04_wf/bold_confounds_wf/acc_roi
Node inputs:
erode_mm = <undefined>
erode_prop = 0.6
ignore_exception = False
in_mask = /scratch/users/oesteban/fmriprep-phase2/work/ds000212/fmriprep_wf/single_subject_13_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/highres001_BrainExtractionMask.nii.gz
in_tpm = /scratch/users/oesteban/fmriprep-phase2/work/ds000212/fmriprep_wf/single_subject_13_wf/anat_preproc_wf/t1_seg/highres001_BrainExtractionBrain_prob_0_tpmsum.nii.gz …
```
> [FIX] Fix AddTPMs interface to write results in proper path

- fmriprep/workflows/anatomical.py
> FIX: Pass only usable T1w images for template transforms

- fmriprep/cli/run.py
> [FIX] Freesurfer license

- fmriprep/interfaces/images.py
This PR tries to fix #873 for good.
> [FIX] Correctly handling xforms

- fmriprep/workflows/bold/base.py
> [FIX] Setting use_compression on resampling wfs

- fmriprep/cli/run.py
> [FIX] Collision between Multi-T1w and --no-freesurfer

- docs/installation.rst
And allow me to use this PR to thank you guys for making this amazing piece of software :)
> DOC: fix example in installation ants-nthreads -> omp-nthreads

- fmriprep/cli/run.py
> FIX: Set workflow return value before potential error

- CHANGES.rst
- fmriprep/interfaces/freesurfer.py
> [FIX] RuntimeWarning: divide by zero encountered in float_scalars

- CHANGES.rst
- fmriprep/interfaces/patches.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
It seems like we may be hitting memory errors masked by the convergence error (``LinAlgErr``).
Two changes are meant to solve this:
- Better memory calculation for the node
- Repeat the execution if failed, up to 10 times.
Attempts to fix #776
> [FIX] Heuristics to prevent #776

- fmriprep/interfaces/patches.py
- fmriprep/workflows/bold/confounds.py
> [FIX] Rerun tCompCor interface in case of MemoryError

- fmriprep/workflows/fieldmap/fmap.py
> [FIX] Bad connection in phasediff-fieldmap workflow

- .dockerignore
- fmriprep/cli/fmriprep_bold_mask.py
- fmriprep/interfaces/nilearn.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/util.py
- setup.py
Several improvements to make BOLD masks robuster.
> [FIX] Robuster BOLD mask

- .circleci/config.yml
- .circleci/ds005_outputs.txt
- .circleci/ds054_outputs.txt
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/bold/registration.py
- fmriprep/workflows/bold/resampling.py
- fmriprep/workflows/fieldmap/unwarp.py
An alternative version of #967, but using the MultiLabel interpolation investigated in #976 ~~rescuing Chris' commits there~~ cherry picking files from Chris' branch.
Before merging either #967 or this, we will be able to check for differences on masks and make a more informed decision.
> [FIX-2] Write latest BOLD mask out (space-T1w)

- fmriprep/interfaces/fmap.py
> Update fmap.py : import _get_pe_index in get_ees

- fmriprep/workflows/bold/registration.py
> Init flirt with qform

- fmriprep/info.py
> MAINT: Upgrade to pybids 0.5

- .gitmodules
- .travis.yml
Reverts poldracklab/fmriprep#1030
> Revert "[ENH] Add a new submodule to maintain notebooks"

- fmriprep/interfaces/reports.py
As identified in https://neurostars.org/t/fmriprep-traiterror/1538
> [WIP, BUG] Patch subject_summary in reports

- docs/citing.rst
https://neurostars.org/t/fmriprep-and-rrid/1562
> [DOC] Add RRIDs in the citation boilerplate

- fmriprep/cli/run.py
> FIX: Check exit code from subprocess

- .zenodo.json
- docs/workflows.rst
- fmriprep/cli/run.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/tests/test_base.py
> Allow changing the dimensionality of Melodic for AROMA.

- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/resampling.py
- fmriprep/workflows/fieldmap/base.py
- fmriprep/workflows/fieldmap/syn.py
ref: https://github.com/poldracklab/fmriprep/pull/1064#discussion_r184896878
> [DOC] Stylistic fix (\`'template'\`)

- fmriprep/interfaces/confounds.py
> FIX: Ensure one motion IC index is loaded as list

- fmriprep/workflows/bold/base.py
> [FIX] Circular dependency

- .zenodo.json
- fmriprep/workflows/bold/resampling.py
> Fix bad connection for --medial-surface-nan option

- docs/citing.rst
- docs/workflows.rst
Addresses https://github.com/poldracklab/fmriprep/issues/1110
> [DOC] Add lesion masking during registration

- fmriprep/utils/bids.py
@mgxd Can you confirm whether this works for you?
Fixes #1140.
> FIX: Refine BIDS queries

- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/images.py
- fmriprep/workflows/anatomical.py
Upstreamed in nipy/nipype#2572.
> RF: Use nipype.interfaces.image.Reorient

- fmriprep/utils/bids.py
> exclude sourcedata

- fmriprep/cli/run.py
> better --output-space desccription

- fmriprep/info.py
Attempts to address #1174. At the very least we'll have access to the latest changes and see if we need to change our invocation at all.
> PIN: pybids 0.6.3

- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/images.py
- fmriprep/workflows/fieldmap/syn.py
> RF: Replace InvertT1w with upstream Rescale(invert=True)

- README.rst
- docs/usage.rst
- docs/workflows.rst
- fmriprep/interfaces/freesurfer.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/fieldmap/fmap.py
> [DOC] Additions to include before responding to reviews of the pre-print

- .circleci/config.yml
- Dockerfile
This PR makes some improvements to minor details of the Dockerfile. The most relevant is changing the working directory.
No documentation changes are needed.
1. We invite you to list yourself as a *fMRIPrep* contributor, so if your name 
is not already mentioned, please modify the 
[``.zenodo.json``](https://github.com/poldracklab/fmriprep/blob/master/.zenodo.json)
file with your data right above Russ' entry. Example:
```
{
"name": "Contributor, New FMRIPrep",
"affiliation": "Department of fMRI prep'ing, Open Science Made-Up University",
"orcid": "<your id>"
},
{
"name": "Poldrack, Russell A.",
"affiliation": "Department of Psychology, Stanford University",
"orcid": "0000-0001-6755-0259"
},
```
2. By submitting this request you acknowledge that your contributions are available under the …
> [ENH] Change WORKDIR of Docker image

- fmriprep/interfaces/fmap.py
> ENH: More specific errors for missing echo times

- .circleci/config.yml
- Dockerfile
- fmriprep/workflows/bold/tests/test_util.py
- fmriprep/workflows/bold/tests/test_utils.py
- scripts/generate_reference_mask.py
Just to track progress on this, I think this is the rough framework we need for testing.
I picked this symmetric overlap metric (taken from [doi:10.1371/journal.pone.0007200](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0007200#article1.body1.sec4.sec3.p3)) because it's sensitive to increases and decreases in mask size, as well as shifts.
Next I'll need a list of images to make reference files from.
> TEST: Add enhance-and-skullstrip regression tests

- .circleci/config.yml
- fmriprep/data/boilerplate.bib
Closes #1229
Update fMRIPrep version in the Zenodo bibtex entry.
Output reports should have the reference updated.
1. We invite you to list yourself as a *fMRIPrep* contributor, so if your name 
is not already mentioned, please modify the 
[``.zenodo.json``](https://github.com/poldracklab/fmriprep/blob/master/.zenodo.json)
file with your data right above Russ' entry. Example:
```
{
"name": "Contributor, New FMRIPrep",
"affiliation": "Department of fMRI prep'ing, Open Science Made-Up University",
"orcid": "<your id>"
},
{
"name": "Poldrack, Russell A.",
"affiliation": "Department of Psychology, Stanford University",
"orcid": "0000-0001-6755-0259"
},
```
2. By submitting this request you acknowledge that your contributions are available under the BSD 3-Clause license.
3. Use a descriptive …
> [DOC] Set appropriate version in Zenodo citation

- .zenodo.json
- fmriprep/data/boilerplate.bib
- fmriprep/workflows/bold/t2s.py
- Closes #1227.
- Adds a description to the ME T2* workflow `init_bold_t2s_wf`.
- Adds a citation for Posse et al. (1999), which introduced the method used in the workflow to optimally combine data across echoes. I could not find citations for the monoexponential signal model, the log-linear fit used, or the use of an adaptive mask for the model.
- Adds my information to the zenodo.json file.
- The workflow description for `init_bold_t2s_wf`.
> [DOC] Add ME workflow description

- fmriprep/workflows/bold/confounds.py
fixes #1254 
I added `mem_gb=mem_gb` to the `ROIplot` interface in `confounds.py`.
May help with a [memory error](https://neurostars.org/t/fmriprep-stopped-due-to-memory-error/2275) experienced by a user
> [FIX] Add memory annotation to ROIPlot interface

- docs/workflows.rst
> Clarify language describing T1w image merging

- Dockerfile
See https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg59406.html
> FIX: Revert FreeSurfer download URL

- requirements.txt
> MAINT: Pin pybids and grabbit in Docker build

- .zenodo.json
- fmriprep/interfaces/freesurfer.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/bold/registration.py
- fmriprep/workflows/bold/resampling.py
Sanitize long paths in LTA files
> FIX: Remove long paths from all LTA output files

- .circleci/ds210_outputs.txt
- docs/contributors.rst
- docs/workflows.rst
- fmriprep/__about__.py
- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/multiecho.py
- fmriprep/utils/misc.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/registration.py
- fmriprep/workflows/bold/t2s.py
- requirements.txt
- Removes in-package implementation of T2* map, wraps tedana in a nipype style interface
- IMPORTANT ! Integrates optimal combination into fmriprep workflow as a default. Previously, users would supply multi-echo files and receive all processed, individual echos back. Now, users will receive a single, optimally combined time series when using multi-echo files. This is in response to queries like [this one on NeuroStars](https://neurostars.org/t/fmriprep-combining-multi-echo-data-error-with-unwarping/2310/3), and several offline requests. Crucially, however, this effectively removes the ability for users to run fmriprep and _then_ tedana, as tedana denoising will now need to be _integrated_ into fmriprep entirely, probably by subbing out the AROMA connection. I would, though, like to have …
> [ENH] Update ME-EPI workflow to create optimal combination

- docs/usage.rst
Updating the currently dead link in the usage section of the docs to the bids-validator app as raised in #1312 
none
> [DOC] [FIX] update BIDS-validator link

- fmriprep/viz/config.json
- fmriprep/workflows/bold/registration.py
> [HOTFIX] Reportlets - bbregister vs flirtbbr (continues #1326)

- .circleci/config.yml
- fmriprep/workflows/bold/tests/test_util.py
Refs. #1000, #1050, #1321.
Also includes a new filter of branches so builds other than tests
are skipped if the name of the branch starts with ``tests?/``.
> [TST] Add heavily-nonuniform boldrefs for regression tests

- fmriprep/__about__.py
- fmriprep/interfaces/cifti.py
- requirements.txt
This should fix the test failed in #1283
> [FIX] Quick update to new template structure

- .gitignore
Ignore project setting files from
- spyder
- pycharm
- vscode
If we ignore the settings files from these somewhat popular python/code editors, then contributors will not have to manually ignore them (I use vscode). 
Any more popular choices to add to the list?
> [ENH]: ignore project settings files from popular python/code editors

- .circleci/config.yml
- fmriprep/cli/run.py
It's time to kill `--debug`. This makes it do nothing, and replaces it with `--sloppy`, with a better docstring.
Do we want to adjust anything else? A single flag to run `stop_on_first_crash` and set `--nthreads` to 1? I think what would be really nice is something like `--create-issue` to construct a pre-filled-in issue with run parameters and tracebacks, but that's almost certainly a job for another day.
> ENH: Deprecate --debug with --sloppy

- docs/links.rst
- docs/outputs.rst
> DOC: Update outputs.rst to match Derivatives RC1 changes

- docs/workflows.rst
- fmriprep/cli/run.py
- fmriprep/utils/bids.py
- fmriprep/workflows/base.py
- fmriprep/workflows/tests/test_base.py
Addition to #1263. Following up on discussions in #1324, adds an `echo-idx` flag to the fmriprep cli so that users can elect to preprocess only one echo in a mutliecho BOLD series.  
Currently failing due to merge conflicts in #1263.
Usage documentation is automatically built from the CLI, so I don't think any additional documentation needs to be added ? Please let me know f there's elsewhere you'd like me to update !
> [ENH] Add echo-idx flag

- .zenodo.json
- fmriprep/workflows/anatomical.py
> [FIX] Select consistent parcellation for producing aparcaseg derivatives

- fmriprep/workflows/bold/tests/test_confounds.py
Addresses [the promise](https://github.com/poldracklab/fmriprep/pull/1335#issuecomment-433400467) to add tests for the functions `_add_volumes` and `_remove_volumes`
N/A
> [TEST] Utility functions for skipping/re-inserting non-steady-state volumes

- fmriprep/interfaces/bids.py
- fmriprep/interfaces/freesurfer.py
- fmriprep/workflows/anatomical.py
> [FIX] Always run FreeSurfer interfaces that sink outside working directory

- Dockerfile
- fmriprep/__about__.py
- requirements.txt
Also updates nipype to allow ForkServer context in `MultiProc`.
Closes #1390.
> ENH: Use Python 3.7 in Dockerfile

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.rst
Closes #1403, #1264 
Improvements to the CONTRIBUTING guide, based on recent questions that have arisen in project development. You can see a [rendered version of this guide](https://github.com/emdupre/fmriprep/blob/doc/update-contrib/CONTRIBUTING.md) here.
All feedback welcomed !
> [DOC] Update contributing guide and add code of conduct

- fmriprep/interfaces/images.py
- fmriprep/workflows/anatomical.py
@gilles86 This is a first pass at fixing the template transform calculation. I think it probably needs to be inverted, but the structure should be there. I'll give this a shot on the data you sent me on Monday, but if you have some time to try it out before then, you might be able to see if I'm moving us in the right direction.
Fixes #1371.
> FIX: Calculate template transforms explicitly as RAS2RAS

- fmriprep/interfaces/images.py
> [MAINT] Replace ``img.get_affine()`` -> ``img.affine``

- fmriprep/viz/reports.py
- fmriprep/workflows/bold/hmc.py
Closes #1400. Example event with very long content: https://sentry.io/poldracklab/fmriprep/issues/770864045/events/37075518627/
> [FIX] Truncating of sentry messages

- fmriprep/viz/reports.py
Closes #1407. This should reduce the amount of noise on sentry.
> [ENH] Group common issues with fingerprints

- fmriprep/cli/run.py
> [ENH] adding memory and cpu info to sentry logs

- Dockerfile
- docs/installation.rst
- fmriprep/cli/run.py
Closes #1408. Ignores issues not relevant to FMRIPREP and data from participants not listed in `--participant_label` to limit the amount of noise.
> [ENH] Make sure inputs are BIDS compliant before running fmriprep

- docs/environment.yml
- fmriprep/__about__.py
- requirements.txt
We should get back to a nipype release. [67d6212a9cabd395ee74f7818d09d8ea6c8426a4](https://github.com/nipy/nipype/commit/67d6212a9cabd395ee74f7818d09d8ea6c8426a4) and [ac4076480ef55eb2a79aff9eff7cbf48394c565b](https://github.com/nipy/nipype/commit/ac4076480ef55eb2a79aff9eff7cbf48394c565b) are included in 1.1.6.
> MAINT: Require nipype >= 1.1.6

- fmriprep/cli/run.py
Per, #1428, adds `overcommit_memory` and `overcommit_limit' tags to Sentry. `overcommit_memory` translates the 0/1/2 codes into `heuristic`/`always`/`never`. `overcommit_limit` is only meaningful under the `never` condition, and it may be either defined as a strict number of kilobytes or a percentage of total memory (kbytes taking precedence).
> ENH: Report memory overcommit policies

- fmriprep/viz/reports.py
Closes #1434.
I suggest making a quickfix release after merging this one.
> [FIX] fix breadcrumb reporting

- fmriprep/viz/reports.py
> ENH: Only report participants with errors

- fmriprep/viz/reports.py
Closes #1440 (this time for real).
> FIX: Use keyword arguments for Sentry breadcrumb reporting

- docs/citing.rst
- docs/environment.yml
- fmriprep/__about__.py
- fmriprep/data/boilerplate.bib
- fmriprep/utils/bids.py
- requirements.txt
Some strip-offs from #1438 to test separatelly
> [MAINT/DOC] Clean-up ``__about__``, update with Nat Meth

- docs/conf.py
> [FIX] Docs failing to build

- Dockerfile
This PR supersedes #1450, which only tested the documentation build.
Therefore, closes #1450.
> [MAINT] Make sure Python 3.7.1 is installed

- .readthedocs.yml
- docs/environment.yml
- fmriprep/__about__.py
- fmriprep/data/flirtsch/bbr.sch
- fmriprep/workflows/bold/registration.py
- fmriprep/workflows/bold/util.py
- requirements.txt
- setup.py
It looks like niworkflows is breaking the RTD build, so I've done some cleanups over in poldracklab/niworkflows#272.
Target fixes:
Fixes #1436.
Fixes #1388.
> FIX: ReadTheDocs builds

- fmriprep/__about__.py
> MAINT: Dev status to beta, bump copyright year

- .circleci/config.yml
- .circleci/ds005_outputs.txt
- .circleci/ds005_partial_outputs.txt
- fmriprep/cli/run.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/resampling.py
The cifti workflow was picking up target names from the wrong source node because fsnative was being replaced by the subject's id.
Fixes #1439
> [FIX] Bad ``fsnative`` replacement in CIfTI workflow

- wrapper/fmriprep_docker.py
This patch updates `PKG_PATH` to mount working dependencies (`niworkflows`, `nipype`, `fmriprep`) as 3.7 source directories.
No changes to documentation.
> [MAINT] resolves #1485 : patch fmriprep-docker automount for use with Python 3.7

- Dockerfile
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/resampling.py
- fmriprep/workflows/bold/util.py
Update some outstanding elements still depending on the old niworkflows.data interface.
> [ENH] Remaining TemplateFlow integrations

- Dockerfile
Fixes memory issues reported in https://neurostars.org/t/fmriprep-error-codes/3340/5
> [FIX] Updating bids-validator to 1.1.3

- .circleci/config.yml
- Dockerfile
This may be the root cause of the TemplateFlow errors, in which `git-annex` attempts to unlock the repository in order to perform a read-only task.
Closes #1500.
* Set `annex.merge-annex-branches` to `false` for all repositories (see [git-annex/ bugs/ impossible to perform "read-only" git annex info without write permissions](https://git-annex.branchable.com/bugs/impossible_to_perform___34__read-only__34___git_annex_info_without_write_permissions/))
* Set branches beginning with `docker/` to push to Docker Hub with a tag matching the portion following `docker/`. So I guess we shouldn't allow `docker/master` or `docker/unstable` or `docker/1.0.0`...
> FIX: Disable merging annex branches at run time

- fmriprep/__init__.py
> UX: Reduce warning levels

- .circleci/config.yml
- CHANGES.rst
- Dockerfile
- fmriprep/__about__.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/resampling.py
- fmriprep/workflows/bold/util.py
- requirements.txt
> REL: 1.3.1

- fmriprep/cli/run.py
- fmriprep/workflows/bold/base.py
Fixes poldracklab/niworkflows#309
> FIX: Make sure ``--cifti-output`` requires at least one of ``fsaverage{5,6}``

- fmriprep/cli/run.py
Closes #1116.
Tested - example event: https://sentry.io/organizations/poldracklab/issues/540334560/events/b315799f619a43eb8e143f254afaca6f/
> [ENH] include dataset_description.json in sentry metadata

- docs/contributors.rst
fixes #1561 
This changes the path references from python3.6 to python3.7
- Please review `contributors.rst`
> [DOCS] bump references of python3.6 to python3.7

- docs/workflows.rst
Documents the work-around described in https://github.com/poldracklab/fmriprep/issues/1572
> DOC: Add .bidsignore requirement to docs on lesion masks

- .circleci/config.yml
- versioneer.py
> FIX: Re-enable correct versioning within container

- .zenodo.json
- docs/_static/theme_overrides.css
Customization on docs styles to separate the parameter name and type:
From:
To:
All functions for workflows might be affected.
> [DOC] Improve appearance of parameter types in API docs

- .circleci/config.yml
- Dockerfile
- docs/workflows.rst
- fmriprep/cli/run.py
- fmriprep/workflows/base.py
- setup.cfg
-- following up poldracklab/smriprep#89
> ENH: Allow template modifiers (a la ``--output-spaces``) in skull-stripping

- fmriprep/workflows/bold/resampling.py
- setup.cfg
> FIX: Finalizing support for new templates and their command line modifiers

- .zenodo.json
Forgot to add myself a while back for the PR I did here.
> DOC: Add WHT to Zenodo

- pyproject.toml
- setup.cfg
- setup.py
> MAINT: Use PyBIDS 0.9.x via niworkflows/smriprep PRs

- docs/citing.rst
- fmriprep/workflows/bold/registration.py
*  FIX: Correct BOLD-T1w registration description if DoF != 9
* DOC: Update boilerplate generator in citing.rst
Closes #1543.
[citing.html](https://9221-53175327-gh.circle-artifacts.com/0/tmp/src/fmriprep/docs/_build/html/citing.html) - Will appear when [9221](https://circleci.com/gh/poldracklab/fmriprep/9221#artifacts/containers/0) completes.
> FIX: Correct BOLD-T1w registration description if DoF != 9

- fmriprep/cli/run.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- setup.cfg
> MAINT: Remove old ``extensions`` entity selector for pybids queries

- fmriprep/workflows/bold/outputs.py
Add `"TaskName"` metadata to BOLD outputs.
Closes #1713.
> ENH: Add TaskName metadata to BOLD outputs

- fmriprep/cli/run.py
> DOC: Add link to documentation in help of ``--output-spaces`` argument

- .zenodo.json
Added utooley to `.zenodo.json` for PR #365 to `niworkflows`. Please feel free to reorder if necessary.
`.zenodo.json`
> [DOC] Update .zenodo.json

- setup.cfg
> PIN: niworkflows and nipype to use latest N4BiasFieldCorrection

- Dockerfile
> MAINT: Container images - cleanup ``$HOME`` in docker build

- docs/contributors.rst
Recent changes to the argument parser have made a meaningful version string no longer optional in custom built Docker containers. This updates the text to explain how to get the current version from the repository metadata and pass it to Docker.
Thanks to @emdupre and @shotgunosine for noticing this.
Related: #1796.
contributors.html
> DOC: Add VERSION argument to docker build instructions

- setup.cfg
Pinning nipype with nipy/nipype#3061 merged.
Trying to identify whether all of our test failures are related to this.
> FIX: Bad results files loads; PIN: nipy/nipype master

- fmriprep/cli/run.py
- wrapper/fmriprep_docker.py
> FIX: Raise error if work_dir is a child of bids_dir

- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/hmc.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/registration.py
- fmriprep/workflows/bold/resampling.py
- fmriprep/workflows/bold/stc.py
- fmriprep/workflows/bold/t2s.py
- fmriprep/workflows/fieldmap/__init__.py
- fmriprep/workflows/fieldmap/base.py
- fmriprep/workflows/fieldmap/fmap.py
- fmriprep/workflows/fieldmap/pepolar.py
Also address https://github.com/poldracklab/fmriprep/pull/1879#discussion_r350899463
> DOC: Revise docstrings of workflows for correct parsing with napoleon

- setup.cfg
Replaces #1896, following up on https://github.com/poldracklab/fmriprep/pull/1886#discussion_r352868543.
`include_package_data` tells `setup.py sdist` to *only* use `MANIFEST.in` to find data, as opposed to using the `package_data` structure defined in `setup.cfg`. This PR drops that line, and now both wheels and sdists include package data with a uniform approach.
Also removes the unnecessary `fmriprep/data/__init__.py`.
To verify:
```
$ python setup.py sdist | grep data
creating fmriprep-1.5.3rc2+0.g0f864c1c.dirty/fmriprep/data
creating fmriprep-1.5.3rc2+0.g0f864c1c.dirty/fmriprep/data/flirtsch
copying fmriprep/data/affine.json -> fmriprep-1.5.3rc2+0.g0f864c1c.dirty/fmriprep/data
copying fmriprep/data/bids.json -> fmriprep-1.5.3rc2+0.g0f864c1c.dirty/fmriprep/data
copying …
```
> MNT: Ensure data is packaged in sdist

- README.rst
Link to EPINorm issue was incorrect.
> FIX: Link to EPINorm issue in README

- .circleci/config.yml
- docs/outputs.rst
- docs/workflows.rst
- fmriprep/cli/run.py
- fmriprep/workflows/base.py
- wrapper/fmriprep_docker.py
Follow-up to poldracklab/smriprep#27.
Doc updates pending.
Closes #1900.
Closes #1573.
> ENH: Add --fs-subjects-dir flag 

- setup.cfg
fixes #1904 
this pull request only updates pin to niworkflows where poldracklab/niworkflows#438 was merged
N/A
> [FIX] Respect ``--dummy-scans 0``

- setup.cfg
> MAINT: Update nibabel to 3.0.0rc1

- fmriprep/data/reports-spec.yml
- setup.cfg
ref #1923
N/A
Should this be merged into the maint/1.5.x branch or the master branch, i'm afraid I have not been following the branching strategies closely.
[also, I should probably not build fmriprep on my account](https://circleci.com/gh/jdkent/fmriprep/tree/pin_niworkflows)
> FIX: Include all functional runs in reports, establish consistent ordering

- fmriprep/workflows/bold/base.py
> FIX: Use SyN-SDC if --use-syn-sdc and --ignore fieldmaps are used

- Makefile
> ENH: Facilitate docker build with make command

- fmriprep/workflows/bold/base.py
- setup.cfg
Depends on https://github.com/poldracklab/sdcflows/pull/82.
Using a `docker/` branch to get a testable Docker image out pre-release.
> FIX: SyN SDC logic failing in `--force-syn` cases

- Dockerfile
This PR updates the bids validator version in the DockerFile and thereby closes #1929.
I verified that the Docker builds successfully using this new version.
The only change that was made was to Dockerfile line 108.
> ENH: Upgrade BIDS validator in Dockerfile to 1.4.0

- .maint/contributors.json
added myself as contributor (for contributing to #1929 #1842 #1952)
> MNT: Add Iris Groen to contributors.json

- fmriprep/cli/run.py
- setup.cfg
Closes #1783 
- Adds flag `--clean-workdir` to facilitate clearing content from existing working directory.
> ENH: Add --clean-workdir argument

- fmriprep/cli/run.py
- setup.cfg
> ENH: Warn when existing output version does not match current pipeline version

- docs/faq.rst
- docs/spaces.rst
And close poldracklab/smriprep#87 and close #1640 because they
will not be implemented anytime soon.
> DOC: Better describe utilization of custom templates

- fmriprep/workflows/base.py
> FIX: Ensure subject ID is passed when grabbing BIDS data

- fmriprep/cli/run.py
- setup.cfg
- wrapper/fmriprep_docker.py
> FIX: Revert MNI152NLin2009cAsym as default BOLD output

- .circleci/config.yml
- Dockerfile
Inspired by nipreps/dmriprep#46, this replaces Docker save/load operations with a local registry, reducing build runtime.
Closes #1885
> MAINT: Use local docker registry

- docs/outputs.rst
- docs/spaces.rst
- fmriprep/workflows/bold/outputs.py
> DOC: Clean up surface outputs

- .mailmap
- .zenodo.json
- CHANGES.rst
- setup.cfg
Some contributors are not yet listed in the `.maint/contributors.json` file:
- Soichi Hayashi (@soichih)
- Basille Pinsard (@bpinsard)
- Marc Bue. (@marcbue)
Thanks very much for your contributions, please add your names (or let me know you want me to do so) to the `.main/contributors.json` file. If you don't want to be annoyed anymore, please let me know or add your names to the `.maint/former.json` file.
Thanks very much
> REL: 20.0.0

- Dockerfile
> ENH: Include low res CIFTI templates in Docker image

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/questions.md
Adds issue templates similar to https://github.com/nipype/pydra/issues/new/choose
> ENH: Add issue templates

- fmriprep/cli/run.py
> FIX: fMRIPrep crashes whenever ``FREESURFER_HOME`` is not set

- docs/faq.rst
> DOC: Add one FAQ about reusing the work directory

- fmriprep/workflows/base.py
- setup.cfg
- fixes for troublesome dependencies
- smriprep's latest API changes
> REL: 20.1.0rc2

- docs/faq.rst
This PR adds a FAQ regarding reusing the working directory. This has come up a number of times here and on Neurostars and is deserving of an entry in the FAQ.
Closes #1756.
The FAQ page should be checked for formatting before merge.
> FAQ: Can fMRIPrep resume execution after encountering an error?

- docs/faq.rst
Reverts poldracklab/fmriprep#2044
> Revert "FAQ: Can fMRIPrep resume execution after encountering an error?"

- fmriprep/cli/parser.py
> FIX: logging error when cleaning working directory

- fmriprep/_warnings.py
- fmriprep/config.py
- fmriprep/interfaces/confounds.py
- fmriprep/interfaces/reports.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/hmc.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/registration.py
- fmriprep/workflows/bold/resampling.py
- fmriprep/workflows/bold/stc.py
- fmriprep/workflows/bold/t2s.py
follows the effort of https://github.com/poldracklab/mriqc/pull/838 in hopes of reducing warnings out of the user's control.
- Avoid niworkflow imports at top level
- Port over warnings filter from mriqc
> MAINT: reduce number of warnings

- fmriprep/workflows/base.py
- fmriprep/workflows/bold/registration.py
- setup.cfg
Resolves a couple of problems (see fixed issue) in a Function node.
Resolves: #2083
Requires: poldracklab/smriprep#177
> FIX: Robustly extract WM from brain-tissue segmentations

- fmriprep/workflows/base.py
- setup.cfg
relies on https://github.com/nipreps/niworkflows/pull/498 and https://github.com/poldracklab/smriprep/pull/174
> FIX: Update anatomical connections with *sMRIPrep*

- fmriprep/cli/parser.py
- setup.cfg
> ENH: use FS canary to detect license issues

- docs/faq.rst
This is a PR to follow up from this issue: https://github.com/poldracklab/fmriprep/issues/2082
> update parallel subject neurostars link in faq

- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/registration.py
> FIX: Dismiss ``echo`` entity on several derivatives and figures outputs

- CHANGES.rst
- docs/usage.rst
- fmriprep/cli/workflow.py
- fmriprep/workflows/base.py
Final preparation for the 20.1.0 release.
> DOC: Improve documentation and logging about fast-track

- .circleci/config.yml
> MAINT: Use legacy pip/setuptools for py2 checking

- fmriprep/workflows/bold/base.py
> FIX: exclude "echo" entity from sdc reports

- .github/release-drafter.yml
With the several maint/ branches the bot messes up.
> MAINT: Delete release-drafter

- fmriprep/utils/misc.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/tests/test_confounds.py
- setup.cfg
- Ignore W503 (boolean operator after line break)
- Add settings section for pytest
> MAINT: Update ``setup.cfg`` (flake8 and pytest)

- docs/workflows.rst
Closes #2214.
- Updates older reference `grow_mask` to new niworkflows interface `RefineBrainMask`.
The `Refinement of Brain Mask` section in workflows.rst.
> [doc] update reference in "Refinement of Brain Mask" description

- setup.cfg
Ensure we are using the latest and greatest of our closest dependencies
> PIN: Latest nipreps

- .circleci/config.yml
> CI: Drop CircleCI docs build

- .circleci/ds005_fasttrack_outputs.txt
- .circleci/ds005_outputs.txt
- .circleci/ds005_partial_fasttrack_outputs.txt
- .circleci/ds005_partial_outputs.txt
- .circleci/ds054_fasttrack_outputs.txt
- .circleci/ds054_outputs.txt
- .circleci/ds210_fasttrack_outputs.txt
- .circleci/ds210_outputs.txt
- docs/links.rst
- docs/outputs.rst
- fmriprep/cli/run.py
- fmriprep/utils/bids.py
- fmriprep/workflows/bold/outputs.py
* Check through derivatives for things not addressed by the standard, add to `.bidsignore`
* Update function that generates `dataset_description.json`
* ...
Should check the "Outputs of fMRIPrep" section if any changes need to be made.
> ENH: Conform to BIDS Derivatives as of BIDS 1.4.0

- .maint/contributors.json
- .maint/developers.json
- .maint/paper_author_list.py
- .zenodo.json
- CHANGES.rst
- setup.cfg
This is happening...
@bpinsard, @pbellec please make sure you feel comfortable with the mention I've done in the CHANGES file, and the commitments I wrote there.
@tsalo I have also moved you as a developer 👍  I hope this is fine by you.
cc/ @shotgunosine
> REL: 20.2.0rc0

- .circleci/config.yml
> MAINT: Move away from nearly deprecated images

- .maint/contributors.json
Add my name to the contributors list for nipreps/niworkflows#572 and nipreps/niworkflows#573
> MAINT Add myself to contributors.json

- .circleci/config.yml
Partially? closes #2311 
https://circleci.com/docs/2.0/private-images/
> ENH: Add Docker authentication to increase pull rate limit

- CHANGES.rst
> REL: 20.2.1

- .circleci/config.yml
- Dockerfile
- scripts/fetch_templates.py
- Clean up extraneous bits
- Create dedicated script for template caching
> RF: Dockerfile

- fmriprep/workflows/bold/base.py
We updated our message but not our actions.
Fixes #2369.
> FIX: Ignore SBREF files if --ignore sbref is passed

- fmriprep/config.py
- fmriprep/tests/test_config.py
Continuation of #2086
This PR explicitly sets the numpy random seed.
> ENH: Set and track NumPy's random seed

- fmriprep/cli/parser.py
Fixes https://github.com/nipreps/fmriprep/issues/2376
> DOC: adds --mem metavar

- .maint/contributors.json
- docs/workflows.rst
Backport of gh-2345 by @jsmentch.
> DOC: skull stripping is forced by default

- fmriprep/cli/run.py
> FIX: Fall-back to initializing workflow in main process

- .circleci/config.yml
> MAINT: Keep pip and setuptools with support for Python 3.5

- .circleci/config.yml
Should we be worried that now docker writes the secret under `/home/circleci/.docker/` in plain text?
> MAINT: Docker hub has disabled password authentication

- setup.cfg
> MAINT: Pin svgutils==0.3.1 for the 20.1.x series

- .circleci/config.yml
- Addresses issues when authenticating docker hub
- Updates CircleCI's machine image, and related changes.
Resolves: #2455.
> MAINT: Back port CircleCI configuration from dev branch

- .circleci/config.yml
I don't think we're ever hitting the `else` block, but fallback to focal base now that the Dockerfile has been updated.
> MAINT: Remove traces of Xenial base

- setup.cfg
Addresses: https://github.com/nipreps/fmriprep/pull/2458#issuecomment-882602377
> FIX: Address dependency incompatibilities by pinning specific packages

- docs/outputs.rst
> DOC: Better explanation on how spike regressors are generated

- Dockerfile
Follow-up to #2409, to test whether the HED refactor solved our issues.
> MNT: Update BIDS validator to 1.8.0

- scripts/fetch_templates.py
These templates are usually required during anatomical processing.
https://github.com/nipreps/niworkflows/blob/32a33d61ab64e262a4ebcf8afcf232d70c2f92b3/niworkflows/anat/ants.py#L391-L403
> MAINT: Add missing OASIS30 WM/BS probsegs

- fmriprep/cli/workflow.py
- fmriprep/utils/misc.py
> FIX: Catch FreeSurfer error related to FIPS being enabled

- fmriprep/cli/workflow.py
- fmriprep/utils/misc.py
#2486 should have targeted the `maint/20.2.x` branch
> [BACKPORT] FIX: Catch FreeSurfer error related to FIPS being enabled

- .circleci/ds054_fasttrack_outputs.txt
- .circleci/ds054_outputs.txt
- fmriprep/config.py
- fmriprep/data/boilerplate.bib
- fmriprep/data/reports-spec.yml
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/resampling.py
- setup.cfg
This PR decouples SDC workflows into a more modular structure, ala anatomical workflows via `smriprep`. A first pass of this integration was done in [`nibabies`](https://github.com/nipreps/nibabies/pull/43/files).
- ~~TODO: Update documentation accordingly.~~
> MAINT: Leverage SDCFlows 2.x API

- fmriprep/workflows/bold/stc.py
> FIX: Import numpy in workflows.stc

- fmriprep/workflows/bold/base.py
> STY: Run black on ``workflows.bold.base`` to clarify diff in #2547

- fmriprep/cli/parser.py
- fmriprep/config.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/stc.py
Backports #2520 and #2540 to the LTS series
cc @bpinsard for approval
> BP: Slice-timing correction improvements

- .maint/contributors.json
- .maint/update_zenodo.py
- .zenodo.json
- CHANGES.rst
- docs/spaces.rst
- setup.cfg
Release prep for 20.2.4.
Closes #2292.
Closes #2507.
> REL: 20.2.4

- Dockerfile
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/outputs.py
* Fix regression in #2547 that used the T2* map as the boldref
* Note in BOLD series metadata that optimal combinations are inherently skull-stripped
> FIX: Minor multiecho issues

- Dockerfile
- fmriprep/tests/test_fsl6.py
Local test passed, so let's see how this goes.
> MAINT: Upgrade Docker to FSL 6

- setup.cfg
> MNT: Restore nitime to requirements, necessary for DVARS

- wrapper/fmriprep_docker.py
> WRAPPER: Map ``--bids-filter-file``s into Docker container

- fmriprep/interfaces/reports.py
- fmriprep/interfaces/tests/test_reports.py
- fmriprep/workflows/bold/base.py
Backport of gh-2302 to 20.2.x series.
For some reason I'd thought we'd already fixed this in LTS.
> FIX: Clarify phase encoding direction, rather than axis

- fmriprep/workflows/base.py
Moves `fmap_select_std` out of a loop, as it can be duplicated unnecessarily and cause a name collision if multiple ANAT estimators are found.
Fixes #2687.
> FIX: Create single fmap_select_std node for use with all ANAT estimators

- fmriprep/cli/parser.py
- fmriprep/config.py
- fmriprep/workflows/base.py
Alternative to nipreps/sdcflows#259.
> ENH: Add --topup-max-vols flag to control TOPUP runtime

- .zenodo.json
- CHANGES.rst
- docs/outputs.rst
Preparation for the 20.2.7 bug-fix release.
Contributors found in git history not listed in Zenodo:
* @josephmje
* @marcbue 
If you would like to be listed as contributors, please provide your preferred name, affiliation and ORCID.
> REL: 20.2.7

- .mailmap
- .zenodo.json
- CHANGES.rst
- setup.cfg
Preparation for the 21.0.1 bug-fix release.
Contributors found in git history not listed in Zenodo:
* @josephmje and @marcbue (Also pinged on #2697; only need to respond to one.)
If you would like to be listed as contributors, please provide your preferred name, affiliation and ORCID.
Edit: Updated mailmap and found two contributors already listed.
> REL: 21.0.1

- fmriprep/data/reports-spec.yml
Two typos corrected in fMRIprep report.
N/A
> fix two minor typos in report spec

- .circleci/config.yml
> MAINT: Upload artifacts after each step of Circle's workflow

- .circleci/config.yml
- fmriprep/cli/workflow.py
- fmriprep/data/boilerplate.bib
> FIX: Update *fMRIPrep* version in bibliography at run time

- fmriprep/workflows/base.py
See https://github.com/nipreps/nibabies/pull/208
> FIX: Preserve `collect_data` behavior by using named args

- fmriprep/data/reports-spec.yml
- fmriprep/workflows/bold/t2s.py
> ENH: Clip T2* values at 100ms to keep consistent histogram axes

- wrapper/fmriprep_docker.py
Forgotten update after upgrading in #2782
> FIX: Update wrapper python path

- docker/files/freesurfer7.2-exclude.txt
Fixes https://github.com/nipreps/smriprep/issues/286 in fMRIPrep.
> FIX: Re-add fsr-checkxopts to Docker image

- setup.cfg
Okay, think we're really just about there. One last RC and then we'll pull the trigger on Monday.
These upgrades resolve DVARS errors in extremely low-variance voxels and GIFTI metadata errors with oblique surfaces.
> REL: 22.0.0rc4

- .circleci/config.yml
https://github.com/CircleCI-Public/docker-orb/issues/154
> CI: Upgrade docker orb

- .circleci/ds210_fasttrack_outputs.txt
- .circleci/ds210_outputs.txt
- docs/outputs.rst
- fmriprep/workflows/bold/outputs.py
If echos are output in BOLD space, it's useful to have a relevant mask. I'm not sure how useful the boldref is, but it shouldn't be very large.
Closes #2844.
- Updated expected outputs (most cribbed from `maint/22.0.x`)
> FIX: Output brain mask and boldref in BOLD space if individual echos requested

- fmriprep/cli/run.py
- fmriprep/config.py
- fmriprep/utils/debug.py
Makes setting traces and debugging errors easier.
> MAINT: Add a ``--debug pdb`` to allow easier line-by-line debugging

- fmriprep/cli/run.py
Only breaks when running with ``--debug pdb`` because `p.exitcode` will not be defined at that point (old line 77).
> FIX: Bug introduced in ``--debug pdb`` PR (#2871)

- .github/workflows/contrib.yml
- .github/workflows/pre-release.yml
- .github/workflows/stable.yml
* Add concurrency and permissions sections to auto-cancel jobs and prevent over-privileged GITHUB_TOKENs in case of an exploit
* Specify only Python 3 for running black and isort; shouldn't have to do it again
* Add diff outputs for black and isort for nicer reading
> CI: Various updates

- fmriprep/workflows/bold/confounds.py
> FIX: Pass CrownCompCor components to GatherConfounds

- .pre-commit-config.yaml
- pyproject.toml
- wrapper/pyproject.toml
- wrapper/src/fmriprep_docker/__main__.py
Errors introduced in #2914, caught by @mgxd doing the same over in nipreps/nibabies#265.
> FIX: Build leftovers

- docs/outputs.rst
- fmriprep/__about__.py
- fmriprep/workflows/base.py
- pyproject.toml
Integrates and connects up nipreps/smriprep#319.
> ENH: Merge T2w images and coregister to T1w template 

- Dockerfile
- docs/installation.rst
- requirements.txt
Upgrades to a recent version of ANTs that seems less susceptible to #3006.
Closes #3006.
Closes #3015.
> MNT: Update ANTs pin in Docker image

- docs/conf.py
- fmriprep/__main__.py
- fmriprep/cli/run.py
- fmriprep/cli/tests/test_parser.py
- fmriprep/interfaces/gifti.py
- fmriprep/interfaces/multiecho.py
- fmriprep/interfaces/patches.py
- fmriprep/interfaces/reports.py
- fmriprep/interfaces/workbench.py
- fmriprep/reports/core.py
- fmriprep/utils/bids.py
- fmriprep/utils/telemetry.py
- fmriprep/workflows/base.py
Apply [pyupgrade](https://github.com/asottile/pyupgrade) suggestions:
```
pyupgrade --py38-plus
```
\-
> STY: Apply pyupgrade suggestions

- .maint/update_authors.py
- .maint/update_zenodo.py
- docs/conf.py
- fmriprep/interfaces/confounds.py
- fmriprep/interfaces/gifti.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/tests/test_base.py
Except E501 (lines too long).
\-
> MNT: fix flake8 warnings

- .circleci/config.yml
- Dockerfile
- env.yml
> MNT: Install ANTs from conda-forge

- docs/workflows.rst
> Fix typo found by codespell

- Dockerfile
- docs/Makefile
- docs/installation.rst
- docs/links.rst
- docs/outputs.rst
- docs/sphinxext/github_link.py
- docs/usage.rst
> MNT: http:// → https://

- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/outputs.py
We were calculating a registration but not passing it to `unwarp_wf`.
> FIX: Connect EPI-to-fieldmap transform

- .github/dependabot.yml
By the way, would you agree to a mechanism automatically suggesting upgrades of GitHub Actions?
[Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions)
I don't expect more than a PR / year.
> Update GitHub actions

- fmriprep/workflows/base.py
Follow-up to nipreps/smriprep#392.
> ENH: Pass FLAIR images to anatomical workflow builder to include in boilerplate

- docs/outputs.rst
> DOC: Minor updates in outputs.rst

- docs/outputs.rst
- fmriprep/workflows/bold/confounds.py
Closes #1142.
- Rename GSCSF to CSF.
- Rename GSWM to WM.
> RPT: Rename CSF/WM confounds in fMRIPlot

- docker/files/freesurfer7.3.2-exclude.txt
Fix recon-all failure found by @jbwexler.
> FIX: Keep minctracc [skip ci]

- docs/outputs.rst
Closes #3204.
Fix online documentation to ensure consistency with all other places and the code.
DVARS -> standardized DVARS.
> DOC: clarify `--dvars-spike-threshold` uses standardized DVARS

- .maint/paper_author_list.py
- .maint/update_authors.py
- .maint/update_zenodo.py
- docs/sphinxext/github_link.py
- fmriprep/_warnings.py
- fmriprep/cli/parser.py
- fmriprep/cli/run.py
- fmriprep/cli/tests/test_parser.py
- fmriprep/cli/tests/test_version.py
- fmriprep/config.py
- fmriprep/interfaces/confounds.py
- fmriprep/interfaces/gifti.py
- fmriprep/interfaces/multiecho.py
- fmriprep/interfaces/workbench.py
- fmriprep/tests/test_config.py
- fmriprep/utils/bids.py
- fmriprep/utils/misc.py
- fmriprep/utils/telemetry.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/registration.py
- fmriprep/workflows/bold/resampling.py
- fmriprep/workflows/bold/stc.py
- fmriprep/workflows/bold/t2s.py
- fmriprep/workflows/tests/__init__.py
- wrapper/src/fmriprep_docker/__main__.py
Apply the very simple fixes suggested by ruff.
Fixes CI failures, probably related to a recent ruff upgrade.
> CI: Pass ruff tests

- .github/workflows/contrib.yml
Avoid this warning:
warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.
> CI: avoid ruff warning

- fmriprep/workflows/base.py
Ensures the proper resolution templates are fetched following https://github.com/nipreps/smriprep/pull/418
> FIX: Ensure proper templates are retrieved with sloppy

- LICENSE
Copied verbatim from:
https://www.apache.org/licenses/LICENSE-2.0.txt
Just removed the copyright year and set the copyright owner.
> MNT: Verbatim copy of Apache license 2.0

- fmriprep/cli/run.py
- pyproject.toml
- requirements.txt
fix copy of dseg.tsv following templateflow update
> FIX: Require recent templateflow, select correct aparc dseg.tsv

- pyproject.toml
- wrapper/pyproject.toml
Illustrates discussion https://github.com/orgs/nipreps/discussions/46.
Apply some [Repo-Review](https://learn.scientific-python.org/development/guides/repo-review/?repo=nipreps%2Ffmriprep&branch=master) suggestions.
I went for the low-hanging fruits, other changes are more invasive and deserve a PR of their own (for example switching flake8/black/isort to ruff in #3185).
> MNT: Apply Repo-Review suggestions

- fmriprep/config.py
- fmriprep/utils/bids.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/outputs.py
References #3261.
- Add the TemplateFlow base directory to the DatasetLinks.
- Add the template used for normalization to the Sources for standard-space volumetric outputs.
> Add templateflow to DatasetLinks

- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/outputs.py
Closes #3252.
- Replace `RawSources` in `init_ds_boldmask_wf` with `Sources` determined using `BIDSURI`.
> Use BIDSURI in init_ds_boldmask_wf

- fmriprep/cli/run.py
backport fix of copy of dseg.tsv following templateflow update to LTS
> FIX: Select volumetric dseg.tsv from recent TemplateFlow releases

- docker/files/freesurfer7.3.2-exclude.txt
> FIX: Stop excluding FS minc_modify_header used during fallback registration

- .maint/CONTRIBUTORS.md
- .maint/update_zenodo.py
- .zenodo.json
- CHANGES.rst
Alright, time for a release. I think we're in pretty good shape.
@keithcallenberg Would you like to be included in the author listing? Do you have an ORCID and affiliation you would like us to use?
> REL: 25.0.0

- fmriprep/workflows/bold/fit.py
Porting https://github.com/PennLINC/aslprep/pull/531 over.
This should have no impact on the workflow structure for full runs, but allows runs with precomputed derivatives to display SDC reports. I therefore think this should be a patch candidate.
@mgxd Could you have a look? I'm happy to port this over to nibabies as well.
> rf: Separate fieldmap registration from coreg ref generation

- .pre-commit-config.yaml
Changes:
```
ruff (legacy alias)......................................................Passed
```
into:
```
ruff check...............................................................Passed
```
> MNT: Update pre-commit ruff legacy alias

- fmriprep/utils/transforms.py
https://github.com/nipy/nitransforms/commit/23a425d1b8e45a039a98f91bca4b07e9c561f02a
Without this, we get an error like "TypeError: Input file is not in X5 format"
> Update transforms.py according to new tranform chain of nitransforms

- .maint/CONTRIBUTORS.md
Add myself to contributor list after:
https://github.com/nipreps/fmriprep/pull/3504
https://github.com/nipreps/fmriprep/pull/3505
N/A
> DOC: Add myself to contributor list

- Dockerfile
- Dockerfile.base
> fix(docker): Ensure perl is installed in container
