nipreps/fmriprep

- docs/requirements.txt
- fmriprep/__init__.py
- fmriprep/info.py
- setup.py
This fixes the problem that was making niworkflows fail
in its installation. In fmriprep this was not happening because
the main ```__init__.py``` did not import anything.
Added as well a requirements file for building the documentation.
Closes #133
> [FIX] setup.py imported self

- circle.yml
- fmriprep/run_workflow.py
- fmriprep/workflows/anatomical.py
Comments:
- ants  skull stripping is the default option now
- ants skull stripping is turned off for one of the test datasets - this saves test times and makes sure we test both options.
> [RTM] Turn on ants skull strip reports

- circle.yml
- fmriprep/run_workflow.py
This PR increases the verbosity of our tests by generating [workflow graphs](https://67-66973489-gh.circle-artifacts.com/0/home/ubuntu/ds005/scratch/workflow_enumerator/graph.dot.svg) and saving scratch directories (however this is only restricted to txt rst svg and html files to save time).
Saving scratch comes at increaseing test time to 9 minutes.
> [RTM] store scratch directories in artifacts

- fmriprep/run_workflow.py
- fmriprep/workflows/anatomical.py
- test/workflows/test_base.py
- more sensible defaults for ants-threads (use all available cores)
- enable multithreaded processing for brain extraction
- set `num_threads` variables so the MultiProc scheduler would be aware of the required resources
> [RTM] multithreading tweaks

- fmriprep/utils/misc.py
- fmriprep/workflows/base.py
- fmriprep/workflows/confounds.py
- fmriprep/workflows/epi.py
- test/workflows/test_base.py
- test/workflows/test_confounds.py
This PR is attempting to avoid situations where we processing fails because we are trying to run too many tasks consuming a lot of memory at the same time. Now the size of the biggest _bold file is read and three times this much RAM is requested for each critical 4D jobs.
I did not implement this for the sbref/fieldmaps sub workflows since I know @oesteban is actively refactoring them in #198
> [RTM] memory consumption driven scheduling

- fmriprep/utils/misc.py
If there is only one sbref file, for instance, the BIDS data source
will return just one string for the file found.
The former implementation didn't check this point.
> [FIX,RTM] Utility function _first crashes with strings

- fmriprep/interfaces/bids.py
- fmriprep/utils/misc.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/epi.py
I had to pick new source name for derivatives obtained from a combination of T1s. I also had to turn off checking if the `source_file` file exists for this to work - rather controversial, but maybe we can address this when refactoring derivatives datasink.
> [RTM] fix for derivatives sink when multiple t1s are present (ds000051)

- fmriprep/run_workflow.py
Revert "keep unnecessary outputs until report aggregation and datasinks are sorted out. Will allow us to confirm the correct images are being generated until then"
This reverts commit d04fdca5627f7f7bc86b4520fe85920afe1d95ab.
Hopefully, this will slim down the size of working directories. We were already running into issues with their size when working on the Beast.
> [RTM] Don't keep unnecessary outputs

- docs/contributors.rst
- docs/index.rst
- docs/installation.rst
Added a sub-heading to Docker, since most of the prep is just getting the Docker image to run at all. Is this the sort of thing you were looking for, @chrisfilo?
Closes #309.
> Add notes for starting a development environment

- Dockerfile
Apparently 6.0.0 was released properly yesterday, and 6.0.0rc was removed from the server.
> Update FreeSurfer bundle URL

- Dockerfile
This change should reduce the time needed to build a new docker image. The premise is that the most expensive, most stable actions should be first, to take advantage of cache. FreeSurfer release is out, and takes longer than AFNI/FSL, so it's moved forward. Git/graphviz are moved toward the end, as these are cheap, and make a natural place to add new apt packages without forcing a re-fetch of FreeSurfer/AFNI/FSL/ANTs/etc.
I haven't really measured the other parts, so if there are some other ordering changes people want made, let me know.
> Reorder Docker commands to reduce build time

- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/confounds.py
- fmriprep/workflows/epi.py
- fmriprep/workflows/fieldmap/base.py
- fmriprep/workflows/fieldmap/phase_diff_and_magnitudes.py
- fmriprep/workflows/fieldmap/se_fmap_workflow.py
- fmriprep/workflows/fieldmap/unwarp.py
- fmriprep/workflows/fieldmap/utils.py
- fmriprep/workflows/sbref.py
- tox.ini
Mostly line length and block spacing issues. These keep popping up when I style check before committing in #347, but I don't really want to infect that PR with these cleanups.
If people don't like these changes, can we put in a tox.ini or something to tell flake8 what style issues to report?
> Flake8 cleanup workflows/anatomical

- requirements.txt
(Minor) unexpected behavior: `stats` and `labels` directories were getting updated by repeat runs of ReconAll.
Once nipy/nipype#1824 is merged, will update pin and mark [RTM].
> [RTM] Pin new nipype - updates ReconAll response to existing subjects

- circle.yml
- docs/workflows.rst
- fmriprep/interfaces/utils.py
- fmriprep/workflows/base.py
- fmriprep/workflows/confounds.py
- fmriprep/workflows/epi.py
- test/workflows/test_base.py
- Closes #267 by performing interpolation using ANTs
- Outputs EPI in T1w space instead of the EPI space
- Use float32 when applying transforms (turns out they were calculated using float32 anyway)
> HMC refactor

- Dockerfile
- requirements.txt
It turns out that "-e" makes packages appear in sys.path in front of whatever is in PYTHONPATH making it impossible to override installs in singualrity.
This will change installation path and require changes to #317
> [RTM] Don't use editable flags.

- fmriprep/interfaces/bids.py
- fmriprep/utils/misc.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- requirements.txt
Starting to track progress on T2w incorporation.
Follow-up to #347.
> [RTM] Accept T2w images in recon-all

- docs/changes.rst
- docs/workflows.rst
- fmriprep/workflows/anatomical.py
- requirements.txt
As indicated in https://github.com/poldracklab/fmriprep/pull/362#issuecomment-287490389 we have been applying affine and warp transforms in the wrong order causing slight misalignment. To avoid such problems in the future I propose to switching to composite transforms.
> [RTM] Switch to composite transforms.

- fmriprep/workflows/anatomical.py
This may be the issue with Beast. The most likely reason some datasets were working is that `nibabel.as_closest_canonical` didn't change anything (or changed little enough).
> FIX: Reference fs_transform to the reoriented T1, not original

- CHANGES.rst
- docs/workflows.rst
- fmriprep/interfaces/utils.py
- fmriprep/viz/config.json
- fmriprep/workflows/epi.py
- requirements.txt
* Non-steady state detector was added to HMC workflow
* Reference image estimator for HMC was added:
* If non-steady state is detected it will be used as a reference (they tend to have better tissue contrast)
* Otherwise a median of 20 motion corrected volumes will be used as a reference
* EPI skull mask reportlet was brought back
> [RTM] HMC refactor around non-steady state

- fmriprep/cli/run.py
Follow-up to #427, this does a little rearranging to generate the workflow before running reports, allowing the graph to be generated without running the workflow.
> ENH: Allow both --write-graph and --reports-only

- CHANGES.rst
- docs/links.rst
- docs/workflows.rst
- fmriprep/workflows/anatomical.py
- requirements.txt
> [RTM] Gifti surfaces

- CHANGES.rst
- fmriprep/interfaces/utils.py
Avoids loading all of the big multiband images.
> [RTM] use dataobj instead of get_data

- docs/installation.rst
BIDS Apps expect labels without prefixes.
> [RTM] Remove "sub-" prefix

- CHANGES.rst
- docs/workflows.rst
- fmriprep/workflows/base.py
- fmriprep/workflows/epi.py
Building on #362, this uses the registration produced by `bbregister` to sample volumes to the subject-native and `fsaverage` surfaces.
Looks like this will be fairly simple, but `mri_vol2surf` is pretty flexible in its sampling strategy. For each vertex on the surface, there is a normal vector from the white matter surface to the pial surface, and you can choose a point along that vector (in mm or as a fraction of the cortical thickness from 0-1), the average value along a range (start, stop, step; again in mm or fraction) or the maximum value on a range.
As a starter, I've set it to sample the midpoint of the normal vectors.
Looks like this'll be the thing that finally makes me learn to use `JoinNode`.
Closes #355.
> [RTM] Surface sample

- docs/workflows.rst
- fmriprep/workflows/anatomical.py
Discussed in #398.
If any of the functions seem like they should either be moved into `interfaces.utils` or promoted into actual interfaces, this would probably be a good time.
Also maybe worth considering working #429 into this, since it's just a slight factorization of the `Autorecon1` node.
> [RTM] RF: Split out surface recon workflow

- fmriprep/workflows/anatomical.py
Function interface rejects undefined inputs otherwise.
Introduced in #437 because I forgot this lesson from back in #376.
> [RTM] BF: Give detect_inputs default parameter values

- circle.yml
Because we rebuild from scratch every time, every docker image is unrelated, even though there may be no difference in the docker file. The primary goal of this PR is to reduce redundant downloads for users of the `poldracklab/fmriprep` docker images on new releases.
It has a futher advantage of nearly halving the image creation stage on Circle:
The failure on saving the image is a little weird. I'll see if that keeps happening.
> CI: Pull latest image before rebuilding

- docs/environment.yml
- requirements.txt
Fixed docs: https://fmriprep.readthedocs.io/en/fix_docs/workflows.html
Sorry, last night's `BBRegisterRPT` fix actually broke the docs again, but the pin didn't get pushed to `docs/environment.yml`, so it was missed.
No effect on running processes, just on building docs in the absence of FreeSurfer.
[skip ci]
> DOC: Update niworkflows pin

- fmriprep/workflows/anatomical.py
- fmriprep/workflows/confounds.py
- fmriprep/workflows/epi.py
- fmriprep/workflows/fieldmap/fmap.py
- fmriprep/workflows/fieldmap/phdiff.py
- fmriprep/workflows/fieldmap/unwarp.py
This PR takes advantage of nipy/nipype#1918 (recently included because of unrelated nipype updates) to eliminate `input_names` arguments to `Function()` interfaces.
Where functions returned only a single value, I've also switched to the default output name of `'out'`.
This avoids having this sort of clean-up spread over a bunch of PRs, and lets us test this change once and forget about it.
> RF: Use implicit Function input/outputs

- circle.yml
We don't seem to be getting any speed-up from maintaining a docker cache. Every pull still grabs a 2.7GB layer; if the cache were actually loading, we should only see the pip builds and on get pulled and rebuilt each time.
Assuming I'm right and there's no speed up granted by the cache, we should be seeing a pull on the order of 5-6 minutes and the same for the build step.
This will end up saving ~4 minutes per build.
> [RTM] CI: Remove non-working docker cache

- .circle/tests.sh
- circle.yml
The Freesurfer-enabled build takes about an hour. This splits it into its own container using a nipype-style `.circle/tests.sh` script. At present, this saves us about 30 minutes, but any time we can shave off by addressing #477 will be a pure win.
Depends: #476
> [RTM] CI: Use 2x parallel builds

- CHANGES.rst
- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/freesurfer.py
- fmriprep/interfaces/images.py
- fmriprep/utils/misc.py
- fmriprep/workflows/anatomical.py
We've found that FLIRT alignment can sometimes fail on T1 images. Although a 9-DOF affine registration resolves the issue, it appears to be an artifact problem, rather than a scaling issue that would require the extra 3 degrees of freedom.
This PR uses FreeSurfer's `mri_robust_template` to generate a structural reference image.
`mri_robust_template` throws an error on single volumes, so I subclass `freesurfer.RobustTemplate` to copy the input file in that case. (I use a hack similar to that in `freesurfer.ReconAll` to fiddle with the `cmdline`.)
Closes: #439, #473
> [RTM] ENH: Use mri_robust_template for T1 merge

- docs/environment.yml
- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/freesurfer.py
- fmriprep/workflows/anatomical.py
- requirements.txt
Just to get this testing, while waiting on upstream. Same style of command-line hack as in #481.
Here I use explicit copying, rather than `copyfile`, since I don't want the datasink to cause an error by overwriting a file with itself. (This might not actually be a problem; I'm not sure.)
Closes #477.
> [RTM] RF: Skip mris_expand on pre-existing midthickness files

- fmriprep/interfaces/freesurfer.py
`FreeSurferSource` returns an `OutputMultiPath`, so the `graymid` input should follow suit. One particular possibility is that a pre-computed subject directory may have `?h.graymid` in it and we create `?h.midthickness` (copies of `?h.graymid`, since the introduction of `MakeMidthickness`).
A second run-through would receive both, which would cause an error. This change accepts either as input, preferring `?h.midthickness` when available.
It also rejects files from the wrong hemisphere, which means this now can be safely used from a `FreeSurferSource` that did not specify hemisphere.
@chrisfilo Possibility of pre-computed subject dirs containing this file is what convinced me to do this. (I'm test running fmriprep on my PhD data, which contains `?h.graymid` surfaces.)
> [RTM] ENH: Validate graymid inputs from FreeSurferSource

- wrapper/fmriprep_docker.py
Should give a more helpful error message than in #485.
Any thoughts on testing this in Circle? I guess something like `sudo -u unprivileged_user fmriprep-docker ...`?
Closes #485.
> [RTM] ENH: Check for error during memory check

- .circle/tests.sh
Currently `ds054/scratch` isn't being saved to artifacts as it is supposed to be. This checks whether it's a permissions issue.
> [RTM] CI: Fix typo in .circle/tests.sh

- .circle/tests.sh
- circle.yml
Assuming this works, we'll be able to tag commits that don't need to run real code.
> CI: Add a flag to commits to instruct Circle only to build docs

- fmriprep/workflows/fieldmap/fmap.py
- fmriprep/workflows/fieldmap/unwarp.py
- fmriprep/workflows/util.py
As discussed in #504, this wraps N4BiasFieldCorrection into a small workflow that copies the original header to the bias-corrected image.
> RF: Add init_n4bias_wf to run N4 bias correction

- fmriprep/workflows/anatomical.py
- fmriprep/workflows/epi.py
- fmriprep/workflows/fieldmap/phdiff.py
While resuming a mostly-completed workflow, I noticed a number of simple nodes being scheduled, running in <2 seconds, and thus causing the scheduler to wait unnecessarily.
I don't know if this will even buy more than a minute speedup for a large, multi-subject run, so consider this a super low-priority review.
> [RTM] Add run_without_submitting to simple functions, datasinks

- wrapper/fmriprep_docker.py
> FIX: Permit `fmriprep-docker -v` to run normally

- CHANGES.rst
- docs/environment.yml
- docs/workflows.rst
- fmriprep/workflows/anatomical.py
This PR eschews the `-parallel` flag in FreeSurfer, preferring the directives that are volume or hemisphere specific. Thus, we run:
* `-autorecon1` - Single thread (`-parallel` has no effect, but `-openmp` does in places)
* Inject externally skull-stripped image
* `-autorecon2-volonly` - Single thread
* `-autorecon-hemi {lh,rh}` - Replace `-parallel` with nipype parallelism
* `-all` - Run stats and any other post-hemisphere-specific processing
Also takes advantage of #494 to get rid of the separate `get_surfaces` node.
> [RTM] RF: Split recon-all into coarse chunks to improve resource use estimates

- CHANGES.rst
- fmriprep/workflows/confounds.py
It's more intuitive in context of using those for nuissance regression.
> [RTM] move missing values to the beginning of the confounds file

- fmriprep/interfaces/bids.py
`recon-all` [symlinks](https://github.com/freesurfer/freesurfer/blob/release_6_0_0/scripts/recon-all#L4887-L4895) `fsaverage` if it doesn't exist. This PR guarantees a copy is made even if `fsaverage` is not among the specified output spaces.
Fixes #535.
> FIX: Always copy fsaverage

- docs/environment.yml
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/fieldmap/fmap.py
- fmriprep/workflows/fieldmap/phdiff.py
- fmriprep/workflows/util.py
- requirements.txt
Taking advantage of nipy/nipype#2034 to simplify workflows slightly.
> [RTM] RF: Use N4BiasFieldCorrection(copy_header=True)

- fmriprep/workflows/epi.py
- fmriprep/workflows/util.py
This is in preparation for SDC unwarping, and abstracts the two BBR branches into workflows with equivalent (but partially unused) inputnodes and outputnodes.
It may not end up being used in other places, but I'm using these for testing, and I think they clean up the `epi_reg_wf` a little bit.
> [RTM] RF: Add interchangeable FreeSurfer/FSL BBR workflows

- Dockerfile
Builds seem to be breaking on this.
@yarikoptic Is this a bug, or does Neurodebian not keep old versions of packages around?
> DEP: Update Neurodebian AFNI pin

- CHANGES.rst
- fmriprep/interfaces/images.py
- fmriprep/workflows/anatomical.py
The existing anatomical pipeline merges T1w images using `mri_robust_template`, and then realigns the result to RAS in a conformation step.
This PR will swap these steps, and update the conformation step to ensure that each T1w image is in a common space (zooms, dimensions, RAS orientation), prior to passing the resulting series to `mri_robust_template`.
The final zoom in each dimension is the smallest of the input zooms in that dimension, and the number of voxels in that dimension is set to the highest.
If no transformations need to be applied, the original file is copied (or linked) to reduce the possibility of error.
Closes #538.
> [RTM] ENH: Conform multiple T1w images, resampling if necessary

- Dockerfile
Neurodebian doesn't appear to have the [5.0.9-1](http://neuro.debian.net/pkgs/fsl-core.html#binary-pkg-fsl-core) fsl-core version anymore. This update brings the fsl-core version to the version available on neurodebian. I remember seeing a conversation about versioning with neurodebian, so maybe there is a more general solution available.
> FIX: update fsl-core from neurodebian

- fmriprep/interfaces/images.py
This PR attempts to make the conformation step minimally disruptive.
* Rescaling and resizing operations are logically separated in calculating the target affine
* Rescaling is only applied if there is a > 0.05mm difference between the original and target zooms
* Resizing is restricted to an integer shift, rather than scaling the intercept; this should avoid half-voxel interpolations if an odd number of voxels are tacked on
* The original image header is copied to the target, reducing the divergence of the header only to changes induced by an updated affine
Additionally, symlinks are disallowed for untouched files, so that the working directory can be created by a docker image and inspected outside.
Fixes #562.
> [RTM] FIX: Reduce interpolation artifacts in ConformSeries

- fmriprep/workflows/fieldmap/fmap.py
> FIX:fieldmaps

- fmriprep/workflows/anatomical.py
Ran across this bug while testing #561 on uh2/sub-s497.
I miscategorized the `-T2pial` step as part of `autorecon_surfs`, in which each hemisphere runs without reference to the other. `-T2pial` uses the contralateral surfaces as part of its workflow, so it should be part of `autorecon3`. The cortical parcellation is done/[redone](https://github.com/freesurfer/freesurfer/blob/master/scripts/recon-all#L6883-L6895) following pial refinement with a T2w image, so I removed them from `autorecon_surfs`, which allows us to drop the `autorecon2_surfs` step.
So the upshot is:
* Removed the `autorecon2_surfs` `MapNode`
* Pushed a number of steps to `autorecon3`, including `-T2pial`, if used
* Upgraded `autorecon3` to a `MapNode`
* Run the report at the end by itself
> FIX: Reroute recon_all workflow to correctly handle T2w images

- CHANGES.rst
- docs/workflows.rst
- fmriprep/cli/run.py
- fmriprep/interfaces/bids.py
- fmriprep/workflows/base.py
- test/workflows/test_base.py
This may be instant-reject, but it's not clear to me that there is an advantage to rejecting datasets without functional images. We already throw a warning in their absence.
(I created this branch a while ago to test the anat pipeline on a user's T1w image.)
> [RTM] ENH: Add --anat-only workflow option

- CHANGES.rst
- fmriprep/info.py
- fmriprep/workflows/epi.py
Correction: Unused parameters were causing a node crash.
----
Original description:
Workflows without phase-encoding directions are not completing due to two missing connections.
> FIX: Remove unused parameters in function node

- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/images.py
- fmriprep/viz/config.json
- fmriprep/viz/report.tpl
- fmriprep/viz/reports.py
- fmriprep/workflows/epi.py
As discussed in #573, BOLD series with invalid headers (no valid qform/sform) can cause a number of issues, including failure of skull stripping. I've also found that bbregister will fail to run.
It was decided that, instead of rejecting these images, we allow nibabel to assume an LAS orientation and set a default sform, and note this prominently in the reports.
The current warning is:
-----
Input file does not have valid qform or sform matrix. A default, LAS-oriented affine has been constructed. A left-right flip may have occurred. Analyses of this dataset MAY BE INVALID.
-----
Related #260 
Closes #573
> [RTM] ENH/FIX: Validate and minimally conform BOLD images

- CHANGES.rst
- docs/environment.yml
- fmriprep/info.py
- fmriprep/viz/report.tpl
- fmriprep/viz/reports.py
- requirements.txt
This adds an "About" section, which includes the FMRIPREP version and a timestamp. 
It also pushes "Errors" out from under "Functionals", since we are not currently collating errors by workflow type.
> ENH: Add version and timestamp

- fmriprep/workflows/fieldmap/unwarp.py
Typo in `init_pepolar_unwarp_wf` resulted in a minor bug that showed up in both #595, #598.
This PR connects the mask report to the `pepolar_unwarp_wf.outputnode.out_mask_report` entry.
> [RTM] FIX: Connect report to outputnode.out_mask_report

- fmriprep/cli/run.py
Fixes #595.
This creates a `derivatives/fmriprep/logs` directory and saves logs and text crashfiles there.
Some other minor cleanups I saw while in there. Probably most significant is only building the graph if we're going to run it or write the graph. This allows `--reports-only` without `--write-graph` to run more quickly.
Closes #240.
> [RTM] ENH: Save text crashfiles in output directory

- docs/anat/base.rst
- docs/links.rst
- docs/workflows.rst
- fmriprep/interfaces/images.py
- fmriprep/viz/config.json
- fmriprep/workflows/anatomical.py
This PR stems from #599, which revealed that we've been conforming wrongly. The error was so small that the error only appears for highly anisotropic voxels in an oblique orientation.
In addition, it introduced the case where high- and low-quality T1w scans coexist in the same dataset, and the upsampling involved would ultimately degrade the quality of a template produced by averaging the images.
The following changes are introduced:
* Rescaling is applied to affine columns, as opposed to rows, which will correctly set the zooms in the resampled dataset
* A size (dimension) factor is recalculated to be less sensitive to large differences in dimension
* A `max_scale` factor (default: 3) discards images which require upsampling over a given ratio
* An HTML reportlet is created to describe …
> [RTM] FIX: Correctly resample T1w images in ConformSeries

- fmriprep/workflows/fieldmap/unwarp.py
Do we have a good dataset to test this? It showed up with blip-up/blip-down, presumably single volume field maps.
Closes #598.
> [RTM] FIX: Ensure un-nested lists are not over-flattened

- docs/environment.yml
- fmriprep/workflows/confounds.py
- requirements.txt
Closes #361.
Because pin includes poldracklab/niworkflows#188:
Fixes #616
Closes #619
> [RTM] ENH: Add non-steady-state detection before CompCor

- CHANGES.rst
- Dockerfile
- docs/installation.rst
> ENH: Use updated ICA-AROMA

- wrapper/setup.py
#626 showed that `pip install fmriprep-docker` from a clean environment can fail, because `future` isn't installed. This should tell pip to bootstrap installation by installing `future` before reading `setup.py`.
> FIX: Require future for fmriprep-docker setup

- fmriprep/cli/run.py
This PR alerts users that specify `--use-aroma` if they don't have the necessary flags to sample the BOLD series in MNI space.
This could be replaced with a strategy of calculating the transforms without adding outputs to the derivatives directory, but this approach keeps behavior closely matched with arguments.
Closes #625.
> [RTM] ENH: Check output spaces for --use-aroma

- fmriprep/workflows/anatomical.py
This PR adds a second `ConformSeries` step post-merge, which ensures that the final template is RAS oriented. This reduces to a `nibabel.as_closest_canonical`, and will not make a new copy (even in memory) if the input is already RAS.
Fixes #636
> [RTM] FIX: Add second reorient step, in case LIA image is created

- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/fmap.py
- fmriprep/workflows/bold.py
- fmriprep/workflows/fieldmap/base.py
- fmriprep/workflows/fieldmap/fmap.py
- fmriprep/workflows/fieldmap/phdiff.py
- fmriprep/workflows/fieldmap/unwarp.py
- fmriprep/workflows/util.py
> [RTM] Code revision - fieldmaps

- docs/environment.yml
- requirements.txt
See https://github.com/poldracklab/fmriprep/issues/360#issuecomment-319211238 and nipy/nipype#2136
Closes #360.
> [RTM] ENH: Improve confound header names

- CHANGES.rst
- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/reports.py
- fmriprep/viz/config.json
- fmriprep/viz/report.tpl
- fmriprep/viz/reports.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
This one's taking a bit more work than I expected. The reportlet is in place, but I'm not sure what the best way to integrate it into reports would be, since it will end up at the same level as "Anatomical" and "Functional", when all of the other reportlets are going under subheadings.
I've started fiddling with the template, but figured I'd put up what I've got at the moment.
Closes #639.
> [RTM] ENH: Subject-level summary report

- fmriprep/workflows/bold.py
As discussed in #253, constructing a mean BOLD image would require a reference from each run to be created and merged. This PR takes a first step toward that end by separating reference generation from HMC.
It is set up so that a list of workflows could be easily generated from a list of BOLD images, but at the moment, it's simply moved to the start of `init_func_preproc_wf`.
> [RTM] RF: Separate BOLD reference generation from head-motion correction

- CHANGES.rst
- fmriprep/workflows/bold.py
Currently, head motion correction is being estimated on slice-timing corrected volumes, but applied to the original, uncorrected volumes.
This PR ensures the inputs to HMC and fslsplit are the same, with slice-timing correction applied to both or neither.
> [RTM] FIX: Enable inactive slice timing, fieldmap unwarping options

- fmriprep/interfaces/bids.py
- fmriprep/interfaces/reports.py
The issue is that `OutputMultiPath` considers an empty list `Undefined`, so we have to handle that case specifically.
Closes #669.
> [RTM] FIX: Handle missing functional data in SubjectSummary node

- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/utils.py
- fmriprep/workflows/fieldmap/fmap.py
This looks like an unnecessary interface, as [every other instance](https://github.com/poldracklab/fmriprep/search?utf8=%E2%9C%93&q=ApplyMask&type=) uses [fsl.ApplyMask](https://nipype.readthedocs.io/en/latest/interfaces/generated/interfaces.fsl/maths.html#applymask). Rather than add documentation, we can just drop it.
If there's any reason not to do this, feel free to close without discussion.
> RF: Drop custom ApplyMask for fsl.ApplyMask

- .circle/tests.sh
- CHANGES.rst
- fmriprep/data/affine.json
- fmriprep/workflows/util.py
A failure of initial alignment appears to have resulted in no-op registration, which cascaded. Adding a center-of-mass initial transform appears to have resolved it, but this may not work for partial FoV's that aren't also centered roughly on the midbrain.
Also found a small bug in reading the BBR cost, so fixing that while here.
Fixes #665.
> [RTM] FIX: Initialize SyN SDC more robustly

- fmriprep/cli/run.py
Relative imports make directly calling `cli/run.py` impossible. If we used absolute imports, then it would work with the first version of fmriprep in the `PYTHONPATH`, which may not always be expected behavior. The simpler solution (suggested by @oesteban) is to raise an error and explain the situation.
I've moved a top-level relative import into the necessary functions, so that the exception can be raised.
Closes #691.
> [RTM] FIX: Raise RuntimeError when run.py is run directly

- fmriprep/workflows/bold.py
Closes #719.
-----
```Shell
$ git blame fmriprep/workflows/bold.py | grep -C 2 "Creating FreeSurfer"
8cc9b683 fmriprep/workflows/epi.py  (Christopher J. Markiewicz 2017-04-18 09:36:15 -0400  521) 
0bbd2f6b fmriprep/workflows/epi.py  (Chris Gorgolewski         2017-04-22 17:57:41 -0700  522)     if freesurfer and any(space.startswith('fs') for space in output_spaces):
88caddce fmriprep/workflows/epi.py  (oesteban                  2017-04-03 14:35:06 -0700  523)         LOGGER.info('Creating FreeSurfer processing flow.')
23bb9b18 fmriprep/workflows/bold.py (oesteban                  2017-07-31 12:06:40 -0700  524)         bold_surf_wf = init_bold_surf_wf(output_spaces=output_spaces,
fad24b26 fmriprep/workflows/bold.py (mathiasg                  2017-08-31 15:47:06 -0400  525) …
```
> LOG: Clarify BOLD surface-sampling log message

- docs/workflows.rst
- fmriprep/interfaces/reports.py
- fmriprep/workflows/bold.py
BOLD series with < 5 usable volumes (apparently these exist...) can't be slice-timing corrected, at least with 3dTShift. This PR will add a check that the number of volumes minus the skipped volumes is at least 5. In the event that STC is disabled due to this check, it will report that in the summary for that BOLD file.
I factor the STC workflow out of HMC (even though it's currently just two nodes) to keep the issues separated. This will hopefully keep the check from cluttering HMC beyond readability.
Closes #696.
> [RTM] ENH: Disable STC on short time series

- fmriprep/interfaces/utils.py
This may or may not resolve #716 and our various other issues with binary erosion that have popped up, but from the [`ndimage.binary_erosion` docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.binary_erosion.html):
> **iterations** : *{int, float}, optional*
> > The erosion is repeated iterations times (one, by default). If iterations is less than 1, the erosion is repeated until the result does not change anymore.
Running on ds000243/sub-012 again, and we'll see if #731 is still needed, but this should definitely go in.
> [RTM] FIX: Set minimum number of erosion iterations

- fmriprep/interfaces/utils.py
- fmriprep/workflows/confounds.py
This change erodes WM mask (approximately) to target proportions of original white matter voxel counts.
Closes #716
> [RTM] ENH: Erode WM mask by proportion

- Dockerfile
- docker/scripts/get_templates.sh
Adapted from #729.
Will only shave a minute off of builds, but it is a lot of unnecessarily repeated work.
> [RTM] DOCKER: Download templates before installing fmriprep

- .zenodo.json
Ran across this commit in the [network](https://github.com/poldracklab/fmriprep/network). Inclusion is overdue, and should go in before next release.
> [RTM] Add James D. Kent to .zenodo

- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold.py
- fmriprep/workflows/util.py
Because I have three PRs (#694, #733, #740) all working in the same areas of code, to work on one almost invariably causes collisions with the others. This PR simply tracks what I think are uncontroversial changes that have come up while working in one that don't impact the *functioning* of the others.
* Cleans up unused workflow inputs/outputs
* Makes `fs_2_t1_transform` follow the `t1_2_<space>_(forward|reverse)_transform` convention
* Moves ITK affine matrix creation into the BBR workflows
* In the case of FreeSurfer's `bbregister`, uses FreeSurfer's native LTA format until ready to convert to ITK
If this list grows, I will rebase the other PRs against it.
> [RTM] RF: Miscellaneous registration refactorings

- fmriprep/interfaces/reports.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold.py
- fmriprep/workflows/util.py
As discussed in #714, the simplest way to build in a prior of A-P phase-encoding is to always use A-P unless otherwise specified. When this produces a discernible error, the correct response would be to update the dataset metadata.
With this change, we can eliminate the cost function machinery from the BBR workflows, which should simplify #694, if this goes in first.
Closes #714.
> [RTM] RF: Assume phase-encoding direction is A-P unless specified L-R

- fmriprep/workflows/bold.py
Quick fix. Introduced in effigies#1.
> FIX: 'i-' and j-' are valid PE directions

- .circle/data/ds005_outputs.txt
- .circle/data/ds054_outputs.txt
- docs/workflows.rst
- fmriprep/interfaces/surf.py
- fmriprep/workflows/anatomical.py
Addresses issue raised in https://github.com/poldracklab/fmriprep/pull/726#issuecomment-333183529.
Given this, I think we should output the registration transform, to give users the tools to move between FMRIPREP and FreeSurfer spaces. I'd recommend the LTA format, since that has more metadata about the source and target spaces; if users need to convert to other formats, they will presumably have access to the `LTAConvert` tool.
To do:
> [RTM] ENH: Register FreeSurfer template to FMRIPREP template

- .circle/tests.sh
- docs/workflows.rst
- fmriprep/cli/run.py
- fmriprep/interfaces/reports.py
- fmriprep/viz/config.json
- fmriprep/workflows/base.py
- fmriprep/workflows/bold.py
- fmriprep/workflows/tests/test_base.py
- fmriprep/workflows/util.py
The easiest way to read this PR is to separately review #741, and read https://github.com/effigies/fmriprep/compare/fsfix_common...bbr_fallback.
Closes #681.
> [REVIEW] Fallback to initial registration, if BBR fails

- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold.py
* Create `t1_2_fsnative_forward_transform` by inverting `t1_2_fsnative_reverse_transform`
* In passing, convert this to ITK to create the derivative, rather than inverting (again) and converting to ITK
* Pass `t1_2_fsnative_forward_transform` to `bold_surf_wf`
* Create "identity" LTA from BOLD space to T1w
* Concatenate with `t1_2_fsnative_forward_transform`
> [RTM] FIX: Use t1_2_fsnative registration when sampling to surface

- fmriprep/workflows/anatomical.py
The issue presented in #767 occurs when trying to find a mean transform between the two images (what we've been calling "unbiased"). The two images had a large translation in the I/S direction, which I assume caused the issue.
This fix disables unbiased templates for 2 image subjects unless `--longitudinal` is passed.
Closes #767.
> FIX: Only use unbiased template with --longitudinal

- Dockerfile
See https://github.com/poldracklab/fmriprep/issues/749#issuecomment-336170941
This should be merged shortly before the next release. Doing so before then will waste time during builds to no benefit, since users won't see the images built until release.
> [RTM] DOCKER: Add rX permissions to make life easier on Singularity users

- docs/environment.yml
- fmriprep/info.py
- fmriprep/interfaces/itk.py
- fmriprep/workflows/bold.py
- requirements.txt
Adds the new `fov_mask` connection to the node that generates the registration target reference in T1w space, but with BOLD resolution.
This could also be added to the MNI resampling target, however, the MNI space is already restrictive enough in terms of FoV.
Closes #722
> [FIX] Reduce FoV of outputs in T1w space

- fmriprep/cli/run.py
- fmriprep/info.py
This PR implements this suggestion https://github.com/poldracklab/fmriprep/issues/766#issuecomment-337695677
If we find this useful, it is worth considering to add a new nipype config that leverages indexed_gzip with nibabel.
Hopefully, this is the last piece of several PRs to fix #766
> [ENH] Use indexed_gzip with nibabel

- docs/workflows.rst
- fmriprep/interfaces/itk.py
- fmriprep/viz/reports.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/bold.py
It seems like the memory issues are caused by LS5's particular setting that maps `/tmp` into RAM. You can consume up to 32GB in `/tmp` that are discounted from the overal RAM.
FMRIPREP was using `/tmp` in the resampling of all BOLD scans into T1 and MNI. For long runs and/or many runs, the 32GB limit was reached in fact reducing the total amount of memory for processes to only 32GB (the total in LS5 is 64GB).
In this PR some other optimizations are also done: make sure we always close file handlers and memory annotations have been revised to more sensible values.
> [FIX] Memory issues in LS5

- .circle/data/ds005_outputs.txt
- .circle/data/ds054_outputs.txt
- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/freesurfer.py
- fmriprep/interfaces/images.py
- fmriprep/interfaces/utils.py
- fmriprep/workflows/anatomical.py
I took a little time to clean this up post 1.0.0-rc6, including some lessons learned regarding affine derivatives.
Current status:
- This creates a simple transform from each input T1w file to the T1w space (defined by `T1w_preproc.nii.gz`)
- It places it in the associated derivative directory of the input file, i.e. in a session-specific `anat/` directory
Decisions going forward:
- Is this worthwhile?
- Should we organize it differently?
- Should we give the template and spaces/affines more generally their own page to make crystal clear exactly how each non-identical affine relates to each other and how to translate from one to another?
-----
Open to critiques. @satra, this one's for you.
Closes #624.
> [RTM] ENH: Conformation transforms

- CHANGES.rst
- fmriprep/workflows/bold/stc.py
- fmriprep/workflows/bold/util.py
As noted in #743, AFNI doesn't believe in NIfTI headers. #807 introduced a bug by targeting an antsApplyTransform at an image with an AFNI-corrupted header.
Fortunately, every AFNI tool we use doesn't change the affine space, so we can overwrite the qform/sform with the original affine. This change adds/moves header correction to immediately after each AFNI process.
> FIX: Immediately fix headers of AFNI outputs

- fmriprep/interfaces/images.py
`img.get_qform(coded=True)` [returns `(None, 0)`](https://github.com/nipy/nibabel/blob/master/nibabel/nifti1.py#L915-L916) if the code is 0, but otherwise returns the qform. The same is true for `get_sform`.
Thus, adding the `is not None` check is required to make this function work as expected.
Fixes #822.
> FIX: Check q/sform is not None

- fmriprep/info.py
- fmriprep/interfaces/itk.py
- fmriprep/workflows/anatomical.py
- Add annotations
- Reduce the number of processes forked by using the ThreadPoolExecutor.
> [REF] More memory annotations and considerations

- fmriprep/cli/run.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/stc.py
- wrapper/fmriprep_docker.py
Enables the `-v` flag for fine-grained tunning of FMRIPREP's quietness.
The default level is 25, only IMPORTANT messages or above (WARNING, ERROR)
will be written.
With one `-v` the level goes to 20 (INFO). Two (`-vv`) maps to the VERBOSE
new level. Finally, three (`-vvv`) is the DEBUG level.
> [REF] Fine-grained logging (make FMRIPREP less shy)

- docs/workflows.rst
Quick cleanup of the workflows page, noticed while reviewing #828.
> DOC: Use non-hierarchical graph for bold_preproc_trans_wf

- fmriprep/interfaces/itk.py
The error was:
```
Traceback (most recent call last):
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/linear.py", line 43, in run
node.run(updatehash=updatehash)
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
self._run_interface()
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
self._result = self._run_command(execute)
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
result = self._interface.run()
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
runtime = …
```
> [FIX] MultiApplyTransforms failed with nthreads=1

- fmriprep/interfaces/images.py
Follow-up to #847, intended to clarify my opinions on this interface.
First, I think this is the easiest place to go ahead and sync qforms and sforms, unconditionally.
Second, I've refactored the warnings to follow this logic:
1) If qform/sform codes are bad, declare "WARNING - Invalid header"; if only qform is invalid, declare "WARNING - Invalid qform".
2) If the qform is invalid (and is not marked invalid), note it simply in the description.
3) If qform/sform are valid, but out of sync, make a note (without "WARNING") that they're mismatched.
Just as some after-the-fact commentary on #847: I think the warnings for invalid qforms are weird, in that a qform_code of 0 is treated as intensifying the problem with invalid qforms, rather than mitigating it. It's bad and marked as bad. That …
> [RFC] ENH: Always sync qforms, refactor error messaging

- wrapper/fmriprep_docker.py
This should make testing with nipype modifications easier. The nipype mount point never got updated when we moved to using it as a submodule.
(I seem to remember symlink issues while mounting niworkflows being a thing, so hopefully this will resolve that, as well.)
> WRAPPER: Mount nipype repositories as niworkflows submodule

- fmriprep/cli/run.py
- fmriprep/viz/__init__.py
- fmriprep/viz/reports.py
> [FIX] Controlling memory explosion

- fmriprep/cli/run.py
After the experience of reducing the memory fingerprint of fmriprep, the Linear plugin is heavily affected by the memory explosion as it is implemented now. The easiest alternative is using MultiProc with `n_procs=1`.
Closes #855
> [ENH] Use Nipype MultiProc even for sequential execution

- fmriprep/interfaces/freesurfer.py
RobustTemplate does not define `transform_outputs` if not asked to, so we don't need to create an identity transform in that case.
Fixes #858.
> [RTM] FIX: Only create identity transform if requested

- docs/workflows.rst
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/base.py
Ended up writing my own quick profiler, captured this memory profile, which seems to follow a 2N-1.5 rule, where N is the number of input images.
This looks like an effect of registering each subsequent image to the first being embarrassingly parallel. If we hit more images than available threads, then I suspect the profile will end up looking a bit different, but I'm not sure it's worth trying to finesse this. If we get to a lot of input images, it will probably justifiably be the only thing running for a bit.
> MEM: Annotate t1_merge with approximate memory usage

- fmriprep/cli/run.py
Nipype's `stop_on_first_crash` option will be `True` by default, except if `-w` is specified. In that case, using the `--stop-on-first-crash` will force it back to `True`.
Closes #850
> [ENH] Add --stop-on-first-crash option

- docs/citing.rst
- docs/workflows.rst
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/hmc.py
- fmriprep/workflows/bold/stc.py
- fmriprep/workflows/fieldmap/base.py
This PR focuses on estimating head-motion parameters before temporal filtering of the signal, as suggested in (Power, 2017) - see #849.
If slice-timing correction (STC) is done, then all processing is tailored to STC. Otherwise, the original data are used.
>  [ENH] Estimate motion parameters before STC

- docs/workflows.rst
- fmriprep/interfaces/nilearn.py
- fmriprep/workflows/bold/util.py
This PR:
Closes #902, #905, #907. Ref. #895.
> [FIX] Robuster EPI mask

- CHANGES.rst
- docs/citing.rst
- docs/workflows.rst
- fmriprep/info.py
- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/freesurfer.py
- fmriprep/interfaces/surf.py
- fmriprep/workflows/anatomical.py
Use the `aseg.mgz` output of FreeSurfer to derive a refined mask to replace the (generally less conservative) mask calculated with `antsBrainExtraction.sh`.
Closes #431
> [FIX] Refine antsBrainExtraction if recon-all is run

- fmriprep/utils/bids.py
As discussed in #914, bold runs should not be grouped only by run, as this could yield multiple tasks in the same run sub-list. Instead, both task and run should be used as grouping factors. Tested on `ds000210/sub-02` and `ds000205/sub-07`.
> Patch to group bold scans by task AND run

- fmriprep/utils/bids.py
I'm going to revert this change until we have a fully tested solution. @emdupre, I'll help you set up new tests on both ds000210 and ds000216 (they are multi-echo but have different combinations of tasks and runs).
Alternatively (probably best), we could submit a PR to the BIDS examples with three different multi-echo patterns:
1. With tasks and runs (I think ds000210 is like this)
2. With only tasks (I think ds216)
3. With sessions.
And use this as test data. WDYT @emdupre, @chrisfilo ?
> [FIX] Revert run grouping (fixes #914)

- CONTRIBUTING.md
Updates the CONTRIBUTING.md file to link to the guide for [creating an FMRIPREP development environment](http://fmriprep.readthedocs.io/en/latest/contributors.html), as discussed in #922.
More significantly, this PR also updates the CONTIBUTING narrative to be more beginner friendly, following text from the [ME-ICA repository](https://github.com/emdupre/me-ica/blob/py3/CONTRIBUTING.md).
> [DOC] Update CONTRIBUTING

- .zenodo.json
Adds @emdupre to the zenodo file (as requested in the contributing guidelines!). 
I'm not sure the intended ordering, so I added myself towards the middle of the file. Please let me know if there's a preferred order and I can update!
> [DOC] Add @emdupre to zenodo

- fmriprep/workflows/bold/base.py
Do not group echoes in multi-echo datasets so that each echo is processed separately (while we work on #921 for a long-term solution)
Fixes #928
> [FIX] Revert echo grouping

- docs/citing.rst
Small fix:
- DOI for 17 was hyperlinked to 16's paper, this fixes the hyperlink to go to the correct landing area.
> [DOC] fix doi

- .circleci/config.yml
This should keep it from trying to push a new image with every commit to master.
> CI: Do not deploy on branches, only tags

- fmriprep/viz/report.tpl
Fixes #971.
This PR proposes replacing a `<div>` with a `</div>`.
> fix: close `<div> tag`

- docs/conf.py
- fmriprep/info.py
As suspected, this bugfix (sphinx-doc/sphinx#2557) to sphinx broke our builds, since mocked modules do not mock ancestors anymore. An updated mocks list (only for sphinx>=1.7.0) is added in this package. Version is checked with packaging.version to avoid distutils (also, setuptools depends on packaging so it was installed before declaring it as a dependency).
Fixes #973.
> [HOTFIX] Sphinx 1.7.0

- fmriprep/cli/run.py
To make it easier to call `--medial-surface-nan`
> fix: argparse action

- docs/workflows.rst
- fmriprep/interfaces/__init__.py
- fmriprep/interfaces/reports.py
- fmriprep/interfaces/utils.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/resampling.py
- fmriprep/workflows/tests/test_confounds.py
Now, the brain mask written out to the derivatives folder is the mask presented in the ROIs plot, but in MNI space.
Fixes (the MNI part of) #963.
Changes:
> [FIX] ROIs Plot and output brain masks consistency

- fmriprep/interfaces/multiecho.py
- fmriprep/workflows/bold/base.py
As discussed in #1009, the BIDS spec does not currently enforce that `*_echo-1*` is the shortest TE of all collected echos. This should patch the current sorting procedure to grab the shortest echo and treat as the `ref_file`.
> [FIX] Use metadata to select shortest echo as ref_file

- .gitmodules
- .travis.yml
This way, we can keep the notebooks and the main fmriprep code separated
> [ENH] Add a new submodule to maintain notebooks

- .circleci/config.yml
- docs/workflows.rst
- fmriprep/cli/run.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/resampling.py
- fmriprep/workflows/tests/test_base.py
- wrapper/fmriprep_docker.py
This PR resurrects the dicussion about native or other output resolutions. ~~In particular, this PR CHANGES the current default (the "native" space of the input BOLD file) and sets the template-2mm version~~.
Implications:
* As off this PR, any new template added to FMRIPREP will require having a 1mm and a 2mm resolution versions. This was probably necessary already, but from this PR on it will be mandatory for sure.
* The default behavior until v1.0.8 can be obtained using ``--output-grid-reference native``.
* The option has been renamed: from ``--output-grid-reference`` to ``--template-resampling-grid``, as it is more descriptive.
Justification:
* Comparison studies need not only a standard (physical) space, but also a standard voxel size (digital space) for the good of analysis.
* …
> [ENH] Revise resampling grid for template outputs

- fmriprep/workflows/bold/base.py
Equating STC check for multi-echo and single-echo bold data-- trying to debug the error in ds210 tests seen in #1037 and #1036.
> [WIP, TST] Pass ref_file to STC check

- fmriprep/workflows/fieldmap/base.py
As a result of refactoring, this node got disconnected for that particular use-case.
This PR fixes that (https://github.com/poldracklab/fmriprep/pull/1001#issuecomment-379000810)
Thanks @mgxd for spotting this problem.
> [FIX] Connect inputnode to SDC for pepolar images

- fmriprep/interfaces/images.py
Nibabel does a bit of validation on qforms already, in that it takes some work to produce an affine from the header. However, sforms are stored more-or-less directly, and nibabel simply shuttles values in and out of the header.
This checks for a non-zero determinant and that the RSS of each column matches the zooms.
Closes #1069.
> FIX: Check for invalid sform matrices

- fmriprep/interfaces/bids.py
not fully tested - adapted from @effigies  https://github.com/poldracklab/fmriprep/issues/1075#issuecomment-385057946
> [FIX] Derivatives datasink handling of compression

- Dockerfile
- fmriprep/workflows/bold/confounds.py
For the sake of cross-browser compatibility, we should revert to PNG for displays.
Leaving `svgo`.
Closes #945 
Closes #969 
Related: #977
> MAINT: Remove cwebp to revert to png

- fmriprep/interfaces/bids.py
This PR tries to fix #1075 for good.
> [FIX] Compression in DataSinks

- docs/workflows.rst
Addresses #1182.
Iterates on documentation for re-using freesurfer derivatives directory. I've switched to a Sphinx note (since it seems that this issue has come up repeatedly, and is worth highlighting), and I also moved the text up to a more prominent spot in the paragraph.
Happy to make any suggested changes, here !
> [DOC] Better document re-using FS derivatives

- docs/environment.yml
- fmriprep/cli/run.py
- fmriprep/info.py
- fmriprep/interfaces/bids.py
- fmriprep/interfaces/confounds.py
- fmriprep/interfaces/fmap.py
- fmriprep/interfaces/freesurfer.py
- fmriprep/interfaces/images.py
- fmriprep/interfaces/itk.py
- fmriprep/interfaces/multiecho.py
- fmriprep/interfaces/nilearn.py
- fmriprep/interfaces/utils.py
- fmriprep/utils/bspline.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/stc.py
- fmriprep/workflows/bold/t2s.py
- fmriprep/workflows/fieldmap/base.py
- fmriprep/workflows/fieldmap/syn.py
- requirements.txt
Testing nipy/nipype#2598 on the fmriprep battery.
> PIN: nipype 1.1.0

- Dockerfile
It sets the last WORKDIR in the docker image to /tmp, instead of /root/src/fmriprep, so now you can run the docker container as a user different from root.  
As far as I can tell, if no working directory is specified by the `-w` parameter, fmriprep will try to create the folder `work` under `/root/src/fmriprep`, and only root has access to that folder.
This should fix problems people have found when running docker specifying a user (e.g., ref #1060).
**Please review and check the following**:
finished (i.e. no ``[WIP]`` tag remains in the title of my PR) and tests pass.
[coding style](https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md#fmriprep-coding-style-guide),
to the extent I understood them (and I will address any comments raised by the PR's reviewers in this …
> [FIX] Corrects Dockerfile WORKDIR.

- .circleci/config.yml
- Dockerfile
- wrapper/fmriprep_docker.py
Enables a ``-u`` flag for the Docker wrapper. Add testing this flag into ds005 tests.
Documentation is automated with the usage of `fmriprep-docker`
1. We invite you to list yourself as a *fMRIPrep* contributor, so if your name 
is not already mentioned, please modify the 
[``.zenodo.json``](https://github.com/poldracklab/fmriprep/blob/master/.zenodo.json)
file with your data right above Russ' entry. Example:
```
{
"name": "Contributor, New FMRIPrep",
"affiliation": "Department of fMRI prep'ing, Open Science Made-Up University",
"orcid": "<your id>"
},
{
"name": "Poldrack, Russell A.",
"affiliation": "Department of Psychology, Stanford University",
"orcid": "0000-0001-6755-0259"
},
```
2. By submitting this request you acknowledge that your contributions are available under the BSD …
> [ENH] Enable ``-u`` (docker user/userid) flag in wrapper

- LICENSE
- docs/license.rst
- wrapper/fmriprep_docker.py
Updates documentation URL in fmriprep-docker wrapper to use HTTPS link.
Updates copyright year to 2018
**Please review and check the following**:
finished (i.e. no ``[WIP]`` tag remains in the title of my PR) and tests pass.
[coding style](https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md#fmriprep-coding-style-guide),
to the extent I understood them (and I will address any comments raised by the PR's reviewers in this regard).
> DOC: Update copyright year to 2018

- fmriprep/interfaces/images.py
- fmriprep/interfaces/tests/test_images.py
`nipype.interfaces.nilearn.SignalExtraction` has been a consistent pain point for users with large BOLD series, resulting in the creation of the `--low-mem` flag (#663) to reduce its memory usage by saving an uncompressed copy of its inputs, thus enabling loading data on an as-needed basis via `mmap`.
This is a proof-of-concept for a pure nibabel replacement. I haven't included all of the options that the nilearn interface presents, but it does handle our use case.
The heart of it is this:
```Python
series = np.zeros((img.shape[3], n_masks))
data = img.get_data()
for j in range(n_masks):
series[:, j] = data[masks[j], :].mean(axis=0)
```
The reason I treat time series as the basic unit rather than volumes is that Nifti images are row-major, so each time series is contiguous in memory, …
> RF: Reimplement SignalExtraction

- .gitignore
- docs/installation.rst
De-indent to remove text from code block. Noticed this when verifying that #1237 was hitting ReadTheDocs.
First note in [Running a Singularity Image](https://fmriprep.readthedocs.io/en/latest/installation.html#running-a-singularity-image).
finished (i.e. no ``[WIP]`` tag remains in the title of my PR) and tests pass.
[coding style](https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md#fmriprep-coding-style-guide),
to the extent I understood them (and I will address any comments raised by the PR's reviewers in this regard).
> DOC: De-indent to remove text from code block

- CONTRIBUTING.md
- docs/pull_request_template.md
As the guidelines are intended for the PR submitter, and not the reviewer, I added them to the comments, and changed the section name to "Pull request agreement".
Additionally, I made the final checklist item something everyone can check. This will avoid the "3 of 4" items complete indicator in the pull request list.
finished (i.e. no ``[WIP]`` tag remains in the title of my PR) and tests pass.
[coding style](https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md#fmriprep-coding-style-guide),
to the extent I understood them (and I will address any comments raised by the PR's reviewers in this regard).
> [MAINT] Update PR template

- fmriprep/__about__.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/bold/resampling.py
- requirements.txt
niworkflows 0.4.3 broke downloading, so all builds will fail until this is resolved. Since #1270 may not go in as quickly as needed, I've rebased the template fixes to their own branch.
> FIX: Accommodate new template formats

- fmriprep/__about__.py
- fmriprep/cli/run.py
In the current logic, `--use-plugin` overrides `--nthreads` and `--mem-mb` options, even if not set. This PR allows `--use-plugin` to define resource constraints, but also allows these CLI options to override them.
Further, it was reported by @poldrack that `--use-plugin` results in a failure to `import yaml` in the Singularity image. This PR also adds PyYAML to the install requirements.
* Load plugin config before setting thread/memory constraints
* Require PyYAML
No relevant changes.
> FIX: Permit overriding plugin config with CLI options

- docker/scripts/get_templates.sh
- docs/workflows.rst
- fmriprep/cli/run.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/util.py
For each BOLD file, this approach finds the associated `sbref` file, if available, and passes it to `EstimateReferenceImage`.
One hangup here is that we need to validate both the bold file and sbref if available. To avoid weird conditionals, I put a second, post-reference-estimation validation step. If the image is estimated from the BOLD series, it should have no effect. If the sbref is returned, it will get the same treatment as the BOLD series did prior to estimation.
An alternative approach would be to generate the reference image, and then validate both the BOLD series and the reference image afterwards. I don't think it would make any computational effects (unless the reference process implicitly depends on good affine codes), but it might be a little easier to understand for future …
> ENH: Use single-band reference images when available

- Dockerfile
- docs/workflows.rst
- fmriprep/workflows/bold/__init__.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/registration.py
As discussed with @effigies, splits the existing `bold_reg_wf` into two separate, smaller workflows, one of which calculates the registrations and the other of which applies the result in a single-shot. This will make integration of ME-EPI workflow changes possible.  
Updated docstrings for both of the new functions.
> [RF] Split BOLD-T1w registration into calculation/application workflows

- fmriprep/cli/run.py
9 degrees of freedom for bbregister can result in pretty dramatic stretches. The purpose of using 9 DoF was to account for field inhomogeneities causing stretching or shrinking. However, it's been decided this relatively rare case is better handled by the user manually specifying 9 DoF.
* Set 6 DoF BOLD-T1w registration by default.
> FIX: Default to 6 DoF for BOLD-T1w registration

- fmriprep/workflows/bold/base.py
* Add `extensions` key in `layout.get` when retrieving sbref files.
See https://neurostars.org/t/fmriprep-bet-threshold/1486/15
> FIX: Only grab sbref images, not metadata

- fmriprep/workflows/fieldmap/pepolar.py
In a cleanup in nipy/nipype#2674, `QwarpPlusMinusInputSpec.source_file` got renamed to `in_file`, to be consistent with the `Qwarp` interface. Apparently the deprecation machinery doesn't set the values in the new location, causing #1287.
* Change source_file to in_file
Fixes #1287.
None
> FIX: QwarpPlusMinus renamed source_file to in_file

- docs/workflows.rst
Following discussion in [this NeuroStars thread](https://neurostars.org/t/fmriprep-correction-of-surface-extracted-from-freesurfer-anat-only/2428/13), a clarifying note seems necessary.
Updated documentation.
* Add a note with the following text:
```RST
GIFTI surface outputs are aligned to the FreeSurfer T1.mgz image, which
may differ from the T1w space in some cases, to maintain compatibility
with the FreeSurfer directory.
Any measures sampled to the surface take into account any difference in
these images.
```
> DOC: Note GIFTI surface alignment

- CHANGES.rst
- fmriprep/__about__.py
* Updates changelog, including release notes for last several releases.
* Bumps nipype dependency to 1.1.3, to work properly with #1289.
> REL: 1.1.7

- .circleci/config.yml
- fmriprep/workflows/bold/tests/test_util.py
- fmriprep/workflows/bold/util.py
Pass `enhance_t2` flag from `init_bold_reference_wf` to `init_enhance_and_skullstrip_wf`.
This parameter currently does nothing. It appears to have been an oversight in #966.
None.
> [FIX] Enhance T2 contrast ``enhance_t2`` in reference estimate

- fmriprep/workflows/anatomical.py
#925 switched from `StructuralReference` to `fs.RobustTemplate`, under the reasoning that a single T1w image could be caught at workflow construction time. However, the conformation process can remove images that would need to be upsampled too much, leaving only a single T1w image to produce a template from. In this case, we need to simply pass through the original image.
* Restore `t1_merge` to `StructuralReference`.
None.
> [FIX] Create template from one usable T1w image

- fmriprep/viz/reports.py
Fix for error in generate_report function encountered when running singularity image of fmriprep version 1.1.8 on a cluster, with singularity version 2.6.0 raised in issue #1313.   
Fixes #1313.
The flag encoding='UTF-8’ was added for all read_text and write_text functions.
> [FIX] Ensure encoding when reading boilerplate

- .circleci/config.yml
- .circleci/ds005_outputs.txt
- .circleci/ds005_partial_outputs.txt
- fmriprep/workflows/bold/base.py
> [TST] Fix expectations for CIFTI outputs & ds005

- docs/workflows.rst
- fmriprep/interfaces/confounds.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
ref #1136
ref #1300
This pull request pulls the steady state detector into `bold/base.py` and uses it's output for both the confounds workflow and the aroma workflow.
I need to update the documentation for ica-aroma, more details to come...
> [FIX] Remove non-steady-state volumes prior to ICA-AROMA

- .circleci/config.yml
- .circleci/ds005_outputs.txt
- .circleci/ds005_partial_outputs.txt
- fmriprep/interfaces/confounds.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
Updating confounds headers to match the RC2.
Known remaining tasks:
Anywhere we discuss confounds. I believe we have example confounds that should be fixed, as well.
> ENH: Conform confound regressor names to Derivatives RC2

- fmriprep/cli/run.py
1.2.1 shows the following, regardless of whether `--debug` was passed:
```
YYMMDD-HH:MM:SS,75 nipype.workflow WARNING:
Option --debug is deprecated and has no effect
```
This is because it stores `False` by default, not `None`.
None.
> FIX: Do not show --debug deprecation warning unless used

- .circleci/config.yml
- .circleci/legacy.yml
- fmriprep/__about__.py
- wrapper/fmriprep_docker.py
* Add a `legacy.yml` plugin configuration to the Circle directory
* Run full ds005 with `LegacyMultiProc`
* Upgrade to nipype>=1.1.5
Closes #1363.
> TEST: Verify LegacyMultiProc functionality

- docs/workflows.rst
- fmriprep/cli/run.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/tests/test_base.py
The proposed change to the documentation explains how to set a flexible upper limit for the number of ICA components extracted by MELODIC in the ICA-AROMA workflow. See #1051 
Default fmriprep behavior is changed to automatic dimensionality estimation limited to a maximum of 200 components.
`docs/workflows.rst`
describes the new default behavior and points to 
`fmriprep/workflows/bold/confounds.py`
for further details.
> [ENH] Set maximum MELODIC components to 200 by default

- .circleci/config.yml
- Dockerfile
- docker/scripts/get_templates.sh
- docs/environment.yml
- fmriprep/__about__.py
- fmriprep/workflows/anatomical.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/resampling.py
- requirements.txt
* Pulls in fix from poldracklab/niworkflows#258.
* Stole large portions of #1334 to handle updates to templates
* Ignores CLI modifications and their consequences
* Ignores changes to ROIsPlot (for now)
Fixes #1365.
Based on #1368 to avoid merge conflicts.
> [FIX] Count non-steady-state volumes even if sbref is passed

- fmriprep/interfaces/cifti.py
The indexing of the cortical structure name after the split was taking the first letter of 'LEFT' (L) or 'RIGHT' (R) and then comparing it to 'RIGHT' a few lines below to select the proper hemisphere (which was then always False). This resulted in LEFT and RIGHT cortical hemisphere BOLD time series being identical, it now compares the whole word and the output is consistent.
No need for changes in doc.
> [FIX] Correctly populate right-hemisphere time series in CIFTI derivatives

- fmriprep/workflows/anatomical.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/tests/test_util.py
The ``ROIsPlot`` interface was modified in poldracklab/niworkflows#257
to enable a ``levels`` input, slightly improving its API.
This PR basically brings the plots in the reports back to their original
colors.
> [FIX] Restore original contour colors in reports

- Dockerfile
- docs/environment.yml
- fmriprep/__about__.py
- fmriprep/cli/run.py
- fmriprep/utils/misc.py
- fmriprep/viz/report.tpl
- fmriprep/viz/reports.py
- fmriprep/workflows/bold/confounds.py
- requirements.txt
- Supersedes #1375 and closes #1367
- Fixes an issue with parsing crashfiles of Function interfaces
- Switches to the new sentry SDK (closes #1380) which is graceful when network is down (closes #1202)
- Logs sentry errors when stop on first crash is not enabled
- Improves grouping of sentry errors (closes #1362)
- Makes final message more explicit when errors were detected
- Minor tweaks in formatting errors in HTML reports
> [ENH] new sentry SDK

- fmriprep/cli/run.py
Fixes two issues:
- If you build a container from master `__version__` is set to `''` - this was tripping Environment assignement
- `fMRIPrep finished without errors` was being sent if errors without crash files (KeyboardInterrupt for example) occurred
> Sentry refinement

- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/t2s.py
For MEEPI, changes the T2* map target from the adaptive to the standard T2* map. This updates the coregistration target in the case of `--t2s-coreg` and seems to produce more consistent alignment.
I have also updated the docstring for the `t2s_coreg` argument in all relevant workflows and updated the workflow description for `bold_t2s_wf`.
The workflow description will need review to ensure its correctness.
> [ENH] Use standard T2* map as coregistration target

- fmriprep/interfaces/bids.py
- fmriprep/workflows/base.py
* Add run UUID to FreeSurfer subjects directory preparation node, to avoid multiple instances with a shared working directory from interfering with one another.
* Catch `FileExistsError` from `shutil.copytree` to ensure that parallel runs don't cause crashes when racing on `os.path.exists`.
Closes #1410.
> ENH: Handle FreeSurfer subject directory preparation gracefully when run in parallel

- fmriprep/cli/run.py
- fmriprep/viz/reports.py
- fmriprep/workflows/bold/hmc.py
This update builds on top of #1418 and adds fingerprint propagation for certain events. In other words, if say memory error was raised during a run all events raised for that run will be marked as memory errors. This should limit noise and group side effects with common causes.
> [ENH] Sentry event categorization propagation

- .circleci/ds005_outputs.txt
- .circleci/ds005_partial_outputs.txt
- .circleci/ds054_outputs.txt
- .circleci/ds210_outputs.txt
- .zenodo.json
- fmriprep/cli/run.py
This PR is in response to #1444 
It copyies the `boilerplate.bib` file to logs folder together with other CITATION files as `CITATION.bib`, using `shutil.copyfile`.
> [ENH] Copy BibTeX file to log directory for LaTeX users

- docs/environment.yml
- fmriprep/__about__.py
- fmriprep/interfaces/patches.py
- fmriprep/viz/config.json
- fmriprep/workflows/bold/confounds.py
Reverts poldracklab/fmriprep#1443
> Revert "[MRG] FIX: Output NaN columns for CompCor on failure"

- fmriprep/cli/run.py
Check that `/proc/1/cgroup` exists before attempting to read it.
Fixes #1453.
> FIX: Verify proc file exists before reading

- fmriprep/cli/run.py
This warning would still happen even if we do not print the boilerplate out (which was planned to be done).
> [FIX] Avoid warning when generating boilerplate

- fmriprep/__about__.py
> Fix a bug where a crashing `before_send` would crash the SDK and app.
> [MAINT] Update sentry-sdk

- Dockerfile
No real way to test this until merged, built and pushed to `poldracklab/fmriprep:unstable` to build a Singularity image off of.
Fixes #1500.
> FIX: Set TemplateFlow directory world-writeable

- fmriprep/interfaces/reports.py
- fmriprep/workflows/bold/base.py
Closes #1425. Small change that adds the repetition time to the functional reports. 
(Was looking how the reports were generated and added it).
> [ENH] Include repetition time in functional summary

- docs/installation.rst
This PR will address https://github.com/poldracklab/fmriprep/issues/1488 and https://github.com/poldracklab/fmriprep/issues/1129. This PR provides additional documentation to fmriprep-docker
Provided documentation to fmriprep-docker
> [DOC] fmriprep-docker documentation

- fmriprep/viz/config.json
In reference to this issue: https://github.com/poldracklab/fmriprep/issues/1538.
Added the text "_Note that Nearest Neighbor interpolation is used in the reportlets in order to highlight potential spin-history and other artifacts, whereas final images are resampled using Lanczos interpolation_" to lines 105, 111, 117, and 123 of /fmriprep/viz/config.json
> [DOC] Indicate that interpolation is NN above the EPI-to-T1w reportlet

- fmriprep/viz/reports.py
Closes #1551.
Tested - results at https://sentry.io/organizations/poldracklab/issues/944343769/?environment=dev&project=1137693&statsPeriod=14d&utc=false
> [ENH] Group all 'finished running with errors' sentry messages

- fmriprep/workflows/bold/base.py
This PR checks that ``template`` is in the output spaces list, skipping the connection to datasinks of workflows resampling the BOLD in MNI.
In particular, we were getting (see #1348):
```
AttributeError: 'DynamicTraitedSpec' object has no attribute 'bold_mni_ref'
```
When forwarding the IdentityInterface of the derivatives data sink because it wasn't included within the input fields.
> FIX: Not having ``template`` as one ``--output-space`` crashes fMRIPrep

- .zenodo.json
- fmriprep/cli/run.py
- makes it friendly to the cases where all output is under git-annex.
.write_text() just opens a file in "w" mode so it would fail on
annex protected file.
- if previous run did succeed generating e.g. .html file, if subsequent run
fails, updated version of .html would not be generated and provided
CITATION files could get out of sync.
Removing all  relevant `CITATION*` files prior generation resolves both of the issues.
No pressure -- if you don't like it just close it.
Comes not tested whatsoever ;-) (are there unittests to run for it?)
> ENH: remove all prior existing citation files first

- CONTRIBUTING.md
fixes #1565 
- add example pull requests to each type (e.g. `STY`, `DOC`, `ENH`, etc)
- add link to add/commit/push files
- change pull request link to forked repositories (since that is the workflow that fmriprep promotes)
- add a cloning step (so contributors have explicit instructions on how to clone the repository)
The CONTRIBUTORS.md file
@ariveradompenciel could you see if this updated [CONTRIBUTING.md](https://github.com/jdkent/fmriprep/blob/contrib_clarity/CONTRIBUTING.md) addresses your suggestions?
@effigies, @oesteban, @emdupre :  I do not know what `RTM` means (it's not Read The Manual), sorry I'm not keeping up with the lingo. But I would like to add an entry for that, which I can do as soon as I know what it means.
> [DOC] add examples/clarify CONTRIBUTORS.md

- fmriprep/__about__.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/util.py
- requirements.txt
Part of #1511. Addresses #1579 and #1463.
> FIX: Support 4D SBRefs when generating the bold reference

- fmriprep/cli/run.py
> ENH: Do not allow writing derivatives directly into the BIDS root folder

- .circleci/config.yml
- .zenodo.json
Fixes #1563 
Changed echo "Skipping pytest job" to "Skipping doc building job"
N/A
> [CI] Fix label on CI step "Skipping doc building job"

- wrapper/fmriprep_docker.py
When ``$HOME`` was changed to ``/home/fmriprep`` for Docker images I
missed updating the mount point of the wrapper.
This PR addresses that issue.
> FIX: Mount Nipype config file under new ``$HOME``

- fmriprep/workflows/bold/base.py
* Add `compress=True` to all volumetric BOLD `DerivativesDataSink`s to ensure that we always produce `.nii.gz` files.
Related: poldracklab/smriprep#80, #1555, poldracklab/niworkflows#356.
> ENH: Force compression of derivative NIfTI volumes

- .circleci/config.yml
This one is fiddling with Circle caches, which we persist anyway, to pass data between jobs. Saving to cache seems to be slightly faster than persisting to the workspace, so this:
1) De-duplicates saving cached/workspace data, choosing the cheaper option.
2) Eliminates the separate `update_cache` job, which persists, reloads and then caches.
The savings of the save/load steps seems to be within the variance of the whole job, so I'm not sure that we'll see much of a speed up (I expect the effect is there, but ~2 minutes in 30-70 minute jobs is not much to brag of. That said, this does eliminate a 7 minute job.
I also experimented with reducing the compression level to 3 and only using 2 threads, and that appears to shave 3-5 minutes off of the save step while not significantly adding to …
> CI: Use caches to pass data between jobs

- fmriprep/utils/bspline.py
Was looking at the `maths.pyx` thing to see about splitting it out into its own package. Noticed some `get_data()` uses in `BSplineFieldmap`. `get_data()` is supposed to be being deprecated any day now... and the two calls to it are sub-optimal.
The first can just be replaced by the image shape, which is just read from the header and doesn't require loading the data.
The second can use `get_fdata`, and if we use `caching='unchanged'`, then it won't store a copy of the array internally, so it can get garbage-collected after filling `_data`.
I don't expect this is going to have a significant effect, but just while I was there.
> ENH: Reduce BSplineFieldmap memory usage

- .circleci/config.yml
Two very small optimizations.
* Use busybox for "deployable" to make as short as possible
* Do not run PyPI tests on docs/ branches
> CI: Reduce pointless expenditures

- fmriprep/workflows/bold/resampling.py
This PR fixes #1626.
The ``transforms`` input to ``MultyApplyTransforms`` had not been
updated to get fed by the ``KeySelect`` interface that demultiplexes
parameterized fields.
With great thanks to @markushs for his invaluable help catching this.
> FIX: Resolve resampling of BOLD into standard spaces

- fmriprep/workflows/bold/base.py
Fixes #1630.
This PR resolves the situation where the derivatives data sinks received
parameterized inputs from two sources of iterables, with overlapping
names.
> FIX: Writing functional derivatives in standard spaces

- fmriprep/workflows/bold/resampling.py
This PR addresses a problem dual to #1630 and closes #1631. The transforms being fed to the resamplers were not being `KeySelect`ed.
> FIX: Incorrect transforms being applied to aparc/asegs in standard space

- .circleci/config.yml
- docs/workflows.rst
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/resampling.py
> FIX: FreeSurfer without adding some ``fs*`` to ``--output-spaces``

- .circleci/config.yml
- .circleci/ds054_outputs.txt
- docs/spaces.rst
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/outputs.py
This PR enables writing data resampled after STC-HMC-SDC in their
original BOLD grid.
Closes #1376.
> ENH: Write outputs in native-BOLD space

- .circleci/config.yml
- Dockerfile
Setting ``$TEMPLATEFLOW_HOME`` within the image [precludes overwriting the variable via ``$SINGULARITYENV_`` exports](https://github.com/sylabs/singularity/issues/2892#issuecomment-500104786).
Additionally, it seems that in some systems (e.g., Sherlock), bound directories do not replace existing directories. That, in practice, led to permission errors when the templates are not pre-cached.
Leaving ``$TEMPLATEFLOW_HOME`` unset will make TemplateFlow use the default path (``$HOME/.cache/templateflow``), which in many systems will be automatically bound and writable.
Therefore, there is little point in setting the variable. This PR also avoids pulling atlases into the Docker image.
> FIX: Do not set ``TEMPLATEFLOW_HOME``

- fmriprep/cli/run.py
- fmriprep/workflows/bold/base.py
Close #1536
A quick fix to alert users that phase1/2 correction is not yet available.
None
> ENH: Show informative warning for phase1/2 type of fieldmaps

- fmriprep/workflows/bold/base.py
This PR will resolve #1675, which fails to identify a template to be used for SDC normalization when no template is specified as an output space.
I'm beginning with the portion that raises the exception, which is simply failure to find an object in an empty container. It may be that doing this is insufficient to ensure that a normalization to the default template is found, and further work will be needed.
> FIX: Use MNI152NLin2009cAsym for SDC if no templates are specified

- fmriprep/cli/run.py
This PR addresses the memory peak caused by pandoc, running the process
at the very end of fMRIPrep.
We probably want to explicitly clear up as many objects as we can from
memory and force gc before the subprocess opens pandoc, but that's left
for a future PR.
This PR just closes #1709 with the delayed pandoc run. I'm not
implementing the flag to avoid the boilerplate generation because I'm
not sure we want to introduce an additioinal argument for this.
Coincidentally, it also closes #1667 - now the deletion of citation
files is done inside a try..catch where ``FileNotFoundError`` is
dismissed. That should avert the issue, while keeping the functionality
of #1567.
Individual reports should keep rendering exactly the same after this PR.
> FIX: Postpone ``pandoc`` conversion of boilerplate after workflow has fully run

- fmriprep/cli/run.py
Use ArgumentDefaultsHelpFormatter so that defaults are printed with --help
I don't consider this work complete, because a substantial number of the options listed in the argument parser don't provide a default value which should.
> ENH: Make fmriprep print defaults for arguments with help

- setup.cfg
Closes #1674.
Addresses [Neurostars #4771](https://neurostars.org/t/naming-of-bids-events-tsv-files-seems-to-disrupt-fmriprep-1-5-0rc1/4771).
> MAINT: Bump pybids and nipype dependencies

- .circleci/config.yml
- Dockerfile
- fmriprep/workflows/bold/base.py
Ensure only volumetric templates are passed as indexing keys into the
carpetplot-creation workflow. Fixes #1721.
> FIX: Passing surface template keywords into carpetplot workflow

- Dockerfile
- fmriprep/interfaces/confounds.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- setup.cfg
* Resolves #1617 
* Resolves #1618
> ENH: Confounds metadata

- .circleci/config.yml
Switches to `circleci/python:3.7.4` for building packages on, as this should have a long lifetime before we need to upgrade it.
The latest twine breaks Python 3.5 but still installs on it, so our current strategy fails. We could pin an older twine, but there doesn't seem much value.
@oesteban I see we're still using manylinux to build wheels. I believe we no longer need that?
> CI: Use recent Python image to build packages

- fmriprep/cli/run.py
> FIX: Ignore sourcedata and derivatives when fetching data

- fmriprep/workflows/bold/base.py
add comma to outputnode of init_func_preproc_wf
In defining the outputnode of init_func_preproc_wf there is a comma missing resulting in a wrong outputnode. I just added the comma.
#1794 
None
> [FIX] Adding comma to outputnode in init_func_preproc_wf

- README.rst
- docs/_static/sbatch.slurm
- docs/citing.rst
- docs/conf.py
- docs/contributors.rst
- docs/docker.rst
- docs/faq.rst
- docs/index.rst
- docs/installation.rst
- docs/license.rst
- docs/links.rst
- docs/singularity.rst
- docs/spaces.rst
- docs/usage.rst
This PR addresses #1801. The intent is to provide clearer documentation about how to run fMRIPrep via Singularity containers. In particular, the interaction between TemplateFlow and Singularity should be better described.
> DOC: Improve documentation about TemplateFlow and Containers

- .circleci/config.yml
Addresses #1835 trying to get lucky (as python version is the most significant change w.r.t. to the latest successful build).
> MAINT: pin python 3.7.4 in circle's build_docs

- .circleci/config.yml
- fmriprep/cli/tests/test_version.py
- fmriprep/cli/version.py
Adds a bugfix and a test-case. Close #1777.
> FIX: Error during version check trying to access read-only file systems

- Dockerfile
- fmriprep/workflows/bold/confounds.py
Requires a customized release of ICA-AROMA from @oesteban's user, until
maartenmennes/ICA-AROMA#43 gets merged.
Fixes #1833.
> FIX: Skip plotting step of  ICA-AROMA

- .circleci/ds005_outputs.txt
- .circleci/ds005_partial_outputs.txt
- fmriprep/workflows/bold/outputs.py
This PR removes the connection of the ``template`` identifier (which is an _iterable_ and is propagated as such by nipype's default behavior) to the ``space`` input of the data sink.
Following nipype's execution rules, the same input was copied over each time for each input at the ``template`` iterable. So, the same data were written over and over again with different space value. In other words, this PR *does not* address #1766. It just improves the clarity as only one conversion is generated.
Since ``desc-smoothAROMAnonaggr_bold`` is calculated always on ``MNI152NLin6Asym`` the keyword is not necessary anymore for disambiguation. I have concerns about whether removing it completely is a good idea (although BIDS-Derivatives mandated, I guess). WDYT?
> FIX: Do not generate ``desc-smoothAROMAnonaggr_bold`` conversions on standard spaces

- .circleci/ds005_outputs.txt
- .circleci/ds005_partial_outputs.txt
- fmriprep/workflows/bold/outputs.py
Brings the space keyword back as suggested in https://github.com/poldracklab/fmriprep/pull/1838#issuecomment-543758805
> ENH: Restore ``space-MNI152NLin6Asym`` for AROMA denoised outputs

- Dockerfile_devel
Solves issue #1851. Apparently there was an older version of CodeServer that does not exist anymore.
- Updated the URL
- Added in the ENTRYPOINT  "--auth none" parameter to avoid random password generation and identification for the CodeServer
Tried the same commands of the docs, they worked.
> FIX: Update code-server in the Dockerfile_devel

- .circleci/artifact_path
I've enabled Eric Larson's [circleci-artifacts-redirector](https://github.com/larsoner/circleci-artifacts-redirector) to make it easier to immediately open the rendered docs. This change tells it where to find the artifacts.
> MNT: Enable circleci-artifacts-redirector

- README.rst
Removes mention of OpenNeuro. This was mostly already done, but the badge was still left over.
> DOC: Remove OpenNeuro badge

- docs/workflows.rst
ref #1804, specifically [this comment](https://github.com/poldracklab/fmriprep/issues/1804#issuecomment-550417076)
- `docs/workflows.rst`: changed names of files.
> [FIX,DOC] change ica-aroma filenames to fit current naming scheme

- fmriprep/cli/run.py
This PR workarounds the issue of pandoc running out of vmem at the end of the fmriprep pipeline which then terminates the workflow on our HPC environement. #1870 
Here is Neurostart discussion about this issue.
> https://neurostars.org/t/large-virtual-memory-allocations-in-fmriprep-on-pbs-system/4665/8
Our workflow doesn't just run a single fmriprep, so if fmriprep fails at the end, it will kill the entire workflow. For us, it's important that fmriprep survives the post-processing. The memory issue with pando has been a known issue since 2016 according to this thread (https://github.com/jgm/pandoc/issues/3169) ..
> Added skip_citation_process flag to skip processing citation.md

- docs/sdc.rst
- fmriprep/cli/run.py
- fmriprep/data/reports-spec.yml
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/fieldmap/__init__.py
- fmriprep/workflows/fieldmap/base.py
- fmriprep/workflows/fieldmap/unwarp.py
- setup.cfg
> ENH: Upgrade SDCFlows to new API (1.0.0rc1)

- fmriprep/workflows/bold/base.py
Currently, the BIDS-Validator would just raise a Warning when metadata contains:
```
{
"SliceTiming": []
}
```
> FIX: Do not run STC if SliceTiming metadata is set but empty

- .circleci/config.yml
- fmriprep/cli/run.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- wrapper/fmriprep_docker.py
Closes #1898 
- removes deprecated `fmriprep` arguments:
```
--ignore-aroma-denoising-errors
--debug
--output-space
--template
--template-resampling-grid
--no-freesurfer
```
- removes deprecated `fmriprep-docker` arguments:
```
--template-resampling-grid
--output-grid-reference
```
- adds `--output-spaces` argument to `fmriprep-docker` to allow custom template usage
> MAINT: Remove deprecated command-line arguments

- docs/outputs.rst
This PR addresses further issues after #1877:
- Address warnings 2) and 3) of #1049, and I've opened #1905 to follow up conversations
- Add documentation about DCT regressors, close #1167.
- Address items 2) and 3) of #1521.
> DOC: Refinement of confounds documentation after #1877

- docs/citing.rst
Trying to solve #813 
There are a pair of issues:
- Annoying 1 (one) after the 2 (two). The first "one" comes from the citation itself. 
`2. *1.* Esteban, Oscar, Blair, Ross(...)`
Solved with `citation.substring(2)`
- Read the docs always serves the latest Zenodo DOI
In [this](https://github.com/poldracklab/fmriprep/blame/278fb84c5407520cdbcc7228c8bcbe8f82d19c6c/docs/citing.rst#L16) line, there's this assignment `var version = 'latest';`. If assigned to the desired version, it changes and works adequately. I guess this can be obtained from the HTML? I've no experience with javascript, I'll give it a try though.
> FIX: Read the docs always serves the latest Zenodo DOI

- wrapper/setup.cfg
As of setuptools 45, our `fmriprep-docker` invocations on CircleCI are emitting:
```
/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pkg_resources/py2_warn.py:19: UserWarning: ************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release. Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
```
This should suppress this warning without affecting Python 3 installations.
> FIX: Constrain setuptools for Python 2.7 (wrapper)

- fmriprep/__main__.py
This helps in confused environment situations, as `python -m fmriprep` uses Python module loading to locate the executable instead of the shell's `$PATH`. Also for cases like `coverage run -m fmriprep` on an installed copy instead of a source directory.
> ENH: Add fmriprep.__main__ to allow python -m fmriprep

- CHANGES.rst
- setup.cfg
The plan is to just push this commit to `maint/1.5.x` and release once sMRIPrep gets pushed to PyPI. Probably in the morning (hence the date).
Opening this PR just to give a chance to object or suggest other bug fixes we should hold off for.
> REL: 1.5.7

- docs/faq.rst
- docs/outputs.rst
- docs/workflows.rst
Build docs is breaking with 
```
Warning, treated as error:
/tmp/src/fmriprep/docs/faq.rst::Could not obtain image size. :scale: option is ignored.
```
Warning introduced in https://github.com/sphinx-doc/sphinx/pull/6985. Unclear whether it's supposed to work or the warning is just added. Either way, if it wasn't working before, removing it shouldn't cause new problems.
Affected files:
* [FAQ](https://11700-53175327-gh.circle-artifacts.com/0/tmp/src/fmriprep/docs/_build/html/faq.html)
* [Outputs](https://11700-53175327-gh.circle-artifacts.com/0/tmp/src/fmriprep/docs/_build/html/outputs.html)
* [Workflows](https://11700-53175327-gh.circle-artifacts.com/0/tmp/src/fmriprep/docs/_build/html/workflows.html)
> DOC/FIX: Remove unusable scale option to SVG figures

- fmriprep/cli/run.py
Closes #1763 
The `cli` logger did not have an attached `Handler`, so logs that should have been displayed were not.
> FIX: Ensure logs are properly displayed

- .circleci/config.yml
- Dockerfile
- wrapper/fmriprep_docker.py
Let's reduce the odds of #1995 coming up again. 
* Adds a `--network` option to `fmriprep-docker` that allows us to pass the `--network` option to Docker
* Set `--network=none` for ds005, which uses AROMA, SyN-SDC, and outputs to a number of spaces including HCP-style CIFTI.
Hopefully this will fail, and then will pass with #1996 in.
> CI: Test that Docker image can run a common set of output spaces without network access

- docs/_static/sbatch.slurm
- docs/faq.rst
- docs/usage.rst
> DOC: add --fs-subjects-dir usage to slurm example

- fmriprep/cli/run.py
- fmriprep/workflows/base.py
Closes #2011 
This adds new options to the `--ignore` flag, allowing users to avoid using T2w/FLAIR images during FreeSurfer processing.
> ENH: Add t2w/flair as potential --ignore targets

- .circleci/config.yml
- .travis.yml
- docs/installation.rst
- docs/license.rst
- fmriprep/__about__.py
- setup.cfg
- wrapper/fmriprep_docker.py
also removes a python 2 test of the docker wrapper, and bumps licenses up a year
> MAINT: Bump to 3.7+

- wrapper/fmriprep_docker.py
This PR re-enables use of custom templates after the output spaces refactoring.
The local directory where the custom template exists is now mounted to the TemplateFlow home within the container.
Related issue: https://neurostars.org/t/custom-template-fmriprep-20-0-1/6232
> FIX: Properly mount local templates

- setup.cfg
Based on a conversation in https://github.com/nipy/nipype/pull/3180, it seems prudent to pin to minor series of nipype. Nipype is on bug-fix-only patch releases. This fits well with our proposed rules for minor release series. Upgrading the nipype pin to a new minor release series would only be valid in minor releases of fMRIPrep.
I also pinned nibabel 3.0. Nibabel has very strict backwards-compatibility constraints within a major version series, so upgrading to a new minor release should not introduce any concerns even in bug-fix releases.
We might want to consider assessing other dependencies. With the prospect of long-term releases, unpinned dependencies become riskier.
> MNT: Pin minor series of nipype, major of nibabel

- docs/workflows.rst
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- setup.cfg
In particular, poldracklab/fmriprep#167 introduces a few changes that need to be considered before #1829 is merged:
- The new `skull_strip_mode` argument for the anatomical workflow (poldracklab/smriprep#167)
- The functional workflow does not require parameterized inputs
- The anatomical workflow no longer produces a brain-masked conversion of the T1w.
> ENH: Adapt fMRIPrep to upcoming sMRIPrep API changes

- docs/faq.rst
- fmriprep/cli/run.py
#2027, one stab at it.
Added a few lines to the Usage Notes as an example of input to `--bids-filter-file`. Took me a while of digging through pybids to figure out how to set the `config.json` up properly; I think that it would be useful to link to an example like that in the discussion of #1770, but couldn't figure out where to put it.
Usage Notes - Positional arguments - bids-filter-file
> DOC: BIDS filter input example

- docs/workflows.rst
- fmriprep/cli/parser.py
- fmriprep/config.py
- fmriprep/workflows/base.py
Supersedes #1829.
@adelavega can you check locally this works for you?
> ENH: Add a ``--skull-strip-t1w`` argument to skip brain extraction

- fmriprep/data/reports-spec.yml
- fmriprep/interfaces/confounds.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
Closes #2026 
Uses BOLD CIFTI file to generate carpetplot when available
Depends on nipreps/niworkflows#491
> ENH: Use CIFTI for carpetplot when available

- fmriprep/cli/parser.py
- fmriprep/config.py
This restores the default value of` omp-nthreads` based on `n-cpus` established in #500 and removed in #2018.
Fixes #2070.
> FIX: Restore omp-nthreads calculation

- fmriprep/interfaces/confounds.py
* Resolves #2062 .
* Using example MELODIC reports, I was able to figure out that the first column of the `melodic_ICstats` file records the fraction of the model variance explained.
* The second column records the fraction of the total variance explained.
* I am not able to discern what the third and fourth columns record, but adding those metadata should be an easy change if we can figure this out.
> (enh) add fraction of variance explained by ICA-AROMA components to metadata

- fmriprep/interfaces/reports.py
Clears the clutter of a long list of headers in the ``_regressors.tsv`` file, by inserting it in a foldable (`<details></details>`) HTML environment.
For consistency, the Summary header and other details have also put together into another details class, in this case always open.
Just check out the aesthetics of the new reports.
> ENH: Fold the list of collected confounds

- wrapper/fmriprep_docker.py
While testing the wrapper, I realize we don't make it easy to patch all our "in-house" dependencies.
This PR removes package specific `--patch-x` calls and instead adds a new argument, `--patch`, which supports one or more key value pairs of package, package path.
For example:
```
fmriprep-docker ... --patch fmriprep=/code/fmriprep/fmriprep smriprep=/code/smriprep/smriprep
```
> ENH: add options to patch in other dependencies

- fmriprep/cli/parser.py
- fmriprep/cli/run.py
- fmriprep/config.py
~~This PR sets and tracks `ANTS_RANDOM_SEED` environmental for increased run-to-run reproducibility. By default, this value is set to a string representation of the current date in `YYYYMMDD` format. Additionally, a parser option `--ants-fixed-seed` is added to allow manually setting this option.~~
This PR adds a new section to the config, *seeds*, that tracks and sets random seeds. Firstly, a master seed is generated, or can be passed in via the new `--random-seed` argument. This seed initiates the PRNG and reproducibly generates program specific seeds. ANTs is the only seed currently tracked.
NOTE: `ANTS_RANDOM_SEED` is only used for some ANTs interfaces (https://github.com/ANTsX/ANTsR/issues/210#issuecomment-538812296)
> ENH: Keep track and allow reuse of random seeds with the config module

- fmriprep/config.py
- fmriprep/workflows/bold/base.py
Proposing in case this is the correct fix.
* FIX: Rename use_syn config option to use_syn_sdc to match CLI
Closes #1941 (again).
> FIX: Rename use_syn config option to use_syn_sdc to match CLI

- wrapper/fmriprep_docker.py
Should partially remedy the problem in #2103, #2098 
In the case where an output directory did not exist, `docker run` was tasked with creating the output directory, leading to potential permission problems when running as non-root. This PR creates the nonexistent directory within the wrapper, prior to the docker command.
Also adds in GID remapping information to the parser help string.
> MAINT: create output folder prior to docker run

- setup.cfg
This bumps the minimum templateflow to [0.6.0](https://github.com/templateflow/python-client/releases/tag/0.6.0), which includes an automatic update mechanism to update the local template skeleton.
This should reduce the burden of having to update the python templateflow client every time a change has been made to the skeleton.
> MAINT: bump templateflow to auto-update skeleton

- fmriprep/cli/parser.py
- fmriprep/cli/run.py
- fmriprep/cli/tests/test_parser.py
- fmriprep/cli/tests/test_version.py
- fmriprep/cli/version.py
- fmriprep/cli/workflow.py
This PR stops the printing of the full boilerplate in the standard output.
I have run ``black`` on the cli module and fixed a tiny bug with a formatting argument not being interpolated when reporting missing dependencies.
> MAINT: Stop printing full boilerplate, ``black fmriprep/cli``

- fmriprep/interfaces/reports.py
Closes https://github.com/poldracklab/fmriprep/issues/2049
Turns out we weren't passing in the `sub-` identifier, which in turn made ReconAll (rightfully) assume the subject wasn't run.
This also imports the modified `ReconAll` interface used in smriprep.
> FIX: correct previous recon-all reporting

- docs/faq.rst
- fmriprep/cli/parser.py
When loading from `bids-filter-file` from json the pybids query values NONE and ANY cannot be used (cannot be serialized).
Here is a quick fix for that problem, will need to be pushed to smriprep as well, and tested.
json `null` is converted to bids.layout.Query.NONE
json string `'__any__'` is converted to bids.layout.Query.ANY (could change the naming if we prefer `'*'` but it usually means anything including empty, maybe `'+'` then ?)
The FAQ section on how to select images when multiple one available.
> ENH: Enable filtering for ANY or NONE in ``--bids-filter-file``

- fmriprep/cli/parser.py
So we can avoid the deprecation warning
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
> MAINT: ensure yaml loader is specified

- fmriprep/workflows/bold/confounds.py
Following poldracklab/smriprep#189.
> FIX: Ensure correct WM and CSF masks are picked in confounds workflow

- fmriprep/cli/run.py
A test fix for #2137. Also ran `black` on `fmriprep/cli/run.py`.
@ariekahn if you have the time and would like to pilot this, please do 😄
> FIX: Temporary config file in work directory gets clobbered in parallel jobs

- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/resampling.py
This is a temporary patch before we go all the way in with NiTransforms
in the sampling of BOLD on surfaces.
The anatomical _fast-track_ required to expose the fsnative-to-T1w
transform in the derivatives folder (which we were already doing in ITK
format).
When fMRIPrep ran without the fast-track, then the LTA transform would
be directly passed in without conversions. The fast-track PR forced the
implementation to use the ITK version.
This, in conjunction with the little trick to stick the BOLD shape and
zooms into the LTA (i.e., using ``lta_concatenate`` with an identity
transform with those features, shape and zooms, as moving) resulted in
an overly complex workflow that I partially implemented with
NiTransforms.
This PR gets rid of the concatenation with identity trick, using …
> FIX: Generate proper LTA transform prior BOLD sampling on surfaces

- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/registration.py
- fmriprep/workflows/bold/resampling.py
This is the root cause of #2142 (although our posterior handling of
the data types in the DerivativesDatasink wasn't great and that
justified nipreps/niworkflows#527).
I found many instances where ``ApplyTransforms`` was used in combination
with ``float=True``. This is why the data array contained floating point
values.
After using this patch, most of the ``_dseg.nii.gz`` files in the output
dropped from ~400KB down to ~25KB (confirming the size is changing on
hard disk). Visually checking one of these files seemed to give the
same labels.
Resolves: #2142
> FIX: ``MultiLabel`` interpolations should not use ``float=True``

- fmriprep/cli/parser.py
- fmriprep/config.py
Fixes #2151 
There are many aliases for the `nprocs` option, but we were not being consistent with the dest variable.
Also fixes an invalid nipype plugin argument (https://github.com/poldracklab/fmriprep/issues/2153#issuecomment-636205196)
> FIX: ensure commandline aliases are respected

- .github/ISSUE_TEMPLATE/bug_report.md
I thought we could make more targeted questions. In particular, we always want to know the command line they executed and whether the report was generated.
> MAINT: Improve the questions on the bug-report template

- fmriprep/cli/parser.py
- fmriprep/cli/workflow.py
- fmriprep/config.py
- wrapper/fmriprep_docker.py
This PR restructures the way we handle the FreeSurfer license:
Requires: nipreps/niworkflows#533 (when the canary does not manipulate the environment)
> FIX: FreeSurfer license manipulation & canary

- fmriprep/config.py
- setup.cfg
Closes #2140 
adds `disable_telemetry` property to `config.nipype` to control whether the initial latest version is done. afterwards, both `NIPYPE_NO_ET` and the config value `check_version` are set to disable future checks
> ENH: Ensure nipype telemetry is just pinged once

- docs/conf.py
- setup.cfg
> DOC: Pin nipype with new sphinx extension syntax

- wrapper/fmriprep_docker.py
#2165 dropped the conversion from str -> path-like for the wrapper's FreeSurfer license binding
> FIX: Coerce license path to pathlike

- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/t2s.py
- setup.cfg
References #1745, https://github.com/nipreps/niworkflows/issues/399, and https://github.com/nipreps/niworkflows/pull/408.
- Currently, just tags a specific version of niworkflows to ensure backward compatibility, by request of @effigies.
None
> FIX: Revise multi-echo reference generation, permitting using SBRefs too

- fmriprep/interfaces/reports.py
- fmriprep/workflows/bold/base.py
Builds on the new echo list extraction of #1803 to determine whether the
dataset is single-echo, multi-echo (and how many echoes are processed),
or multi-echo but processing only one of the echoes (e.g., using
``--bids-filter``).
Resolves: #2174.
> ENH: Report number of echoes in BOLD summary.

- CHANGES.rst
- docs/conf.py
- docs/faq.rst
- setup.cfg
```
sed -i 's+poldracklab/smriprep+nipreps/smriprep+g'
```
and update ``docs/conf.py`` with new url for the python doctree reference.
> DOC: Update references to new nipreps GH organization

- .zenodo.json
- wrapper/fmriprep_docker.py
Adding an option to the wrapper to omit the "-it" argument to docker, which avoids crashes in non-interactive environments (See https://github.com/nipreps/smriprep/issues/209 and https://github.com/nipreps/smriprep/pull/216#issuecomment-649134073)
> ENH: Add --no-tty option to fmriprep-docker.py

- fmriprep/cli/parser.py
- fmriprep/config.py
- fmriprep/data/tests/config.toml
fixes #2176
replace meaningful  bids-filter None values with bids.layout.Query.NONE to be kept with config toml dump/load.
> FIX: Storing ``--bids-filters`` within config file

- fmriprep/cli/parser.py
- fmriprep/cli/run.py
- fmriprep/config.py
- wrapper/fmriprep_docker.py
Closes #2019 
- Adds support for `BIDSLayout.database_path`
- If no database path is specified, one will be created in `<working-directory>/<run-uuid>`
- If it is specified, will just use that path
- A `<run-uuid>` directory is created at the top level of the `<working-directory>`, and the previously generated `config-<run-uuid>.toml` files are now located within each directory and renamed to `config.toml`
> ENH: Leverage BIDSLayout's database_path

- fmriprep/workflows/base.py
- setup.cfg
Fixes #2197 .
In the case where a precomputed anatomical derivatives are provided with `--anat-derivatives`, skip the check for an existing T1w.
For now the side-tracking of smriprep will produce a warning when the anat-derivatives does not match the necessary input. Should it produce an error and die instead?. I think that this option will be mainly used by skilled users, and they would rather know if fast-track didn't work.
> FIX: skip t1w check if anat-derivatives provided.

- .circleci/ds005_fasttrack_outputs.txt
- .circleci/ds005_outputs.txt
- .circleci/ds005_partial_fasttrack_outputs.txt
- .circleci/ds005_partial_outputs.txt
- .circleci/ds054_fasttrack_outputs.txt
- .circleci/ds054_outputs.txt
- .circleci/ds210_fasttrack_outputs.txt
- .circleci/ds210_outputs.txt
- docs/outputs.rst
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/outputs.py
Closes #1184.
Open questions:
- Should `tfm` transforms be supported in `DerivativesDatasink`?
- Answer: Replace `tfm` with `txt`.
- Do we want the native-to-T1w transform even when T1w isn't one of the desired spaces?
- Answer: Yes.
- Incorporate bold2anat_xfm and anat2bold_xfm into functional derivatives workflow. This will save these transforms only when T1w is a desired output space.
I added the transforms to the "Outputs of fMRIPrep" page.
> ENH: Save scanner-to-T1w xform to outputs

- fmriprep/utils/misc.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/resampling.py
Closes #2175. It appears that dropping the tedana-based mask in #2109 led to un-joined echo-specific masks being used _after_ echo combination throughout the workflow. This led to many redundant nodes in the workflow being created, including multiple runs of ICA-AROMA, although those nodes should be duplicates of one another except for the difference, if any, in masks.
- Move final reference image creation step out of `init_bold_preproc_trans_wf` and into `init_func_preproc_wf`. The workflow is called `final_boldref_wf`.
- Rename `bold_reference_wf` in `init_func_preproc_wf` to `initial_boldref_wf`.
- Replace `bold_files` in `join_echos` JoinNode with reference native-space BOLD files from `bold_bold_trans_wf`.
- Add `skullstripped_bold_files` to `join_echos` JoinNode, to combine …
> REF: Split final boldref generation from BOLD-BOLD resampling, eliminate extra per-echo computation

- .circleci/config.yml
- fmriprep/cli/parser.py
- fmriprep/config.py
- wrapper/fmriprep_docker.py
Restart of #2107. Last comments were about restyling with `black`, so I restyled, and rebased all of #2107 on top of this, restyling in the process.
Closes #2187.
> ENH: Reuse config

- fmriprep/data/reports-spec.yml
- fmriprep/interfaces/confounds.py
- fmriprep/utils/confounds.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
This PR revises the implementation of CompCor masks in an attempt to make it closer to the original proposal and at the same time address some recurring problems of *fMRIPrep*'s tCompCor implementation.
Finally, with the more careful resampling of prior knowledge from the anatomical scan, this refactor should also make the aCompCor components more run-to-run repeatable.
The massaging of CompCor masks is now done in anatomical space where it is more precise, and a careful resampling to BOLD space follows.
The implementation deviates from Behzadi et al. Their original implementation thresholded the CSF and the WM partial-volume masks at 0.99 (i.e., 99% of the voxel volume is filled with a particular tissue), and then binary eroded that 2 voxels:
> Anatomical data were segmented into gray …
> FIX: Revise the reproducibility of CompCor masks

- fmriprep/__init__.py
- fmriprep/workflows/bold/base.py
PyBIDS changed its behavior around the extension entity. The old behavior was to ignore the initial dot (`.`), which remains the default. The planned behavior will be to include the initial dot, as of 0.14. This PR accepts the new behavior, suppressing the warning.
> MNT: Silence pybids warning by setting extension mode

- fmriprep/workflows/bold/confounds.py
- setup.cfg
> ENH: Revise confounds in confounds-correlation plots

- CHANGES.rst
- fmriprep/workflows/bold/confounds.py
This branch tracks merging #2252 into master, so we can test the proposed inclusion in fMRIPrep 20.2.x alongside the @oesteban's target in 20.1.x.
My merge was not entirely clean. As a result, I went ahead and applied my suggestion from https://github.com/poldracklab/fmriprep/pull/2252#discussion_r483130729.
> TRACK: Revise confounds in confounds-correlation plots

- docs/workflows.rst
- fmriprep/cli/parser.py
DOC: Note options in documentation.
Closes #2259.
Restores #2015.
> FIX: Restore --ignore t2w/flair options

- Dockerfile
When putting together the 20.1.3 release, some version conflicts in
addition to the extension (dot-start) changes made the image be shipped
without important blobs.
The new queries should work well for any version of TemplateFlow, while
ensuring we don't get empty queries.
Resolves: #2266
> FIX: More targetted TemplateFlow queries to work with all later releases

- setup.cfg
Addresses:
```
ERROR: niworkflows 1.2.9 has requirement pybids~=0.10.2, but you'll have pybids 0.12.1 which is incompatible.
ERROR: niworkflows 1.2.9 has requirement templateflow<0.6.3,>=0.4.2, but you'll have templateflow 0.6.3 which is incompatible.
```
References: #2264
References: #2266
IMPORTANT: this commit should not be merged into master.
> FIX: Dependency conflict between niworkflows and templateflow

- Dockerfile
Addresses the effects of #2265 and #2266 on current master.
> FIX: Get missing ``probseg`` file from MNI152NLin2009cAsym

- fmriprep/workflows/bold/base.py
> FIX: Specify logger for warning

- fmriprep/interfaces/reports.py
- fmriprep/interfaces/tests/test_reports.py
- fmriprep/workflows/bold/base.py
BOLD runs' `FunctionalSummary` nodes were returning PE-Axis instead of PE-Direction.
> FIX: Clarify phase encoding direction, rather than axis

- .maint/contributors.json
- .zenodo.json
- docs/workflows.rst
docs say that the deteciton heuristic is used by default but at the moment skull stripping is forced per #2318, updated docs to mention this
> DOC: skull stripping is forced by default

- .circleci/config.yml
- setup.cfg
This updates the base images for our circle tests, and bumps the numpy and scipy versions as the one we're currently using is raising an error.
Given that this is the LTS branch, are we comfortable moving to a different minor of the above packages?
> MAINT: Failing CI

- fmriprep/workflows/bold/base.py
Fixes #2405
When `dummy_scans` is provided in the configuration, we do not need to estimate the number of non-steady-state volumes, thus increasing performance of workflow creation.
This effectively halves the time needed for `init_func_preproc_wf` in my test dataset.
Not applicable
> [ENH] Improve `_get_series_len` performance

- setup.cfg
tedana 0.0.9 requires scipy 1.3.3+ and scikit-learn 0.22+
Upgrading to 0.0.9+ would break our commitment to avoid non-bug-fix changes to underlying libraries during the LTS window.
> PIN: tedana 0.0.9a1 for LTS branch

- .circleci/config.yml
- Dockerfile
- fmriprep/utils/bids.py
- setup.cfg
- wrapper/fmriprep_docker.py
This PR bumps up the Docker image base to Ubuntu Focal LTS (20.04).
As a result, a number of packages were updated, including:
- AFNI
- FSL
- Connectome Workbench
- Graphviz
- Pandoc
Furthermore, Python was bumped to 3.8.x, and many of its packages were "modernized" accordingly.
This builds the foundation for #2392 , as it depends on updated scipy. Also closes #2382
> ENH: Bump Dockerfile

- .circleci/config.yml
- setup.cfg
Nilearn 0.8.0 bumped the numpy dependency to `>=1.16`. The last release of 20.2.x had nilearn 0.6.2, so I'm pinning that here. We can march it forward as we verify reproducibility and start relaxing some of our dependency constraints.
This should unblock #2331.
> PIN: nilearn 0.6.2

- fmriprep/cli/parser.py
- fmriprep/cli/tests/test_parser.py
Check if provided bids-filter-file path exists if not raise an error.
This should avoid cases when the user provides file filters and the pipeline silently runs on other set of file. 
none
> FIX: non-existing path or JSON syntax error for `--bids-filter-file` should raise on error.

- fmriprep/cli/parser.py
- fmriprep/config.py
It can be useful to store the BIDS database separately from the working directory. For example, if you want to preserve the working directory on an HPC run, it will need to be put on (or synced to) a network store. There is no advantage to doing that with an SQLite database as well, so we should permit the location to be specified without pre-generating.
> ENH: Relax requirement for PyBIDS databases to exist

- fmriprep/workflows/base.py
Inspired by https://github.com/nipreps/nibabies/issues/82.
`workflow.connect()` is tab-shifted but otherwise unchanged.
> FIX: Raise informative error when duplicate subworkflows are added

- fmriprep/cli/run.py
To remove some ambiguity from that error.
Additionally, fMRIPrep will now raise a `RuntimeError` in addition to any `Exception` hit when running the workflow.
> FIX: Add some clarity to BrokenProcessPool failures

- setup.cfg
This PR limits the latest acceptable version of networkx, nilearn and tedana, as they have started to show errors when building the docker image.
> MAINT: Some dependencies cannot be left unpinned

- fmriprep/workflows/bold/registration.py
As reported by @eburkevt back on October 18, 2020, resampled BOLD time-series in standard spaces do not look good anymore.
This PR uses FreeSurfer to cater RAS2RAS transforms to *NiTransforms*.
This may resolve the problem for *fMRIPrep* regardless of the resolution of poldracklab/nitransforms#125
Addresses: #2307.
> FIX: Feed *NiTransforms* with LTAs of type RAS2RAS

- setup.cfg
There is a new `tedana` release (0.0.9), in which the masking we apply is made less aggressive. This should address user-reported issues with multi-echo coverage in fMRIPrep (e.g., [here](https://neurostars.org/t/poor-fmri-prep-brain-masks/5712?u=tsalo), [here](https://neurostars.org/t/bold-brain-mask-not-correct-problem-with-bold-signal-itself/17494?u=tsalo), and https://github.com/ME-ICA/tedana/issues/600).
Pinging @emdupre and @jbteves because they were involved in the release.
- Increase the minimum `tedana` version to 0.0.9, now that there is a new release.
None
> MNT: Increase minimum tedana version

- .circleci/config.yml
As a result of the ambiguity of these tags, a tag 20.2.2 was deployed to docker hub containing the 20.1.4 build last Friday.
The misuse of ``{{ epoch }}`` as well as too liberal template matching when loading cached docker images resulted in this situation.
Resolves: #2454.
> MAINT: Revise CircleCI's cache tags to avoid mixups between builds

- fmriprep/cli/parser.py
> FIX: Unprotected import of ``sentry_sdk``, which is not a dependency

- setup.cfg
Makes sure this bugfix to *NiWorkflows* gets distributed with the current LTS.
Supersedes/closes: #2421.
Links: nipreps/niworkflows#640.
> FIX: ``DerivativesDataSink`` nondeterministic checksums fixed with ``niworkflows=~1.3.4``

- Dockerfile
Closes #2462.
Combined svgo and bids-validator installation to keep the layer smaller.
Currently, there's a 77MB /root/.npm directory.
```
$ fmriprep-docker --shell            
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.7 -it -v /home/chris/Projects/nipreps/fmriprep:/data:ro -v /home/chris/Projects/nipreps/fmriprep:/out --entrypoint=bash nipreps/fmriprep:20.2.2
root@afd4469af151:/tmp# du -sh /root/.npm
77M	/root/.npm
```
> MNT: Remove /root/.npm

- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
> ENH: Detect 3D BOLD series, warn and return empty workflow

- fmriprep/workflows/bold/base.py
I precipitated the merge of #2461 without observing three issues:
- The bold workflow is provided with a list (not a str) with ME-EPI
- Test data (ds054) for CircleCI has only 5 timepoints, which triggered workflow skipping.
- Inexisting variable name required in string interpolation when logging the skip warning.
Both problems are addressed in this PR.
Continues: #2461.
> FIX: Address the problems of a sloppy merge

- docs/spaces.rst
@bbfrederick brought up the problem that, although the documentation does not state the above explicitly, it is the most plausible reading.
This PR adds a danger admonition to clarify the ambiguity.
Follow-up: templateflow/templateflow#92.
Resolves: #1847.
> DOC: Clarify that ``res-2`` entity does not mean 2mm

- .circleci/config.yml
Reduces packaging tests to just
- tags
- release branches
- maintenance branches
This will allow us to stay pinned to the developmental branches
of our nipreps dependencies during active development.
> ENH: Ease CI packaging tests

- scripts/fetch_templates.py
Related to #2480 
Facilitate no network runs by providing users a script to cache templateflow templates to a directory.
> ENH: Allow users to download templateflow templates to directory

- .circleci/config.yml
- docs/faq.rst
- fmriprep/cli/parser.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/stc.py
After #2461 and #2468, the ``TooShort`` value for running STC could not be assigned.
This PR ignores manually set dummy timepoints, although the case when this could be problematic is largely a very edge case (say you have only 7 timepoints and manually set 3 as dummy).
On the flip side, this PR drops the use of a function discontinued in the latest niworkflows release, fixing a bug ahead of time (currently popping out in #2392).
> FIX: Simplify STC logic for too short BOLD series

- Dockerfile
- fmriprep/interfaces/__init__.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/hmc.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/registration.py
- fmriprep/workflows/bold/resampling.py
- fmriprep/workflows/bold/stc.py
- fmriprep/workflows/bold/t2s.py
- setup.cfg
Removes the preloading of interfaces at ``__init__`` of the interfaces submodule.
> ENH: Avoid eager imports from *NiWorkflows* causing API breaks

- fmriprep/workflows/bold/base.py
Should make #2512 have a clearer error message.
> FIX: Permit missing TR to show PyBIDS error at workflow construction time

- fmriprep/workflows/bold/registration.py
After #2444, `init_bbreg_wf` would crash when `bold2t1w_init == 'register'` and `use_bbr is False`.
Originally implemented in https://github.com/nipreps/nibabies/pull/95
> FIX: Avoid unnecessary connections based on branching logic

- fmriprep/config.py
- setup.cfg
Updates to the recommended way of initializer the indexer, and also
includes a new regex to preempt indexing unnecessary modalities as
@jdkent reported.
Resolves: #2386.
> ENH: Use ``BIDSLayoutIndexer`` and do not index unnecessary modalities

- fmriprep/cli/parser.py
- fmriprep/config.py
- fmriprep/workflows/bold/stc.py
This PR partially address #2477 by providing a flag `--slice-time-ref` that can take a float from 0-1 or special values `"first"` and `"middle"`.
This also always sets the `-tzero` flag for 3dTshift (in cases where we run STC) to `min + frac * (max - min)`, which will generally be `frac * max`. This *should* be the same as 3dTshift's default of `mean(SliceTiming)`, as well as `frac * max`, but I update the text to be explicit as well.
Millisecond precision is used in reporting.
Closes #2516.
> ENH: Add flag for STC reference time and set in all cases

- .github/workflows/pre-release.yml
- .github/workflows/stable.yml
- .maint/ci/activate.sh
- .maint/ci/build_archive.sh
- .maint/ci/check.sh
- .maint/ci/create_venv.sh
- .maint/ci/env.sh
- .maint/ci/install.sh
- .maint/ci/install_dependencies.sh
- .maint/ci/install_extras.sh
- fmriprep/cli/tests/test_parser.py
- fmriprep/utils/sentry.py
- setup.cfg
I want to run pre-release tests on fMRIPrep to make sure that upcoming releases like numpy, nilearn or pybids aren't going to break things. GitHub actions seems the lightest-touch way of doing this.
~~Starting with stable tests. Will add pre-release if this works.~~
Started with stable tests, added pre-release tests. Added a test to ensure that we exercise pybids.
> CI: Run pytest through GitHub actions

- Dockerfile
Fixes #2534.
Once done, this should be fetchable at `docker://nipreps/fmriprep:libqt`.
> DOCKER: Strip ABI tag from libQt5Core.so.5 to prevent Singularity failures

- Dockerfile
Addresses #2545
Exclude and remove many unneeded binaries / files.
To cut down the size a bit further, we may want to `strace` and compile a list of the freesurfer / fsl binaries we are using, as there are still many included that are not being used.
Building off this PR:
```
$ docker images
REPOSITORY                           TAG                 IMAGE ID       CREATED          SIZE
nipreps/fmriprep                     size                e0634fde686b   21 minutes ago   13.9GB
```
> FIX: Shrink Docker image size

- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/t2s.py
- setup.cfg
This PR addresses the problem reported in #2210.
Along with the specific changes in SDCFlows, this PR:
- Resamples BOLD data in its native space using new SDCFlows' utilities.
- Introduces a new ``IdentityInterface`` node called ``bold_final`` that acts as buffer to reduce LoC and branches when dealing with data with/without fieldmaps (and helpful too for ME-EPI, although this is not fully implemented).
- ROIs plot now uses the output of unwarping through a `RobustAverage` node, therefore fixing one issue reported in #2210.
- preproc datasink of BOLD in native space now connected to the ``bold_final`` node, which contains HMC'ed + SDC'ed (if fieldmaps found) BOLD in native space. Now, it is matched with the ROIs plot, reducing a little the opportunities for divergence.
**This PR DOES NOT …
> ENH: Refactor workflow to adopt *SDCFlows*' new correction workflow

- fmriprep/workflows/bold/outputs.py
Closes #2539.
Addresses #2477.
Implements provisional https://github.com/bids-standard/bids-specification/issues/836
This does not update the `toffset` field in NIfTI at present.
One thing to address: when we're calculating the acquisition time (TA), we use `st[-1] + (st[1] - st[0])`, which treats each slice as having a duration. When we're calculating tzero, we use `(st[-1] - st[0]) * frac + st[0]`, which treats each slice as an instantaneous acquisition. So tzero is a half "slice duration" less than half TA (`tzero = (t[0] + TA) / 2 - (t[1] - t[0]) / 2`).
Our tzero calculation is consistent with AFNI's default, but while we're here, maybe we want to adjust it to be `tzero = (t[0] + TA) / 2`. Or is the calculation of TA incorrect?
cc @martinhebert @theoschaefer @nitschalex …
> ENH: Add SliceTimingCorrected and StartTime fields to BOLD metadata

- fmriprep/data/reports-spec.yml
- fmriprep/workflows/bold/registration.py
Rebases #2607 on master.
Fast-tracked to get this into the next 21.0.0 RC. Need to figure out numpy failures in the docker image to patch 20.2.x.
> ENH: Replace initial FLIRT with mri_coreg, use -basescale 1 for FLIRT-BBR

- docs/conf.py
- docs/links.rst
- docs/outputs.rst
> DOC: Update description of output layout, add discussion of legacy mode

- NOTICE
These lines are not true anymore after SDCFlows 2.0 (I don't think they are true for SDCFlows either, at this point in time).
> DOC: Remove mention to ``epidewarp.fsl`` from ``NOTICE``

- .circleci/config.yml
- .circleci/ds210_fasttrack_outputs.txt
- .circleci/ds210_outputs.txt
- fmriprep/workflows/bold/base.py
- setup.cfg
This PR:
1) Changes the source of iteration from `boldbuffer`/`meepi_echos` to `echo_index`, an `IdentityInterface` that is just `0` for single-echo workflows.
2) The echo index is passed to `bold_source` which indexes the list of BOLD images, and `validated_bold`, which indexes the list of BOLD images that have been validated in `initial_boldref_wf`.
Consequences:
1) Validated echos are now passed to STC/boldbuffer (was true for SE, but not for ME)
1) STC no longer has any dependency on number of echos
1) JoinNodes `joinsource` no longer depends on STC (non-)use
1) Iterable directories are now indexed by an integer instead of full file paths
1) `bold_bold_trans_wf` `name_source` no longer depends on number of echos
Fixes #2650.
> RF/FIX: Iterate over echo indices, not filenames, simplifying iteration logic

- fmriprep/workflows/base.py
- wrapper/fmriprep_docker.py
The big issue was that the functional heading was attached to the anat postproc. Prepending it to all functional workflows ensures that it's always kept local. The fmap workflow needs an extra newline to be placed correctly, as well.
While testing this, I ran across the problem that the PKG_PATH in the wrapper didn't keep up with the changes in the docker file. I thought I'd fixed that in another PR, but I either never included it or it hasn't been merged yet.
Closes #2526.
> FIX: Re-group and space boilerplate text

- fmriprep/workflows/bold/registration.py
- Disables `flirt` scaling of input transformation matrices, which may
lead to issues with high-resolution T1w data (see #2591)
This is #2607 without the switch to `mri_coreg`. That can be done in 21.0.0.
Doing this first so we can get the mri_coreg fix into the next 21.0 RC.
cc @HippocampusGirl
> FIX: Add `-basescale 1` parameter to avoid `flirt` scaling

- fmriprep/workflows/bold/confounds.py
> FIX: Ensure AROMA inputs are uncompressed if --low-mem

- Dockerfile
Closes #2644. Can be obviated by https://github.com/nipreps-containers/miniconda/pull/2.
> MNT: Update scikit-image to 0.19 in Docker image

- .github/ISSUE_TEMPLATE/bug_report.yml
This will help distinguish between bugs in fMRIPrep and fmriprep-docker and also make it easier to ask diagnostic questions.
> MNT: Ask for fmriprep-docker RUNNING line

- fmriprep/cli/parser.py
- fmriprep/cli/tests/test_parser.py
- fmriprep/workflows/base.py
The main use case here is when writing a script to run fMRIPrep on heterogeneous datasets. This avoids having to pre-check each dataset/subject for whether `PhaseEncodingDirection` is available; you just run it if you can.
Also simplifies the (probably vanishingly rare) case where `PhaseEncodingDirection` may be available for some tasks/runs within a subject but not others.
The old behaviors are preserved, so this is bug-fix safe. `--use-syn-sdc` and `--use-syn-sdc error` are synonyms. `--use-syn-sdc warn` is the new feature.
Happy to consider alternative approaches, but I think this is useful functionality.
> ENH: Allow `--use-syn-sdc` to take a "warn" option to avoid exiting when PE dir is unavailable

- Dockerfile
This creates the `/etc/protocols` file that allows Haskell (git-annex) to fetch web objects. Without it you can get responses like:
```
$ singularity exec code/containers/images/bids/bids-fmriprep--21.0.0.sing datalad get sourcedata/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz
get(error): sourcedata/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz (file) [https://files.osf.io/v1/resources/ue5gx/providers/osfstorage/5bc647b153cec4001aadab65 download failed: ConnectionFailure Network.BSD.getProtocolByName: does not exist (no such protocol name: tcp)
downloading from all 1 known url(s) failed
https://files.osf.io/v1/resources/ue5gx/providers/osfstorage/5bc647b153cec4001aadab65 download failed: ConnectionFailure Network.BSD.getProtocolByName: does not exist (no …
```
> MNT: Add netbase to Docker image to ensure correct datalad operation

- fmriprep/workflows/base.py
Requires nipreps/sdcflows#258.
Started testing on ds000223, and the workflow looks reasonable, but the affines are slightly different between EPI and BOLD. I'll look for another dataset or just hack the affines for now.
> FIX: Re-enable reverse-PE EPI fieldmaps

- fmriprep/__init__.py
- setup.cfg
Lesson learned about trying to cycle through FutureWarnings/DeprecationWarnings to change APIs with no quiet period.
Also, we use `packaging` for more than just docs. Promoted to a first-class dependency.
> MNT: Silence warning from pybids; list packaging as dependency

- fmriprep/workflows/bold/confounds.py
A few words seemed to be missing in the documentation about how confounding signals are calculated. I believe this is the intended meaning. (But please double check me!)
> DOC: clarify calculation of confounding signals

- fmriprep/workflows/base.py
> ENH: Add major/minor versions to base workflow name

- fmriprep/workflows/bold/confounds.py
> MAINT: Normalize code style of ``workflows.confounds``

- fmriprep/workflows/bold/base.py
Likely fixes issues reported in https://github.com/nipreps/fmriprep/issues/2727
No
> FIX: ensure `fieldwarp` == `identity` during resampling of processed multi-echo data

- fmriprep/interfaces/confounds.py
The final integration of the edge mask had missed that detail. It went undetected as the reports on Circle did not show CIFTI outputs. Now that is resolved and this PR should conclude the carpet refactor.
> FIX: Plot carpetplot with CIFTI-specific colorbar

- setup.cfg
In cases when the input BOLD series has `pixdim[4]` in ms, we update the output series to have the temporal units of seconds, but do not set the `pixdim[4]` field to seconds. This release of niworkflows fixes that.
Low priority for release, IMO.
> FIX: Set pixdim[4] (repetition time) in seconds

- .circleci/config.yml
- .maint/ci/build_archive.sh
- .maint/ci/env.sh
* ~~Run tests/doctests on Python 3.10 in GitHub Actions~~ No vtk for Python 3.10, so we can't install niworkflows.
* Build sdists/wheels with `python -m build`, which provides build isolation, so we don't need to use our own on CircleCI
* Remove the `VERSION` file from sdist/wheel builds. We check whether the packages have the correct version added by versioneer.
> CI: Update package builds to use python -m build

- .git-blame-ignore-revs
- .maint/update_ignore_revs.sh
This is not intended to be complete, but can be added to as annoying commits show up in blame. I also added a script so we can annotate them automatically. It would be nice to tag commits with `[ignore-rev]` if we intend to ignore them, and we can then auto-add them later.
> MNT: Seed ignore-revs file and script to tag new hashes with log entries

- fmriprep/cli/parser.py
- fmriprep/config.py
I saw three options.
1) Protect the PyBIDS DB from being deleted by `--clean-workdir`. This complicates the cleaning code.
2) Move cleaning into `config.execution.init`, which seems bad as I think initialization is supposed to be okay to do multiple times. Destructive filesystem operations certainly seem bad to hide in configuration init.
3) Have a separate explicit layout initialization step that we call after cleaning the work-dir.
Went for option 3.
Fixes #2721
> FIX: Initialize BIDS layout after cleaning working directory

- Dockerfile
Running into problems with cache-less docker builds
> FIX: Update multiarch deb package link

- .circleci/config.yml
Slightly rework the circleci config to:
- Use YAML anchors to avoid obvious duplication
- Use `large` machines (4 vCPUs, 15GB RAM) (we could also consider using xlarge - 8/32GB)
- Leverage `docker_layer_caching` (decent speedup!)
Closes #2759
> CI: Touch up CircleCI configuration

- .circleci/config.yml
- setup.cfg
Starting by setting a random seed to verify that it can be reproduced.
> Diagnose ds210 failure

- docs/faq.rst
minor fix to make the default config in the FAQ JSON valid for an easier copy-paste-adapt
> [DOC] fix JSON typo in config in FAQ

- .circleci/ds210_fasttrack_outputs.txt
- .circleci/ds210_outputs.txt
- docs/outputs.rst
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/resampling.py
Resample T2* map (calculated in BOLD space) to T1w and standard spaces if requested. Sink any of these as functional derivatives.
Unclear what would happen with fsaverage, so will need to test this case.
Need to update expected outputs.
> ENH: Save T2starmap files in all requested output spaces, if calculated

- fmriprep/data/reports-spec.yml
- fmriprep/interfaces/maths.py
- fmriprep/interfaces/reports.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/t2s.py
Closes #2541. I think we should also show the gray-matter mask in the T2*-boldref map immediately above the histogram.
Working on the OHBM poster should provide some images/text that can be added to the docs.
> ENH: Plot histogram of T2* values in gray-matter mask

- Dockerfile
- setup.cfg
- wrapper/fmriprep_docker.py
Quick check. If this works, then let's upgrade to Python 3.9 for 22.0.x. Otherwise it can wait.
> MNT: Build on Python 3.9 environment

- fmriprep/workflows/bold/base.py
Fixes #2839
I'm considering whether its cleaner to add `sbrefs` as a parameter to the workflow (function signature changing, so in a future minor bump) since we already have a data collection step https://github.com/nipreps/fmriprep/blob/c9c43ba5470c18bbfaf1cefb8800e2b377eeb405/fmriprep/workflows/base.py#L153-L158
> FIX: Filter sbrefs by BIDS filters if available

- fmriprep/workflows/base.py
- setup.cfg
Closes #2832 
This sets a `minimum_fs_version` to ensure an FS7 recon-all compatible `fsaverage` is available.
Also bumps nipreps dependencies to the latest compatible versions.
> ENH: Add check to ensure latest fsaverage folder is used

- .circleci/config.yml
- fmriprep/interfaces/confounds.py
- setup.cfg
When running full fMRIPrep on test data, we can get empty compcor results. Since there's nothing to rename, this just passes empty files without attempting to modify them.
> FIX: Check for empty ACompCor results before trying to rename

- fmriprep/data/reports-spec.yml
- fmriprep/workflows/bold/base.py
- setup.cfg
This PR drafts a missing component for a faster assessment of problems with fieldmaps.
> MAINT: Generate more verbose reports (here, showing fieldmaps) if running in debug mode

- .circleci/ds005_legacy_partial_fasttrack_outputs.txt
- .circleci/ds005_legacy_partial_outputs.txt
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/resampling.py
- setup.cfg
This cleans up a lot of the legacy code previously used to generate frankenstein MNI152NLin2009cAsym/fsaverage CIFTI-2 files.
- Removes legacy MNI152NLin2009cAsym/fsaverge hybrid space
- Remove redundant outputs (cifti variant/cifti density)
Follows work in https://github.com/nipreps/niworkflows/pull/756
> RF: CIFTI generation

- fmriprep/workflows/bold/resampling.py
This experiments with removing the cortical masking during the BOLD volume -> surface sampling, as suggested in https://github.com/nipreps/fmriprep/issues/2364#issuecomment-1275400866
The point is if we need to apply this mask in a later point, it should be trivial given the information is present in 
`?h.cortex.label` files.
> FIX: Remove cortex masking during vol2surf sampling

- fmriprep/cli/workflow.py
Running `--reports-only` in `--output-layout bids` (now default) results in:
```console
221202-17:24:56,169 nipype.workflow IMPORTANT:
Running --reports-only on participants 01
Process Process-2:
Traceback (most recent call last):
File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/workflow.py", line 91, in build_workflow
retval["return_code"] = generate_reports(
File "/opt/conda/lib/python3.9/site-packages/niworkflows/reports/core.py", line 544, in generate_reports
report_errors = [
File "/opt/conda/lib/python3.9/site-packages/niworkflows/reports/core.py", line 545, in …
```
> FIX: Conform --reports-only to match post-run report generation

- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/t2s.py
T2SMap was tagged with the default memory consumption (~100MB), when it should be based on the size of the input files. This implements #1100 in order to get a direct estimate of that, and then passes that along, with an additional factor based on the number of echos and a safety factor of 2.
Fixes #1100.
Fixes #2728.
> ENH: Tag memory based on data shape, annotate T2SMap

- .circleci/config.yml
- fmriprep/cli/run.py
- fmriprep/config.py
- fmriprep/utils/telemetry.py
- setup.cfg
This adds `migas` telemetry in addition to sentry, to allow us to compare +/-'s
> ENH: Add migas telemetry in addition to sentry

- fmriprep/workflows/bold/base.py
- setup.cfg
Takes advantage of nipreps/sdcflows#321 by providing an estimate of the free memory on the system to better select the number of threads to request.
None.
> ENH: Provide free memory estimate to unwarp_wf for better resources allocation

- .maint/update_changes.sh
- .maint/update_zenodo.py
- .zenodo.json
- CHANGES.rst
Preparation for the 22.1.0 release of fMRIPrep. I propose Monday, December 12 for release.
Outstanding issues:
> REL: 22.1.0

- .circleci/config.yml
The last build generated a bad version number in the docker file:
```console
$ docker run --rm -it nipreps/fmriprep:22.1.0 --version
fMRIPrep v22.1.0+0.gce344b39.dirty
```
Building locally, it doesn't seem to have an issue, so it seems to be a CircleCI problem. I've resolved what I think was causing the dirty repository and also added a safeguard that should ensure future CI issues don't affect version determination.
> FIX: Ensure version installed in Docker file is clean

- CHANGES.rst
- setup.cfg
Preparation for a 22.1.1 release, which fixes two small bugs. Ensuring CircleCI runs through before tagging, but will fast-forward merge into `maint/22.1.x` and tag when this passes.
> REL: 22.1.1

- fmriprep/interfaces/confounds.py
We had a use of deprecated `Index.ravel()` functionality. It turns out this was to do the same thing as `DataFrame.rename(columns=mapper)`, so I just replaced that.
Closes #2904.
> RF: Use DataFrame.rename instead of ad hoc process

- fmriprep/cli/run.py
Following recent discussion. ICA-AROMA is not necessary to do within the fMRIPrep workflow, and it constrains our ability to upgrade to newer versions of FSL and/or Python as the package is very sporadically maintained. A better approach is to wrap ICA-AROMA as a post-fMRIPrep app that takes a BOLD series in MNI152NLin6Asym space and produces the outputs/reports we have up to now.
This change is not to be effected in the next release, in order to give warning that this will happen.
> MNT: Warn that AROMA support will be removed in a future version

- docs/faq.rst
- docs/workflows.rst
- fmriprep/workflows/base.py
* Update docs to better match BIDS conventions for lesion ROIs, but do not change existing behavior.
* Emit warning that a change will be coming and users working with this feature should check the docs before doing further upgrades.
Closes #2892.
* Added notice that lesion ROI detection will change in an upcoming version (not 23.0).
> DOC: Update lesion ROI documentation, warn in docs and app about upcoming changes

- .maint/contributors.json
- fmriprep/cli/parser.py
Back when I commenced some work on #2207 (from which I'll need to familiarise myself with #2913), I started by looking at the CLI and thinking about what the right interface would be for such a capability (see eg. #2805, #2806). I immediately found some command-line options that really felt as though they were in the wrong place. So here I've separated out the set of CLI changes that I'd generated in the course of that little experiment.
The git diff is quite unclean, so I've produced the set of options that would be moved and their corresponding old and new option groups. 
| Option                      | Old option group              | New option group                                     |
|-----------------------------|-------------------------------|------------------------------------- …
> DOC: Altered CLI option grouping

- fmriprep/workflows/bold/base.py
- pyproject.toml
Hook up to https://github.com/nipreps/sdcflows/pull/334.
This is a workflow change, so requires a minor release bump for sdcflows and fmriprep.
This is based on reviewing the analysis provided by @sgiavasis and his group.
None.
> FIX: Pass reference image to unwarp_wf, use reference fieldwarp for single shot

- .circleci/ds005_legacy_partial_outputs.txt
- fmriprep/workflows/base.py
- pyproject.toml
Depends on https://github.com/nipreps/smriprep/pull/325
> ENH: Resample morphometrics to fsLR dscalar CIFTI-2 files if `--cifti-output` is used

- fmriprep/data/boilerplate.bib
> DOC: Add TemplateFlow's citation into bibtex file

- fmriprep/config.py
According to the [psutil docs](https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory):
> Return statistics about system memory usage as a named tuple including the following fields, expressed in bytes. Main metrics:
> 
> * total: total physical memory (exclusive swap).
> * available: the memory that can be given instantly to processes without the system going into swap. This is calculated by summing different memory values depending on the platform and it is supposed to be used to monitor actual memory usage in a cross platform fashion.
> 
> Other metrics:
> 
> * used: memory used, calculated differently depending on the platform and designed for informational purposes only. total - free does not necessarily match used.
> * free: memory not being used at all (zeroed) that is …
> FIX: Estimate free memory with "available", not "free"

- fmriprep/workflows/bold/t2s.py
Dilates BOLD mask by two voxels before passing to tedana's `t2smap` command. This accounts for BOLD masking sometimes being overly aggressive. Tedana is tolerant of a relaxed mask, so this is cheaper than attempting to rework mask generation to cover more cases without becoming worse in others.
Could consider dilating by more voxels to reduce the odds of clipping further.
> FIX: Dilate BOLD mask by 2 voxels to prevent over-aggressive masking degrading T2* map estimation

- fmriprep/workflows/base.py
`--force_syn` and `--use-syn-sdc` should behave identically when combined with `--ignore fieldmaps`. 
Closes #2918
> FIX: Inconsistent fmapless estimation when ignoring fieldmaps

- .circleci/config.yml
Getting tired of build times again, so experimented with layer caching.
Some references for how I got here:
* https://docs.docker.com/build/cache/backends/registry/
* https://docs.dagger.io/1237/persistent-cache-with-dagger/
> CI: Use registry for layer caching

- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/tests/test_base.py
This PR takes a chunk out of the `init_func_preproc_wf` function and pre-runs it in `init_single_subject_wf` to filter out fieldmaps that are not needed to correct BOLD files.
Closes #2968.
Closes https://github.com/nipreps/sdcflows/pull/359.
> RF: Filter fieldmaps based on whether they will be used to correct a BOLD series

- fmriprep/workflows/bold/base.py
Checks shapes of multiecho images on workflow build and errors rather than waiting for it to become an issue.
Closes #3005.
> FIX: Raise RuntimeError at build if echos have mismatched shapes

- docs/workflows.rst
- fmriprep/cli/parser.py
- fmriprep/config.py
- fmriprep/workflows/bold/t2s.py
Closes #3029.
- Add a new command line parameter, `--me-t2s-fit-method`, to control how T2* and S0 will be estimated with tedana. The default, "curvefit", is slower and more memory intensive, which has led to out-of-memory errors for some users. The new option, "loglin", shouldn't result in the same memory issues, but it also may produce less accurate estimates.
I added a couple of sentences on the new parameter to the "T2*-driven echo combination" section of `workflows.rst`.
> Add `--me-t2s-fit-method` parameter

- .github/workflows/pre-release.yml
- .github/workflows/stable.yml
- .maint/CONTRIBUTORS.md
- pyproject.toml
Test with Python 3.11, show Python 3.11 as supported.
\-
> MNT: Python 3.11 should be supported

- .github/workflows/pre-release.yml
- .maint/ci/env.sh
Pre-release tests on GitHub actions are taking a long time, almost all in installation. It turns out the Pandas is uploading sdists, but not a full set of wheels, to nightly. This adds `--prefer-binary` to just get the latest wheel they uploaded.
Also, we don't plan to update dependencies during maintenance phases, so I'm disabling pre-release tests for `maint/` branches. If this is merged, I'll cherry-pick onto `maint/20.2.x` and `maint/23.1.x`.
> CI: Clean up pre-release builds

- .maint/update_zenodo.py
This is an attempt to update script `.maint/update_zenodo.py`.
- File `contributors.json` appears to have been replaced by a table in Markdown file `CONTRIBUTORS.md`.
- Files `former.json` and `FORMER.md` luckily point to the same person. I haven't changed anything here: still reading from `former.json`.
Note that some contributors have two affiliations, and convey that using a JSON/Python array inside the Markdown array.
```
| Frederick         | Blaise B.    |  | 0000-0001-5832-5279 | ['McLean Hospital Brain Imaging Center, MA, USA', 'Consolidated Department of Psychiatry, Harvard Medical School, MA, USA']                  |
```
```
| Ghosh             | Satrajit S.  |  | 0000-0002-5312-6729 | ['McGovern Institute for Brain Research, MIT, MA, USA', 'Department of Otolaryngology, Harvard …
```
> MNT: update update_zenodo.py script

- .maint/CONTRIBUTORS.md
- .zenodo.json
- fmriprep/workflows/bold/resampling.py
Update documentation for `init_bold_grayords_wf`
Removes mention of inputs that are no longer used (`surf_files` and `surf_refs`). Adds documentation of the new `repetition_time` parameter and `bold_fsLR` input. 
Additionally, updates the description to clarify that the surface data is transformed directly to fsLR and the surface data is transformed to MNI152NLin6Asym at the appropriate resolution.
Resolves #3050.
> DOC: Fix documentation and description for init_bold_grayords_wf

- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
The improvements to SDC to detect sbref files and prefer them needed to come with passing sbrefs to the SyN workflow.
Fixes #3046.
> FIX: Pass sbref files to SyN workflow

- .readthedocs.yml
- docs/outputs.rst
- pyproject.toml
* Depend on Sphinx >= 5
* Add apt requirement for graphviz, to restore workflow graphs
* Build with Python 3.11, because why not?
* Remove unused references producing warnings
> MNT: Depend on newer sphinx

- .circleci/config.yml
Since moving to hatch-vcs and the next version strategies of `setuptools_scm`, the default behavior of a new branch is to increment the minor version (or major, if the new year happens to have come). At the same time, we have rules where `docker/XYZ` produces a docker tag `nipreps/fmriprep:XYZ`.
To create a Docker branch that indicates a patch on a minor series, which will be useful for reusing work directories and testing patches before a bug-fix release, this change allows for branches named `docker/X.Y.x+tag`. For example, `docker/23.1.x+mynewpatch` would produce a version `23.1.5.devN+gHASH` and a Docker image `nipreps/fmriprep:mynewpatch`.
> CI: Improve tag detection for docker builds

- fmriprep/workflows/bold/fit.py
* Accommodate nipreps/sdcflows#346
* Convert ITK transforms from `.mat` (MATLAB) to text format
> FIX: Update connections to unwarp_wf, convert ITK transforms to text

- .circleci/config.yml
It's been long enough, and a good time to change the outputs is when we've disabled checking that they don't change.
> CI: Stop testing legacy layout

- .github/workflows/pre-release.yml
- .github/workflows/stable.yml
- fmriprep/cli/parser.py
- fmriprep/cli/run.py
- fmriprep/config.py
- fmriprep/workflows/base.py
- pyproject.toml
Adds a `--level` flag to permit going beyond minimal. First thing beyond minimal is surface resampling outputs.
Also factored out the fieldmap estimator discovery into its own function.
> ENH: Generate anatomical derivatives useful for resampling

- fmriprep/cli/parser.py
- fmriprep/data/reports-spec.yml
- fmriprep/interfaces/reports.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/reference.py
- pyproject.toml
- requirements.txt
* Sets up scaffolding for including reports for fitting, following smriprep example.
* Adds basic SDC and coregistration reportlets.
TODO:
Results:
* [ds005](https://output.circle-artifacts.com/output/job/9e2d4c60-5fbb-4f2f-b129-280b60529159/artifacts/0/full-run/sub-01.html) (2 runs, no SDC)
* [ds005](https://output.circle-artifacts.com/output/job/9e2d4c60-5fbb-4f2f-b129-280b60529159/artifacts/0/partial-run/sub-01.html) (1 run, SyN-SDC)
* [ds054](https://output.circle-artifacts.com/output/job/9399b2c4-61f3-4d5e-b271-7a5861859779/artifacts/0/tmp/ds054/fmriprep/sub-100185_noerror.html) (2 run, phasediff)
* [ds210](https://output.circle-artifacts.com/output/job/b592d2a7-5cf6-445e-85e1-57bc722906b1/artifacts/0/tmp/ds210/fmriprep/sub-02.html) (1 run, SyN-SDC)
> ENH: Add reporting workflow for BOLD fit

- Dockerfile
- fmriprep/cli/parser.py
- fmriprep/config.py
- fmriprep/workflows/base.py
- scripts/fetch_templates.py
Closes #2694 
This PR adds MSMSulc surface registration, and enables it by default. To disable it, the `--no-msm` flag has been added, and behaves similar to `--no-fs-reconall`.
> ENH: Add MSMSulc

- docker/files/freesurfer7.3.2-exclude.txt
in total 3 lines were *removed* from "/docker/files/freesurfer7.3.2-exclude.txt"
- /freesurfer/mni/bin/mritotal
- /freesurfer/mni/etc/mni_autoreg
- /freesurfer/mni/share/mni_autoreg
Previously the following error was encountered 
`mritotal: Command not found. 
ERROR: mritotal failed, see transforms/talairach.log`
however, no error was logged in the log file.
The problem is now fixed.
The resulting docker image ran without error.
Fixes #3088.
> DOCKER: Remove mritotal and dependencies from FreeSurfer ignore file

- fmriprep/config.py
- fmriprep/workflows/base.py
Companion PR to nipreps/smriprep#370.
> FIX: Minor fixes to work with MSMSulc-enabled smriprep-next

- fmriprep/workflows/bold/fit.py
#3099 introduced a subtle bug where we applied the inverse transform of what we needed. This is because `init_unwarp_wf` and `init_coeff2epi_wf` have opposite conventions (point and image) for describing transforms.
This could be swapped in sdcflows, but I intend to replace `unwarp_wf` with our resampler, so this is just doing the job correctly in the meantime.
> FIX: Swap direction of fmap-EPI transform

- fmriprep/utils/transforms.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
> ENH: Restore resampling BOLD to volumetric templates

- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/hmc.py
- fmriprep/workflows/bold/outputs.py
Builds on #3116. Just check the last two commits.
> ENH: Restore confound generation

- fmriprep/interfaces/gifti.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/resampling.py
Builds on #3126.
This one splits out the selection of the MNI template for the CIFTI-2 generation from the rest of the resampling to volumetric templates. If someone requests MNI152NLin6Asym and CIFTI, then we will resample twice in the working directory, but given that resampling is significantly faster now and does not scale files per-time point, I'm okay with that. I think it's a pretty rare case, and I suspect we'll want to resample a smaller ROI than the full brain at some point, so a separate pathway for that seems okay.
> ENH: Restore CIFTI-2 generation

- fmriprep/cli/run.py
- fmriprep/utils/telemetry.py
- pyproject.toml
Strips away error handling logic, which has been ported to `migas.track_exit`.
> chore: update to latest migas api

- docs/sphinxext/github_link.py
As far as I can see, we had just added a few lines to tell this vendored script originates in scikit-learn.
File initially copied in #1258, and [not changed since](https://github.com/nipreps/fmriprep/commits/master/docs/sphinxext/github_link.py), except for #3097 which I shouldn't have applied to a vendored file.
> MNT: update vendored docs script `github_link.py`

- docker/files/freesurfer7.3.2-exclude.txt
When FreeSurfer has trouble with an image, it can reach for some more obscure tools.
Closes #3103
> DOCKER: Restore mritotal subcommands

- fmriprep/interfaces/workbench.py
- fmriprep/workflows/bold/outputs.py
I selected only a couple of suggestions that make sense:
* [FURB123]: Replace `bool(x)` with `x`
* [FURB109]: Replace `in [x, y, z]` with `in (x, y, z)`
> STY: Apply a couple refurb suggestions

- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/registration.py
- fmriprep/workflows/bold/tests/test_base.py
- fmriprep/workflows/bold/tests/test_fit.py
- fmriprep/workflows/tests/__init__.py
- fmriprep/workflows/tests/test_base.py
Turns out testing's a good idea. Starting out doing something similar to nipreps/smriprep#390. Will try to expand the smoke tests upward to `workflows.bold.base` and `workflows.base`.
> TEST: Add smoke-tests for bold_fit_wf

- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/tests/test_base.py
Add more smoke tests that build the whole workflow, setting most flags that affect workflow shape.
Added a regression test for #3154.
Fixes #3154.
> TEST: Add smoke tests for full workflow and most branching flags

- .circleci/ds005_partial_fasttrack_outputs.txt
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/resampling.py
Closes #3169. This could just be a first step toward moving one or more of these workflows from fMRIPrep to niworkflows.
- Move `init_goodvoxels_bold_mask_wf` call out of `init_bold_fsLR_resampling_wf`. This will allow downstream tools (e.g., ASLPrep) to generate the goodvoxels mask from one file (the ASL time series) and apply it to others (e.g., CBF maps).
- Clean up `init_bold_fsLR_resampling_wf` (e.g., remove unused imports and add all parameters to docstring).
- Move BOLD-to-anatomical resampling workflow call from `resampling` level to `full` level, since it doesn't produce any outputs.
> Separate goodvoxels mask creation from fsLR resampling

- fmriprep/interfaces/confounds.py
- fmriprep/interfaces/reports.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/t2s.py
I don't understand what the test complains about. Help, please?
> MAINT: load reportlets interfaces from nireports rather than niworkflows

- fmriprep/workflows/bold/resampling.py
Fixes #3178. Depends on https://github.com/nipreps/smriprep/pull/405 to actually work, but can be merged separately.
> FIX: Retrieve atlas ROIs at requested density

- fmriprep/interfaces/confounds.py
- fmriprep/interfaces/reports.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/t2s.py
Reverts nipreps/fmriprep#3176.
Looks like tests weren't passing for other reasons.
> Revert "MAINT: load reportlets interfaces from nireports rather than niworkflows"

- fmriprep/workflows/bold/confounds.py
Closes #2614 and is related to https://github.com/nipreps/niworkflows/pull/843.
- Feed `skip_vols` into confounds correlation plot. Since niworkflows is pinned to `master` in `pyproject.toml`, the new parameter from https://github.com/nipreps/niworkflows/pull/843 can be used without waiting for a niworkflows release.
> Exclude non-steady-state volumes from confound correlation plot

- fmriprep/interfaces/confounds.py
- fmriprep/interfaces/reports.py
- fmriprep/workflows/bold/confounds.py
- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/t2s.py
- pyproject.toml
Reverts nipreps/fmriprep#3182, restoring #3176. There's an issue with the CompCor reportlets to resolve before we can merge.
cc @celprov
> MNT: Load reportlets interfaces from nireports rather than niworkflows

- fmriprep/cli/parser.py
- fmriprep/interfaces/resampling.py
- fmriprep/workflows/bold/apply.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/fit.py
There is some indication (https://github.com/nipreps/sdcflows/issues/413) that fieldmap correction can lead to weird patches of intensity variation. This is almost certainly caused to modulation by the Jacobian determinant image, although the reason that this is not working as expected in these cases is unclear.
In any case, this allows the behavior to be disabled with `--ignore fmap-jacobian`.
> ENH: Allow --ignore fmap-jacobian to disable Jacobian determinant modulation during fieldmap correction

- .circleci/config.yml
- fmriprep/cli/parser.py
- fmriprep/utils/bids.py
- fmriprep/workflows/base.py
fixes #3201 
Re-enables the possibility to run fMRIPrep on a fMRI only dataset using anat derivatives from another (anatomical) dataset with the same participant. 
Tries to implement integration test for that feature.
related to #2201 
NA
> Re-enable anat fasttrack for dataset without t1w

- .circleci/config.yml
- fmriprep/cli/run.py
Closes #3209 
The exit code for `--reports-only` should be an indicator of report generation status, not whether or not errors were present in the workflow (those should be reported separately, at the time they are encountered during processing).
> TST: Update test to reflect new report generation behavior

- fmriprep/cli/parser.py
- fmriprep/config.py
Closes #3214.
- Update action in CLI for `--bids-filter-file` parameter to loop through lists and check for `null` or `*`.
- Update `Config.bids_filters` in `config.py` to loop through lists and check for `Query.ANY` or `Query.NONE`.
> FIX: Support lists in bids filter file containing `null` or `*`

- fmriprep/data/reports-spec-func.yml
To avoid repeating the same summary many times when the reports are separated by sessions, remove the summary from the functional report template.
> FIX: delete summary from functional report when separated by sessions

- Dockerfile
- docs/installation.rst
- env.yml
- requirements.txt
Updates pins for:
1) Python (3.11)
2) NodeJS (20)
3) Scipy numeric stack (conda)
4) ANTs (conda)
5) FSL (conda)
6) Python dependencies (pip)
Third party dependencies.
> MNT: Update environment pins

- fmriprep/workflows/bold/outputs.py
Closes #3237.
- Switch order of transforms in `boldref2target` node of `init_ds_volumes_wf` from boldref2anat_xfm --> anat2std_xfm to anat2std_xfm --> boldref2anat_xfm, as antsApplyTransforms expects transforms to be provided in reverse order.
none
> Flip order of transforms in `init_ds_volumes_wf`

- fmriprep/interfaces/resampling.py
> FIX: Preserve pixdim4+ of resampled images

- fmriprep/workflows/bold/base.py
Closes #3253.
- Copy code used to fill in `source_file` and `base_directory` fields for reportlet datasinks in `init_bold_wf` for the `full` level to the `resampling` level as well.
- AFAICT, the only reportlets that should be generated by the resampling level are `ds_report_t2scomp` and `ds_report_t2star_hist`, so I could directly add these fields to those nodes, but this approach seems more robust.
None
> FIX: Add datasink fill-in step to resampling level

- fmriprep/cli/run.py
- fmriprep/config.py
- fmriprep/interfaces/bids.py
- fmriprep/interfaces/tests/test_bids.py
- fmriprep/utils/bids.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/outputs.py
Closes #3252. This is just a first pass- it only modifies the RawSources for now. I can add the immediate Sources in another PR (this'll require a lot more effort).
- Add `DatasetLinks` field to the `dataset_description.json`
- The input dataset is called `raw`
- Any other datasets supplied through `--derivatives` are automatically named `deriv-<index>`. We might want to support named derivatives at some point.
- Replace BIDS-relative paths in `RawSources` fields with BIDS-URIs.
- Change `RawSources` to `Sources` in the sidecar files, since `RawSources` is deprecated.
I'll probably need to update the documentation, but haven't yet.
> ENH: Use BIDS URIs to track Sources in sidecars

- fmriprep/cli/parser.py
- fmriprep/config.py
- fmriprep/workflows/base.py
- pyproject.toml
(reopen of #3105) 
Integrate options/configs for https://github.com/nipreps/smriprep/pull/393
> ENH: Add --fs-no-resume option to reuse existing FreeSurfer outputs without resuming

- fmriprep/cli/parser.py
- fmriprep/cli/tests/test_parser.py
- fmriprep/cli/workflow.py
- fmriprep/config.py
- fmriprep/workflows/base.py
- wrapper/src/fmriprep_docker/__main__.py
Closes #3260.
- Copy over `ToDict` action from fmriprep-docker over to the main CLI parser.
- Modify the Config to handle named derivative paths.
- E.g., `--derivatives anat=/path/to/smriprep` --> `DatasetLinks = {'anat': '/path/to/smriprep'}`
- Infer derivative name from the folder name of the derivative path if it isn't labeled.
- E.g., `--derivatives /path/to/smriprep` --> `DatasetLinks = {'smriprep': '/path/to/smriprep'}`
> ENH: Support named derivative paths

- .maint/paper_author_list.py
- .maint/update_authors.py
- .maint/update_zenodo.py
- fmriprep/cli/parser.py
- fmriprep/cli/run.py
- fmriprep/cli/workflow.py
- fmriprep/utils/bids.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/resampling.py
New in [ruff v0.4.2](https://github.com/astral-sh/ruff/releases/tag/v0.4.2).
> STY: Apply ruff/pyupgrade rule UP031

- fmriprep/interfaces/reports.py
- fmriprep/workflows/base.py
These have not caught by pyupgrade or ruff.
See https://github.com/nipreps/fmriprep/pull/3147#issuecomment-1971808094.
> STY: Manual conversions to f-strings

- .pre-commit-config.yaml
Should make life a little easier on @DimitriPapadopoulos :-).
> MNT: Upgrade ruff pre-commit, add fixing checks

- fmriprep/utils/transforms.py
The ANTs utility `CompositeTransformUtil --assemble` outputs its displacement field as 'DisplacementFieldTransform_double_3_3', but utils/transform/load_ants_h5 throws an error unless it is 'DisplacementFieldTransform_float_3_3'. Presumably this is just a check to make sure it is a displacement field. The code after this check works fine for "double".
Just changing `!= b'DisplacementFieldTransform_float_3_3'` to `not in (b'DisplacementFieldTransform_float_3_3', b'DisplacementFieldTransform_float_3_3')`
None
> [FIX] Add "double" type to allowed DisplacementFieldTransform

- env.yml
libitk 5.4 was being installed, while ANTs is built against libitk 5.3.
> MNT: Pin libitk 5.3 and note dependencies

- fmriprep/utils/transforms.py
- pyproject.toml
Alternative to (and builds on) #3296.
Closes #3296.
> RF: Fix ITK warp conversion to nitransforms format

- fmriprep/data/reports-spec-anat.yml
- fmriprep/data/reports-spec-func.yml
- fmriprep/data/reports-spec.yml
Noticed that nireports injects its own title, because we aren't adding ours:
> ENH: Add appropriate titles to HTML reports

- .circleci/ds054_fasttrack_outputs.txt
- .circleci/ds054_outputs.txt
Following https://github.com/nipreps/sdcflows/pull/453, we are no longer storing multi-level coefficients.
> CI: Fix expected outputs for fieldmaps

- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/tests/test_base.py
- fmriprep/workflows/bold/tests/test_fit.py
~~Not backportable as-is, although the change is very small. To backport into 24.0.x, we could check whether `sbref_files[0]` is 4D, and fall back to the existing code if not.~~
This only modifies the workflow in a known-breaking case. Safe for bug-fix releases.
Closes #3319.
> FIX: Validate and summarize multi-volume sbrefs

- .readthedocs.yml
- docs/conf.py
Following the advice of https://about.readthedocs.com/blog/2024/07/addons-by-default/.
Starting on the LTS, since there's still a chance a new release would come out.
> DOC: Read html_baseurl from RTD environment, if available

- docs/workflows.rst
- fmriprep/workflows/bold/apply.py
- fmriprep/workflows/bold/registration.py
- fmriprep/workflows/bold/stc.py
- pyproject.toml
* sphinx-argparse v0.5.0 broke our builds, so blacklist: https://github.com/sphinx-doc/sphinx-argparse/issues/56
* Backport some fixes from #3312.
> fix(doc-build): Address errors/warnings in RTD builds

- fmriprep/workflows/base.py
Companion to https://github.com/nipreps/smriprep/pull/433
> RF: Adapt to less T1w-centric smriprep

- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/resampling.py
Closes #3337.
- Use `output_dir` function argument for `BIDSURI` objects instead of the `config.execution.fmriprep_dir` field. This will let other preps (e.g., ASLPrep) use these workflow functions without having to mock up `fmriprep_dir` fields in their config objects.
> RF: Replace `config.execution.fmriprep_dir` uses in BIDSURI calls with `output_dir` parameter

- fmriprep/data/io_spec.json
- fmriprep/utils/bids.py
- fmriprep/utils/tests/test_derivative_cache.py
Closes #3368 
This required massaging several kinks from `collect_derivatives`, so careful review of that would be appreciated.
> FIX: Repair search for precomputed transforms

- fmriprep/utils/bids.py
- fmriprep/utils/tests/test_derivative_cache.py
Following through with suggested change: https://github.com/nipreps/fmriprep/pull/3369#pullrequestreview-2343043830; previously, precalculated baseline/boldref niftis would not be found.
> Fix: Repair and test query for precalculated baseline/boldref files

- fmriprep/utils/transforms.py
A user with a custom template is generating warps that have spacing `[1.5 1.5 1.5]`: https://neurostars.org/t/use-custom-dartel-template-in-fmriprep/30670/8
The check for unit spacing was mostly intended to avoid weird behavior where we might generate a bad affine. The interpretation of isotropic spacing is straightforward, so I think we can relax this. Creating a docker image to allow for testing.
> fix: Remove checks for unit zooms and symmetric rotations in template warp

- .circleci/config.yml
- .github/workflows/docker.yml
This PR is a potential model for nipreps using GHA to build Docker images. The latest build (from a previous commit's cache) took 2 minutes, including checkout, build and push. If the cache needs rebuilding, it's <10 minutes. This is a vast improvement from Circle all on it's own.
I will make a separate PR to start triggering Circle builds from GHA after build. I would like to get to a model of:
```mermaid
graph LR;
subgraph GitHub;
test & build
end
subgraph Circle
build --> ds005 & ds054 & ds210
end
subgraph gh2["GitHub"]
test & ds005 & ds054 & ds210 --> deploy
end
```
Where Circle runs anything where we want inspectable artifacts and nothing else. For SDCflows, it would be tests again, but with artifact saving turned on.
> CI: Build docker images in GHA, store cache inline and push to GHCR

- .github/workflows/docker.yml
- Dockerfile
This tests the behavior of PRs with the docker build. It should reuse the `ghcr.io/nipreps/fmriprep:master` cache and create `ghcr.io/nipreps/fmriprep:pull-3381` or similar.
It also checks out enough history to properly create a version string.
> CI: Fetch tags and 200 commits to support describe

- Dockerfile
- env.yml
The entire package (14MB) is smaller than the statically linked c3d_affine_tool (116MB).
> Install c3d through conda

- fmriprep/cli/parser.py
This PR removes [pkgutil.find_loader()][] and replaces it with [importlib.util.find_spec()][]. `find_loader` was deprecated in Python 3.12 and will be removed in 3.14. `find_spec` has been present since Python 3.4.
Both functions return `None` if the module loader cannot be found. For its use in this project, this is sufficient and no translation of the return value is needed.
[pkgutil.find_loader()]: https://docs.python.org/3/library/pkgutil.html#pkgutil.get_loader
[importlib.util.find_spec()]: https://docs.python.org/3/library/importlib.html#importlib.util.find_spec
> rf(py314): Replace deprecated pkgutil.find_loader

- CHANGES.rst
- fmriprep/workflows/bold/outputs.py
While attempting to reproduce a bug report, I ran across a crash. Fieldmaps are always in RAS, while the BOLD references and masks are in the space of the original BOLD. In the case of ds000221, that's LSP. The reportlet assumes all input images are in the same space, and so can fail if the field-of-view is not a cube (and would be bad otherwise).
I was unable to reproduce the reported bug, but it's possible it was confused for this. For searchability's sake, the error was:
```
2024-10-21 12:21:37,963 [CRITICAL] fMRIPrep failed: Traceback (most recent call last):
File "/home/chris/mambaforge/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
result["result"] = node.run(updatehash=updatehash)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> FIX: Ensure fieldmap is resampled correctly in report

- fmriprep/workflows/base.py
> ENH: Flexibilize "sophisticated" pepolar to allow monomodal execution

- fmriprep/reports/core.py
> fix: Listify sessions when generating reports

- fmriprep/cli/parser.py
- fmriprep/reports/core.py
- fmriprep/utils/bids.py
We had some `.lstrip()`s that should be `removeprefix()` as well as some pre-`removeprefix()` hacks of the form `s[len(prefix):] if s.startswith(prefix) else s`.
> fix: Use removeprefix instead of lstrip or ternary operator

- .circleci/ds005_partial_fasttrack_outputs.txt
- .circleci/ds005_partial_outputs.txt
- fmriprep/workflows/base.py
- pyproject.toml
- scripts/fetch_templates.py
Integration of nipreps/smriprep#460.
> feat: Output fsLR meshes on subject surfaces

- fmriprep/workflows/bold/fit.py
Overall seems safe, the `skullstrip_wf` is extracted from the `enhance_and_skullstrip_wf`, skipping reruns.
Running locally now. We'll see if does address #3406.
> fix: Use consistent skull-stripping pre- and post- SDC

- .maint/update_authors.py
- .maint/update_zenodo.py
- .pre-commit-config.yaml
- fmriprep/_warnings.py
- fmriprep/cli/parser.py
- fmriprep/cli/workflow.py
- fmriprep/config.py
- fmriprep/interfaces/workbench.py
- fmriprep/reports/tests/test_reports.py
- fmriprep/utils/bids.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/stc.py
- pyproject.toml
- wrapper/pyproject.toml
Upgrade ruff to the latest 0.9.1. Enable `ISC001` as it now documented as compatible with the formatter.
> Upgrade to ruff 0.9.1

- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/reference.py
This builds on #3427 to add a couple final things to the transform-only workflow:
```
fmriprep $BIDS $OUT participant --derivatives fmriprep=$MINIMAL
```
BOLD masks were not getting generated from the boldref and dummy scans were not being estimated.
This PR factors out the validation and dummy scan detection from `init_raw_boldref_wf` and uses the full workflow in fit mode and the subworkflow in transform mode.
Will rebase after #3427 is merged. Can compare now with: https://github.com/nipreps/fmriprep/compare/c28a6158e80bd054284533ff85f0ba5719606bb4...6c78e547d43ca4faa68ee72c21d872548daaf586
> fix: Calculate bold mask and dummy scans in transform-only runs

- docs/outputs.rst
minor fix to the docs
outputs docs
> [DOC] fix xfm extension in the outputs docs

- fmriprep/cli/parser.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/fit.py
Builds on #3442.
Closes #3367.
> feat: Enable Jacobians only for PEPOLAR by default, allow forcing

- fmriprep/cli/parser.py
- fmriprep/cli/run.py
Pretty straightforward. We said we'd remove these things, and now they're removed. It's been a full year and two minor versions with the deprecation warnings.
> feat(cli): Remove CLI flags with expired deprecation periods

- fmriprep/interfaces/resampling.py
This PR addresses an interpolation effect when the brain signal goes right up to the edge of the image.
We have used the [scipy.ndimage.map_coordinates](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.map_coordinates.html) default interpolation mode of `"constant"`, which extends the input image with zeros when necessary to perform interpolation (within two voxels of the edge, for the cubic interpolation we do). This will frequently result in zeroed-out portions of edge voxels.
This generally works well when the image field of view is large enough to fully contain the brain, but can cause problems for limited field-of-view scans or images where the brain tissue can be found in the edge voxels.
By switching to `nearest`, the edge voxels are extended out. For images with …
> fix(resampling): Use nearest mode for extrapolating data outside image boundaries

- fmriprep/data/fmap_spec.json
Discovered while testing precomputed derivatives in aslprep, which imports `fmriprep.utils.bids.collect_fieldmaps`. See https://github.com/PennLINC/aslprep/pull/518.
For PEPolar fieldmaps, the fieldmap reference is often `desc-epi_fieldmap.nii.gz`, as opposed to `desc-magnitude_fieldmap.nii.gz`. IMO, it would be good to change `desc-{epi,preproc}_fieldmap.nii.gz` to `desc-preproc_{magnitude,fieldmap}.nii.gz`, but this is what it is for now.
> fix: Improve retrieval of precomputed pepolar fieldmaps

- pyproject.toml
Declare licenses using only these two fields, as per PEP 639:
* `license`: SPDX license expression consisting of one or more license identifiers
* `license-files`: list of license file glob patterns
Supported by hatchling ≥ 1.27.0:
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files
N/A
> MNT: PEP 639 compliance

- .git-blame-ignore-revs
- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/outputs.py
- fmriprep/workflows/bold/registration.py
> feat: Add registration metadata to boldref-to-anat transforms

- .circleci/ds005_fasttrack_outputs.txt
- .circleci/ds005_outputs.txt
- .circleci/ds005_partial_fasttrack_outputs.txt
- .circleci/ds005_partial_outputs.txt
- fmriprep/workflows/base.py
Closes #3511. I don't think I accounted for the versions of aseg and aparcaseg that get written out to the func directory, and I haven't thought about precomputed derivatives at all.
- Add Freesurfer-related section from sMRIPrep's `init_anat_preproc_wf` to `init_single_subject_wf`
> FIX: Write out Freesurfer-derived outputs

- fmriprep/workflows/bold/confounds.py
Document `freesurfer` parameter in BOLD confound workflow initialization function.
Take advantage of the commit to move the `name` parameter docstring after `freesurfer` to match the function signature.
`init_bold_confs_wf` function.
> DOC: Document `freesurfer` parameter in BOLD confound workflow init

- .circleci/ds005_partial_fasttrack_outputs.txt
- .circleci/ds005_partial_outputs.txt
- fmriprep/workflows/bold/base.py
Closes #3510. I'm happy to move the DerivativesDataSink into `init_goodvoxels_bold_mask_wf` if the current approach clutters up the workflow too much.
- Add a DerivativesDataSink to `init_bold_wf` to write out the goodvoxels mask.
- Update the expected outputs for relevant tests.
> ENH: Write out goodvoxels mask

- .maint/paper_author_list.py
- .maint/update_authors.py
- .maint/update_zenodo.py
- fmriprep/cli/parser.py
- fmriprep/cli/run.py
- fmriprep/cli/workflow.py
- fmriprep/config.py
- fmriprep/interfaces/reports.py
- fmriprep/utils/bids.py
- fmriprep/workflows/base.py
- fmriprep/workflows/bold/base.py
- fmriprep/workflows/bold/fit.py
- fmriprep/workflows/bold/hmc.py
- fmriprep/workflows/bold/registration.py
- fmriprep/workflows/bold/resampling.py
Make use of f-strings extensive: prefer using f-strings for string interpolation and formatting instead of the modulo operator and the `str.format()` method.
f-strings have become the preferred method for Python string formatting since their introduction in Python 3.6:
https://peps.python.org/pep-0498/
The code becomes more concise and readable.
N/A.
> STY: Make use of f-strings extensive

- .circleci/config.yml
- .dockerignore
- .github/workflows/docker.yml
- Dockerfile
- Dockerfile.base
- Makefile
FreeSurfer downloads are extremely finicky, and I feel bad about hitting their server as much as we do. This is something we experimented on in PETPrep, to put the non-Pixi (conda, in PETPrep) dependencies in one image that gets pushed to ghcr.io, and then building on top of that.
> chore: Split Dockerfile into base and pixi layers

- fmriprep/workflows/base.py
Summary should receive the actual T1w files found, not a phony source file
Closes https://github.com/nipreps/fmriprep/issues/3530
> fix: pass actual t1w files to summary interface
